import OrganicVitals from '@/app/organic-vitals';
import {env} from 'cloudflare:workers';
import {headers} from 'next/headers';
import {indexState,canonicalURL} from '@/lib/organic-core';
import MarketingTracker from '@/app/marketing-tracker';
import {companyDetails} from '@/lib/company';
import {publicAboutDocument} from '@/lib/about-cms';
import {publicHubSettings,helpFAQs,hubSettings} from '@/lib/travel-hub';
import {editorialContent} from '@/lib/editorial';
import {publishedReviews} from '@/lib/review-engine';
import {presenceProfile} from '@/lib/search-presence';
import {seoProfile,record404} from '@/lib/seo-platform';
import {socialImage,visibleAnswers,contentSchemas} from '@/lib/content-visibility';
import {discoveryData} from '@/lib/discovery-server';
import {clientSummary} from '@/lib/client-summary';
import {notFound} from 'next/navigation';
import {pages,logo} from '@/lib/model';
import {config,tourConfig,db,identity,editablePages} from '@/lib/server';
import Site from '@/app/site';
import organized from '@/data/organized-content.json';
export const dynamic='force-dynamic';
const system=['/login/','/signup/','/partners/','/gifts/','/account/','/admin/','/wishlist/','/verify/'];
async function resolve(params:Promise<{slug?:string[]}>){const p=await params;const segments=[...(p.slug||[])];const lang=['fr','es'].includes(segments[0])?segments.shift()!:'en';const path='/'+segments.join('/')+(segments.length?'/':'');const all=await editablePages();const original=all.find(x=>x.path===path&&!x.draft);let translation:any=null;const alternates:Record<string,string>={en:'https://www.tangierexcursions.com'+path,'x-default':'https://www.tangierexcursions.com'+path};if(original){try{const r=await db().prepare('SELECT key,value FROM settings WHERE key IN (?,?)').bind('translation:fr:'+path,'translation:es:'+path).all<any>();for(const x of r.results){const l=x.key.split(':')[1],t=JSON.parse(x.value);if(t.reviewed){alternates[l]='https://www.tangierexcursions.com/'+l+(path==='/'?'/':path);if(l===lang)translation=t}}}catch{}}return {path,lang,original,translation,alternates};}
export async function generateMetadata({params}:{params:Promise<{slug?:string[]}>}){const {original:p,translation:t,lang,path,alternates}=await resolve(params);if(!p)return {title:'Tangier Excursions — Test workspace',robots:{index:false,follow:false}};const saved=await seoProfile(path,p),published=saved.status==='published'?saved:null;const title=t?.title||published?.title||p.title,description=t?.description||published?.description||p.meta.description;const canonical=lang==='en'?canonicalURL(published?.canonical||p.canonical[0]||p.url):'https://www.tangierexcursions.com/'+lang+(path==='/'?'/':path);const ogImage=socialImage(published?.openGraph?.image||p.featuredImage||p.gallery?.[0]||p.meta['og:image']),xImage=socialImage(published?.twitter?.image)||ogImage;const hdr=await headers(),live=(env as any).SEO_PUBLIC_INDEXING==='true'&&/^(www\.)?tangierexcursions\.com$/.test((hdr.get('host')||'').split(':')[0]),eligibility=indexState(p,published||saved);const other:Record<string,string>={};for(const [k,v] of Object.entries(p.meta)){if(k&&typeof v==='string'&&!['description','robots','viewport','charset'].includes(k)&&!k.startsWith('og:')&&!k.startsWith('twitter:'))other[k]=v;}return {title,description,alternates:{canonical,languages:alternates},robots:{index:live&&eligibility.index,follow:live&&eligibility.follow,googleBot:{index:live&&eligibility.index,follow:live&&eligibility.follow,maxSnippet:published?.maxSnippet??-1,maxImagePreview:published?.maxImagePreview||'large',maxVideoPreview:published?.maxVideoPreview??-1}},other,openGraph:{title:t?title:published?.openGraph?.title||p.meta['og:title']||title,description:t?description:published?.openGraph?.description||p.meta['og:description']||description,url:canonical,images:ogImage?[{url:ogImage,alt:p.imageAlt||p.name}]:[]},twitter:{card:'summary_large_image',title:t?title:published?.twitter?.title||published?.openGraph?.title||p.meta['twitter:title']||title,description:t?description:published?.twitter?.description||published?.openGraph?.description||p.meta['twitter:description']||description,images:xImage?[xImage]:[]}};}
export default async function Page({params}:{params:Promise<{slug?:string[]}>}){const {path,original,lang,translation}=await resolve(params);if(lang!=='en'&&!translation)notFound();const page:any=original?{...original,organized:original.product?.sections||(organized as any)[path]}:null;if(page?.kind==='tour'){try{page.pricing=(await tourConfig(path)).tiers}catch{}}if(!page&&!system.includes(path)){const h=await headers();await record404(path,h.get('referer')||'',h.get('user-agent')||'').catch(()=>{});notFound()}let overrides:Record<string,any>={};try{const r=await db().prepare("SELECT key,value FROM settings WHERE key LIKE 'tour:%'").all<any>();for(const x of r.results)overrides[x.key.slice(5)]=JSON.parse(x.value)}catch{}
 if(page&&(['/destinations/','/faqs/','/about-us/','/transport_booking/'].includes(path)||page.destinationId)){page.hubData={settings:await publicHubSettings(),faqs:await helpFAQs(await editablePages())};}if(page&&!page.hubData){const shared=await hubSettings();page.sharedHelp=Object.entries(shared).filter(([k,v]:any)=>k.startsWith('faq:')&&v.published&&(v.relatedTours?.includes(path)||v.relatedPages?.includes(path))).map(([,v])=>v);}if(page?.path==='/about-us/'){page.aboutDocument=await publicAboutDocument();page.aboutCompany=await companyDetails();page.aboutReviews=await publishedReviews();}if(page){page.companyEntity=await companyDetails();if(page.kind!=='tour')page.editorial=editorialContent(page);page.visibility=await seoProfile(path,page);page.presence=visibleAnswers(await presenceProfile(path),page.visibility);page.guestReviews=await publishedReviews(['/', '/tangier-excursions-reviews/'].includes(path)?undefined:path);}
 const currentUser=await identity().catch(()=>null);const summaries=(await editablePages()).filter(p=>!p.draft||path==='/admin/'&&currentUser?.role==='admin').map((p:any)=>{const s=clientSummary(p,overrides[p.path]?.tiers,overrides[p.path]?.mode);if(path!=='/admin/'){s.gallery=[s.featuredImage||s.image].filter(Boolean);if(s.product)s.product.media=[]}return s});return <>{page&&<OrganicVitals template={path==='/'?'home':page.knowledge?'knowledge':page.landing?'landing':page.destinationId?'destination':page.kind}/ >}{page&&<MarketingTracker path={path} kind={page.kind} destination={!!page.destinationId} landing={!!page.landing}/ >}{(page?contentSchemas(page,page.visibility):[]).map((s:string,i:number)=><script key={i} type="application/ld+json" dangerouslySetInnerHTML={{__html:s}}/>)}<Site initialMarketing={path==='/'?(await config()).homeMarketing:undefined} initialDiscovery={await discoveryData()} initialUser={currentUser} page={page?.product?.golden?{...page,visibility:undefined,content:'',organized:{},product:{...page.product,operations:undefined,sections:{},golden:{...page.product.golden,migration:undefined}}}:(page?{...page,visibility:undefined}:null)} catalog={summaries} path={path} logo={logo} initialLang={lang} initialTranslation={translation}/></>}
