import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const wranglerRequire=createRequire(require.resolve('wrangler/package.json'));
const {Miniflare}=wranglerRequire('miniflare');
const root=process.cwd();
const mf=new Miniflare({modules:[{type:'ESModule',path:path.join(root,'dist/server/index.js')},...fs.readdirSync('dist/server',{recursive:true}).filter(x=>x.endsWith('.js')&&x!=='index.js').map(x=>({type:'ESModule',path:path.join(root,'dist/server',x)}))],modulesRoot:path.join(root,'dist/server'),modulesRules:[{type:'ESModule',include:['**/*.js'],fallthrough:true}],compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'test-database'},r2Buckets:{MEDIA:'test-media'},bindings:{ADMIN_USER_IDS:'test-admin'},assets:{directory:path.join(root,'dist/client'),binding:'ASSETS',routerConfig:{has_user_worker:true,invoke_user_worker_ahead_of_assets:true}},cf:false});
const evidence=[];
const record=(name)=>{evidence.push({name,status:'passed'});console.log('PASS',name)};
try{
 const database=await mf.getD1Database('DB');
 for(const filename of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())for(const stmt of fs.readFileSync('drizzle/'+filename,'utf8').split('--> statement-breakpoint').map(x=>x.trim()).filter(Boolean))await database.prepare(stmt).run();
 async function request(op,body,user='test-customer'){const headers={'Content-Type':'application/json',Origin:'http://test.local'};if(user){headers['oai-authenticated-user-id']=user;headers['oai-authenticated-user-email']=user+'@example.test'}const r=await mf.dispatchFetch('http://test.local/api/'+op,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:JSON.stringify(body)})});const raw=await r.text();if(!raw)throw new Error('Empty '+r.status+' response for '+op+' '+JSON.stringify([...r.headers]));const data=JSON.parse(raw);return {status:r.status,data}}

 const catalog=JSON.parse(fs.readFileSync('data/catalog.json','utf8'));const tourPages=catalog.filter(p=>p.kind==='tour');
 let models=(await request('cms-tours',undefined,'test-admin')).data;
 for(const p of tourPages){const g=(await request('golden-admin?path='+encodeURIComponent(p.path),undefined,'test-admin')).data;assert.equal(g.original,p.content);assert.equal(g.tour.path,p.path);const saved=await request('golden-save',{action:'save',tour:g.tour},'test-admin');assert.equal(saved.status,200,p.path+' '+saved.data.error);assert.deepEqual((await request('golden-admin?path='+encodeURIComponent(p.path),undefined,'test-admin')).data.tour.overview,g.tour.overview)}record('All 40 structured tours save and reload with immutable original source');
 const route=Object.values(models).find(t=>t.golden.itineraryMode==='day');let g=(await request('golden-admin?path='+encodeURIComponent(route.path),undefined,'test-admin')).data.tour;const day=g.itinerary.find(s=>s.type==='day');day.events=[{id:'qa-event',type:'time',label:'Approx. 14:30',title:'QA nested event',location:'QA location',description:[{text:'QA timing note',links:[]}],duration:'30 minutes',image:'',note:'Approximate',lat:35.78,lng:-5.8,mapOrder:1}];day.accommodation='QA reviewed accommodation';g.timeFormat='12';assert.equal((await request('golden-save',{action:'save',tour:g},'test-admin')).status,200);const reread=(await request('golden-admin?path='+encodeURIComponent(route.path),undefined,'test-admin')).data.tour;assert.equal(reread.itinerary.find(s=>s.id===day.id).events[0].title,'QA nested event');let html=await (await mf.dispatchFetch('http://test.local'+route.path)).text();assert.ok(html.includes('QA nested event'));assert.ok(html.includes('Approx. 2:30 pm'));assert.ok(html.includes('QA reviewed accommodation'));record('Nested timed events, accommodation and 12-hour display persist and render on multiday tours');
 g.itinerary.find(s=>s.id===day.id).events=[];await request('golden-save',{action:'save',tour:g},'test-admin');assert.equal((await request('golden-admin?path='+encodeURIComponent(route.path),undefined,'test-admin')).data.tour.itinerary.find(s=>s.id===day.id).events.length,0);record('Nested itinerary event deletion persists');
 let copy=await request('cms-duplicate',{path:route.path},'test-admin');assert.equal(copy.status,200);assert.equal(copy.data.status,'draft');assert.equal(copy.data.golden.path,copy.data.path);assert.equal(copy.data.golden.reviews.length,0);const draft=copy.data.path;let dg=(await request('golden-admin?path='+encodeURIComponent(draft),undefined,'test-admin')).data.tour;dg.overview=[{text:'QA draft-only overview',links:[]}];assert.equal((await request('golden-save',{action:'save',tour:dg},'test-admin')).status,200);assert.equal((await request('golden-admin?path='+encodeURIComponent(draft),undefined,'test-admin')).data.tour.overview[0].text,'QA draft-only overview');assert.equal((await mf.dispatchFetch('http://test.local'+draft)).status,404);assert.equal((await request('cms-delete',{path:draft},'test-admin')).status,200);assert.equal((await request('golden-admin?path='+encodeURIComponent(draft),undefined,'test-admin')).status,400);record('Duplicate copies structured itinerary as an unpublished draft; draft editing and protected deletion work');
 const article=catalog.find(p=>p.kind==='article'&&p.path.includes('how-to-get'));const linked=tourPages[0].path;let b={path:article.path,name:article.name,kind:'article',image:'',intro:'',reviewed:true,category:'Travel Tips',editorial:{featured:true,quickAnswer:'QA source-based quick answer',relatedTours:[linked],author:'QA editor',showPlanning:true,order:1}};assert.equal((await request('page-edit',b,'test-customer')).status,403);assert.equal((await request('page-edit',b,'test-admin')).status,200);html=await (await mf.dispatchFetch('http://test.local'+article.path)).text();assert.ok(html.includes('QA source-based quick answer'));assert.ok(html.includes('QA editor'));assert.ok(html.includes('desktop-article-toc'));assert.ok(html.includes('mobile-article-toc'));assert.ok(html.includes('href="'+linked+'"'));assert.ok(html.includes(article.canonical[0]));const settings=(await request('admin',undefined,'test-admin')).data.settings;assert.equal(JSON.parse(settings.find(s=>s.key==='page:'+article.path).value).editorial.featured,true);record('Journal settings persist through admin authentication and update server-rendered article without altering canonical');
 assert.equal((await request('page-edit',{...b,editorial:{...b.editorial,relatedTours:['/invented-tour/']}},'test-admin')).status,400);await request('page-edit',{...b,editorial:{...b.editorial,quickAnswer:'',relatedTours:[],featured:false}},'test-admin');html=await (await mf.dispatchFetch('http://test.local'+article.path)).text();assert.ok(!html.includes('<p>QA source-based quick answer</p>'));record('Unknown editorial relationships rejected; clearing recommendations and answers persists');
 assert.equal((await request('article-feedback',{path:article.path,helpful:'yes',consent:false},null)).status,400);assert.equal((await request('article-feedback',{path:article.path,helpful:'yes',consent:true},null)).status,200);const count=await database.prepare('SELECT value FROM settings WHERE key=?').bind('article-feedback:yes:'+article.path).first();assert.equal(count.value,'1');record('Guide helpfulness uses consented anonymous aggregate without storing identity');
 for(const p of ['/morocco-travel-blog/','/about-us/','/terms-conditions/','/seville-to-morocco-tours/']){html=await (await mf.dispatchFetch('http://test.local'+p)).text();assert.ok(html.includes('footer-preferences'),p);assert.ok(html.includes('Choose language'),p);assert.ok(html.includes('Choose currency'),p)}assert.equal((await mf.dispatchFetch('http://test.local/nonexistent-qa-page/')).status,404);record('Journal, About, legal and landing pages expose shared footer controls; custom 404 retains correct status');
 fs.writeFileSync('migration/experience-system-test-results.json',JSON.stringify({passed:evidence.length,checks:evidence},null,2));console.log('TOTAL',evidence.length);
}finally{await mf.dispose()}
