import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const wranglerRequire=createRequire(require.resolve('wrangler/package.json'));
const {Miniflare}=wranglerRequire('miniflare');
const root=process.cwd();
const mf=new Miniflare({modules:[{type:'ESModule',path:path.join(root,'dist/server/index.js')},...fs.readdirSync('dist/server',{recursive:true}).filter(x=>x.endsWith('.js')&&x!=='index.js').map(x=>({type:'ESModule',path:path.join(root,'dist/server',x)}))],modulesRoot:path.join(root,'dist/server'),modulesRules:[{type:'ESModule',include:['**/*.js'],fallthrough:true}],compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'test-database'},r2Buckets:{MEDIA:'test-media'},bindings:{ADMIN_USER_IDS:'test-admin'},assets:{directory:path.join(root,'dist/client'),binding:'ASSETS',routerConfig:{has_user_worker:true,invoke_user_worker_ahead_of_assets:true}},cf:false});
const evidence=[];
const record=(name)=>{evidence.push({name,status:'passed'});console.log('PASS',name)};
try{
 const database=await mf.getD1Database('DB');
 for(const filename of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())for(const stmt of fs.readFileSync('drizzle/'+filename,'utf8').split('--> statement-breakpoint').map(x=>x.trim()).filter(Boolean))await database.prepare(stmt).run();
 async function request(op,body,user='test-customer'){const headers={'Content-Type':'application/json',Origin:'http://test.local'};if(user){headers['oai-authenticated-user-id']=user;headers['oai-authenticated-user-email']=user+'@example.test'}const r=await mf.dispatchFetch('http://test.local/api/'+op,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:JSON.stringify(body)})});const raw=await r.text();if(!raw)throw new Error('Empty '+r.status+' response for '+op+' '+JSON.stringify([...r.headers]));const data=JSON.parse(raw);return {status:r.status,data}}
 const tour='/tangier-day-trips/full-day-trip-to-tangier-from-tarifa-spain/';const date='2027-06-15';
 let r=await request('golden-admin',undefined,null);assert.equal(r.status,403);r=await request('golden-admin',undefined,'test-customer');assert.equal(r.status,403);record('Migration review requires an authenticated administrator');
 r=await request('golden-admin',undefined,'test-admin');assert.equal(r.status,200);const initial=structuredClone(r.data.tour),original=r.data.original;let shared=structuredClone(r.data.shared);assert.equal(initial.itinerary.length,7);assert.equal(initial.reviews.length,4);assert.equal(r.data.inventory.filter(t=>t.status!=='NOT STARTED').length,40);assert.ok(r.data.coverage.every(s=>!s.needsReview));record('Approved Tarifa reference retains seven stops, four source reviews and complete mapped-block coverage');
 assert.equal(initial.facts.find(f=>f.label==='Ferry tickets').value,'Optional');assert.ok(initial.optional.some(b=>b.text.includes('ferry')));assert.equal(initial.cancellation.body.length,0);record('Optional ferry and missing cancellation policy are not invented as inclusions');
 async function render(){const response=await mf.dispatchFetch('http://test.local'+tour);assert.equal(response.status,200);return (await response.text()).replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'')}
 let html=await render();assert.ok(html.includes('golden-tour'));assert.ok(html.includes('golden-timeline'));assert.ok(html.includes('Optional arrangements'));assert.ok(html.includes('Great Personal Service'));assert.ok(!html.includes('Why would Book'));assert.ok(!html.includes('old Elementor'));assert.equal((html.match(/id="overview"/g)||[]).length,1);assert.equal((html.match(/id="included"/g)||[]).length,1);record('Golden frontend renders structured content once with source reviews and no legacy template');
 const model=(await request('cms-tours',undefined,'test-admin')).data;assert.equal(Object.values(model).filter(t=>t.golden).length,40);record('All 40 audited tours use the approved shared template');
 r=await request('golden-save',{action:'save',tour:initial},'test-customer');assert.equal(r.status,403);r=await request('golden-save',{action:'save',tour:{...initial,path:'/other-tour/'}},'test-admin');assert.equal(r.status,400);record('Customer mutation and unknown tour URLs are blocked');
 let edit=structuredClone(initial);edit.overview[0].text+=' QA persistent overview marker.';edit.highlights.push({text:'QA highlight',links:[]});edit.itinerary.push({...edit.itinerary[0],id:'qa-stop',title:'QA itinerary stop',label:'Day 2',type:'day',mapOrder:8});edit.itineraryMode='day';edit.sectionOrder=[...edit.sectionOrder].reverse();r=await request('golden-save',{action:'save',tour:edit},'test-admin');assert.equal(r.status,200);let fresh=(await request('golden-admin',undefined,'test-admin')).data;assert.equal(fresh.tour.itinerary.length,8);assert.equal(fresh.tour.itineraryMode,'day');assert.equal(fresh.tour.sectionOrder[0],'faqs');assert.equal(fresh.original,original);html=await render();assert.ok(html.includes('QA persistent overview marker.'));assert.ok(html.includes('QA itinerary stop'));record('Structured content, itinerary creation, mode and section order persist and render after fresh reads');
 edit=fresh.tour;edit.itinerary.reverse();edit.itinerary=edit.itinerary.filter(s=>s.id!=='qa-stop');edit.highlights=edit.highlights.filter(b=>b.text!=='QA highlight');r=await request('golden-save',{action:'save',tour:edit},'test-admin');assert.equal(r.status,200);fresh=(await request('golden-admin',undefined,'test-admin')).data;assert.equal(fresh.tour.itinerary.length,7);assert.equal(fresh.tour.itinerary[0].id,'stop-7');record('Itinerary reordering and deletion persist without deleting source');
 edit=structuredClone(initial);edit.itinerary[0].lat=120;r=await request('golden-save',{action:'save',tour:edit},'test-admin');assert.equal(r.status,400);edit=structuredClone(initial);edit.links.push({text:'Bad',href:'javascript:alert(1)'});r=await request('golden-save',{action:'save',tour:edit},'test-admin');assert.equal(r.status,400);record('Map coordinates and unsafe links are validated server-side');
 r=await request('golden-save',{action:'approve',tour:initial},'test-admin');assert.equal(r.status,400);assert.match(r.data.error,/cancellation/i);record('Approval is blocked while the cancellation policy is missing');
 edit=structuredClone(initial);edit.included=[];r=await request('golden-save',{action:'save',tour:edit},'test-admin');assert.equal(r.status,200);fresh=(await request('golden-admin',undefined,'test-admin')).data;assert.ok(fresh.coverage.some(s=>s.field==='included'&&s.needsReview));record('Comparison flags information removed from the mapped field');
 shared.blocks=[{id:'qa-information',kind:'information',scope:'global',title:'QA reusable information',icon:'info',body:[{text:'QA inherited content',links:[]}]}];shared.maps={provider:'none',zoom:9,style:'standard',animate:false};shared.cancellation=[{text:'QA test-only reviewed policy',links:[]}];r=await request('golden-save',{action:'shared',shared},'test-admin');assert.equal(r.status,200);edit=structuredClone(initial);edit.reusableIds=['qa-information'];edit.cancellation.mode='global';r=await request('golden-save',{action:'save',tour:edit},'test-admin');assert.equal(r.status,200);html=await render();assert.ok(html.includes('QA inherited content'));assert.ok(html.includes('QA test-only reviewed policy'));fresh=(await request('golden-admin',undefined,'test-admin')).data;assert.equal(fresh.shared.maps.provider,'none');record('Reusable information, inherited policy and provider settings persist into frontend');
 r=await request('golden-save',{action:'shared',shared:{...shared,blocks:[]}},'test-admin');assert.equal(r.status,400);record('In-use reusable information cannot be deleted');
 edit.reusableIds=[];await request('golden-save',{action:'save',tour:edit},'test-admin');r=await request('golden-save',{action:'shared',shared:{...shared,blocks:[]}},'test-admin');assert.equal(r.status,200);record('Unused reusable information deletion persists');
 edit.map.pointsReviewed=true;edit.migration.decisions={itinerary:'QA review',map:'QA review',cancellation:'QA review',faqs:'QA review'};r=await request('golden-save',{action:'approve',tour:edit},'test-admin');assert.equal(r.status,200);assert.equal(r.data.status,'APPROVED');assert.ok(r.data.migration.approvedAt);record('Individual content approval works only after required reviews');
 edit=structuredClone(initial);const transFields=['overview','facts','highlights','itinerary','included','excluded','optional','before','cancellation','faqs'];edit.translations={fr:{reviewed:true,content:Object.fromEntries(transFields.map(k=>[k,structuredClone(edit[k])]))}};edit.translations.fr.content.overview=[{text:'Exemple français pour QA',links:[]}];r=await request('golden-save',{action:'save',tour:edit},'test-admin');assert.equal(r.status,200);fresh=(await request('golden-admin',undefined,'test-admin')).data;assert.equal(fresh.tour.translations.fr.content.overview[0].text,'Exemple français pour QA');assert.equal(fresh.tour.status,'REVIEW REQUIRED');record('Structured translations persist and editing resets approval status');
 await request('golden-save',{action:'save',tour:initial},'test-admin');await request('golden-save',{action:'shared',shared:{cancellation:[],blocks:[],maps:{provider:'openstreetmap',zoom:10,style:'standard',animate:true}}},'test-admin');
 r=await request('quote',{tour,date,adults:4,children:0,infants:0,extras:[],currency:'EUR'});assert.equal(r.status,200);assert.equal(r.data.total,34800);const q=r.data;record('Golden Tour booking quote preserves audited EUR 348 tier for four travelers');
 r=await request('booking',{tour,date,adults:4,children:0,infants:0,extras:[],currency:'EUR',name:'Golden QA',email:'golden@example.test',accepted:true,expectedTotal:q.total,expectedDeposit:q.deposit,requestKey:'golden-booking-qa-1'});assert.equal(r.status,200);const booking=r.data;r=await request('account');assert.ok(r.data.bookings.some(b=>b.id===booking.id));record('Golden booking flows through authoritative quote to saved customer booking');
 r=await request('lead',{name:'Golden QA',email:'golden@example.test',tour,tourName:'Tarifa Golden Tour',url:'http://test.local'+tour,currency:'EUR',displayedPrice:'€57',guests:2,consent:true,type:'tour'},null);assert.equal(r.status,200);const lead=r.data;r=await request('admin',undefined,'test-admin');assert.ok(r.data.leads.some(l=>l.id===lead.id));assert.ok(r.data.emails.length>0);record('Tour enquiry persists into Admin and branded test outbox');
 const catalog=JSON.parse(fs.readFileSync('data/catalog.json','utf8'));for(const p of catalog){const response=await mf.dispatchFetch('http://test.local'+p.path);assert.equal(response.status,200,p.path);const raw=await response.text();const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#x27;');assert.ok(raw.includes('<title>'+esc(p.title)+'</title>'),p.path+' title');assert.ok(raw.includes('href="'+esc(p.canonical[0]||p.url)+'"'),p.path+' canonical');}record('All 72 original routes, titles and canonical URLs remain unchanged');
 fs.writeFileSync('migration/golden-tour-test-results.json',JSON.stringify({passed:evidence.length,checks:evidence},null,2));console.log('TOTAL',evidence.length);
}finally{await mf.dispose()}
