import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const organic='data:text/javascript;base64,'+Buffer.from(ts.transpileModule(readFileSync('lib/organic-core.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64');
const source=ts.transpileModule(readFileSync('lib/marketing-core.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace("'./organic-core'",JSON.stringify(organic));
const {acquisition,touches,isSessionActive,effectiveSEO,canIndex,eventContext,publicPath}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const first=acquisition('https://www.tangierexcursions.com/malaga/?utm_source=google&utm_medium=cpc&utm_campaign=summer&utm_content=hero&utm_term=private-tours','https://google.com/search?q=private');
assert.equal(first.source,'google');assert.equal(first.referrer,'google.com');assert.equal(first.landing_page,'/malaga/');assert.equal(first.term,'private-tours');
const direct=acquisition('https://www.tangierexcursions.com/tangier/','https://www.tangierexcursions.com/malaga/');
let state=touches(null,first);state=touches(state,direct);assert.deepEqual(state.first,first);assert.deepEqual(state.last,first);
const later=acquisition('https://www.tangierexcursions.com/?utm_source=facebook&utm_medium=social','');state=touches(state,later);assert.deepEqual(state.first,first);assert.deepEqual(state.last,later);
assert.equal(acquisition('https://example.test/?utm_source=person%40mail.com','').source,'direct');assert.equal(acquisition('https://example.test/?utm_source=google','',false).source,'direct');
assert.equal(publicPath('/booking-link/secret/'),null);assert.equal(publicPath('/account/'),null);assert.equal(acquisition('https://x.test/checkout/',''),null);
assert.deepEqual(eventContext({passport:'secret',email:'a@b.com',trip_id:'/trip/',party_size:2}),{trip_id:'/trip/',party_size:2});
assert.equal(isSessionActive({last_seen:new Date(10000000).toISOString()},10000001),true);assert.equal(isSessionActive({last_seen:new Date(0).toISOString()},2000000),false);
const base={title:'Default',description:'Summary',canonical:'https://www.tangierexcursions.com/trip/',index:true,sitemap:true,status:'published',openGraph:{image:'/image.jpg'}};
assert.equal(effectiveSEO(base,{title:'Manual'}).title,'Manual');assert.equal(effectiveSEO(base,{title:''}).title,'Default');
assert.equal(canIndex({path:'/trip/',draft:false},base),true);assert.equal(canIndex({path:'/trip/',draft:true},base),false);assert.equal(canIndex({path:'/trip/'},{...base,index:false}),false);assert.equal(canIndex({path:'/other/'},base),false);
console.log('PASS UTM sanitization, first/last touch, session expiry, context allowlist, manual SEO fallback, canonical/draft/sitemap eligibility');
const permSource=ts.transpileModule(readFileSync('lib/admin-permissions.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {canMarketing,canAdminView}=await import('data:text/javascript;base64,'+Buffer.from(permSource).toString('base64'));
assert.equal(canMarketing('admin','manage_tracking'),true);assert.equal(canMarketing('seo','manage_tracking'),false);assert.equal(canMarketing('seo','manage_seo'),true);assert.equal(canMarketing('content','manage_landing_pages'),true);assert.equal(canMarketing('customer','view_analytics'),false);assert.equal(canAdminView('finance','Content Performance'),true);assert.equal(canAdminView('content','Tracking & Attribution'),false);
console.log('PASS scoped Marketing role permissions');
const clientSource=ts.transpileModule(readFileSync('lib/marketing-client.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace("'./marketing-core'",JSON.stringify('data:text/javascript;base64,'+Buffer.from(source).toString('base64')));
const client=await import('data:text/javascript;base64,'+Buffer.from(clientSource).toString('base64'));
const savedFetch=globalThis.fetch;const store=new Map([['te-analytics','yes']]);const sent=[];
globalThis.localStorage={getItem:k=>store.get(k)||null};globalThis.sessionStorage={removeItem:()=>{}};
globalThis.location={pathname:'/',search:'?utm_source=google&email=secret@example.test&utm_term=secret%40example.test',host:'www.tangierexcursions.com'};globalThis.document={referrer:'https://google.com/search?q=private'};
globalThis.fetch=async(url,options)=>{sent.push({url,body:JSON.parse(options.body)});return {ok:true}};
assert.equal(client.analyticsOptIn(),false);client.trackEvent('view_home');assert.equal(sent.length,0);
store.set('te-analytics-version','2');assert.equal(client.analyticsOptIn(),true);client.trackEvent('view_home');await new Promise(resolve=>setImmediate(resolve));assert.equal(sent.length,2);assert.equal(sent[1].body.query,'?utm_source=google');assert.equal(sent[1].body.referrer,'https://google.com');assert.ok(!JSON.stringify(sent).includes('secret'));
store.set('te-analytics','no');client.trackEvent('view_home');await new Promise(resolve=>setImmediate(resolve));assert.equal(sent.length,2);globalThis.fetch=savedFetch;
console.log('PASS renewed consent requirement, no tracking on denial, client-side query/referrer privacy filter');
