import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const code=ts.transpileModule(readFileSync('lib/organic-core.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {canonicalURL,indexState,validateRedirects,parseMigration,landingQuality,similarity,fingerprint,incomingGraph,relationSuggestions,reviewDue}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
assert.equal(canonicalURL('https://tangierexcursions.com/tangier?utm_source=test#x'),'https://www.tangierexcursions.com/tangier/');
assert.throws(()=>canonicalURL('https://evil.test/foo'));
const p={path:'/tangier/'},s={canonical:'https://www.tangierexcursions.com/tangier/',status:'published',index:true,sitemap:true};
assert.equal(indexState(p,s).sitemap,true);
for(const path of ['/admin/','/account/','/api/booking/','/booking-link/abc/','/passengers/','/partners/portal/','/search/'])assert.equal(indexState({path},{...s,canonical:'https://www.tangierexcursions.com'+path}).index,false,path);
assert.equal(indexState({...p,draft:true},s).sitemap,false);assert.equal(indexState(p,{...s,index:false}).sitemap,false);assert.equal(indexState(p,{...s,canonical:'https://www.tangierexcursions.com/other/'}).status,'CANONICALIZED');assert.equal(indexState(p,s,'?sort=price').index,false);assert.equal(indexState(p,s,'?utm_source=test').index,true);
assert.throws(()=>validateRedirects([{source:'/a/',destination:'/a/',type:301}],new Set(['/a/'])));
assert.throws(()=>validateRedirects([{source:'/a/',destination:'/b/',type:301},{source:'/b/',destination:'/a/',type:301}],new Set(['/a/','/b/'])));
assert.throws(()=>validateRedirects([{source:'/a/',destination:'/b/',type:301},{source:'/b/',destination:'/c/',type:301}],new Set(['/c/'])));
assert.throws(()=>validateRedirects([{source:'/a/',destination:'/missing/',type:301}],new Set(['/x/'])));
assert.equal(validateRedirects([{source:'/a/',destination:'/b/',type:301}],new Set(['/b/'])).length,1);
assert.equal(parseMigration('Old URL,New URL,Action,Notes\n/a/,/b/,301 redirect,"reviewed, useful"')[0].notes,'reviewed, useful');
assert.throws(()=>parseMigration('Old URL,New URL,Action,Notes\n/a/,https://evil.test/,301 redirect,x'));
assert.equal(landingQuality({...p,name:'Thin',landing:{}},s).ready,false);
const content=Array.from({length:150},(_,i)=>'fact'+i).join(' ');assert.equal(similarity(fingerprint(content),fingerprint(content)),1);
const graph=incomingGraph([{path:'/',outgoing:['/a/']},{path:'/a/',outgoing:[]},{path:'/b/',outgoing:[]}]);assert.equal(graph[1].orphan,false);assert.equal(graph[2].orphan,true);
assert.equal(relationSuggestions({path:'/a/',taxonomy:[{id:'t'}]},[{path:'/b/',taxonomy:[{id:'t',kind:'destination',name:'Tangier'}]}]).length,1);
assert.equal(reviewDue({type:'knowledge',review:{lastReviewed:'2000-01-01'}}).needsReview,true);
console.log('PASS canonical cleanup, system/search/facet noindex, sitemap eligibility, redirect safety, CSV review parsing, landing quality, duplicate similarity, orphan graph, semantic relationships and freshness');
