import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const wranglerRequire=createRequire(require.resolve('wrangler/package.json'));
const {Miniflare}=wranglerRequire('miniflare');
const root=process.cwd();
const mf=new Miniflare({modules:[{type:'ESModule',path:path.join(root,'dist/server/index.js')},...fs.readdirSync('dist/server',{recursive:true}).filter(x=>x.endsWith('.js')&&x!=='index.js').map(x=>({type:'ESModule',path:path.join(root,'dist/server',x)}))],modulesRoot:path.join(root,'dist/server'),modulesRules:[{type:'ESModule',include:['**/*.js'],fallthrough:true}],compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'test-database'},r2Buckets:{MEDIA:'test-media'},bindings:{ADMIN_USER_IDS:'test-admin'},assets:{directory:path.join(root,'dist/client'),binding:'ASSETS',routerConfig:{has_user_worker:true,invoke_user_worker_ahead_of_assets:true}},cf:false});
const evidence=[];
const record=(name)=>{evidence.push({name,status:'passed'});console.log('PASS',name)};
try{
 const database=await mf.getD1Database('DB');
 for(const filename of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())for(const stmt of fs.readFileSync('drizzle/'+filename,'utf8').split('--> statement-breakpoint').map(x=>x.trim()).filter(Boolean))await database.prepare(stmt).run();
 async function request(op,body,user='test-customer'){const headers={'Content-Type':'application/json',Origin:'http://test.local'};if(user){headers['oai-authenticated-user-id']=user;headers['oai-authenticated-user-email']=user+'@example.test'}const r=await mf.dispatchFetch('http://test.local/api/'+op,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:JSON.stringify(body)})});const raw=await r.text();if(!raw)throw new Error('Empty '+r.status+' response for '+op+' '+JSON.stringify([...r.headers]));const data=JSON.parse(raw);return {status:r.status,data}}
 const tour='/tangier-day-trips/full-day-trip-to-tangier-from-tarifa-spain/';
 const admin='test-admin';
 const rep=(action,body,user=admin)=>request('reputation/'+action,body,user);
 const get=async id=>{const r=await database.prepare('SELECT * FROM records WHERE id=?').bind(id).first();return r?{...r,data:JSON.parse(r.data)}:null};
 async function booking(key,language='en'){const r=await request('booking',{tour,date:'2027-06-15',adults:2,currency:'EUR',name:'Private Customer Name',email:'secret.customer@example.test',pickup:'Private pickup address',accepted:true,language,requestKey:key});assert.equal(r.status,200,JSON.stringify(r));await request('booking-status',{id:r.data.id,status:'completed'},admin);return r.data}
 const first=await booking('reputation-first','fr');let req=await get('review-request:'+first.id);assert.match(req.data.token,/^[a-f0-9]{64}$/);assert.equal(req.data.status,'Scheduled');assert.ok(Date.parse(req.data.dueAt)-Date.parse(req.data.completedAt)>=10*3600000);assert.equal((await rep('run',{})).data.queued,0);record('Completed booking receives an opaque token and a real ten-hour delay');
 assert.equal((await rep('admin',undefined,'test-customer')).status,403);assert.equal((await rep('settings',{},null)).status,403);record('Reputation administration rejects customers and anonymous callers');
 const token=req.data.token;let res=await mf.dispatchFetch('http://test.local/review/'+token+'/');let html=await res.text();assert.equal(res.status,200);assert.ok(html.includes('Comment s'));assert.ok(!html.includes('secret.customer@example.test'));assert.ok(!html.includes('Private pickup address'));assert.ok(!html.includes('Private Customer Name'));assert.ok(!html.includes(first.id));assert.ok(html.includes('noindex'));assert.ok(html.includes('no-referrer'));record('French secure review page is server-rendered without private booking identity or contact data');
 let bad=await rep('submit',{token:'invalid',rating:5,text:'test',publicationConsent:true},null);assert.equal(bad.status,400);assert.equal((await rep('submit',{booking:first.id,rating:5,text:'test',publicationConsent:true},'other-customer')).status,400);record('Invalid tokens and other-customer booking access are rejected');
 let settings=(await rep('admin')).data.settings;settings={...settings,platforms:[{id:'google',url:'https://g.page/r/test-review',enabled:true},{id:'tripadvisor',url:'https://www.tripadvisor.com/UserReviewEdit-test',enabled:true},{id:'trustpilot',url:'https://www.trustpilot.com/review/example.test',enabled:true}]};assert.equal((await rep('settings',settings)).status,200);assert.equal((await rep('admin')).data.settings.platforms.filter(p=>p.enabled).length,3);assert.equal((await rep('settings',{...settings,platforms:[{id:'google',url:'https://evil.test/',enabled:true}]})).status,400);record('Platform settings persist and reject unofficial redirect destinations');
 await database.prepare("UPDATE records SET data=json_set(data,'$.dueAt',?) WHERE id=?").bind(new Date(Date.now()-1000).toISOString(),req.id).run();const queued=await Promise.all([rep('run',{}),rep('run',{})]);assert.equal(queued.reduce((n,r)=>n+r.data.queued,0),1);let mail=await get('review-outbox:'+first.id+':0');assert.equal(mail.data.status,'test-outbox');assert.ok(mail.data.subject.includes('Tanger'));assert.ok(mail.data.html.includes('/review/'+token+'/'));assert.ok(mail.data.html.includes('/review-qr/'+token+'/'));assert.ok(mail.data.html.includes('Rubik,Arial'));assert.ok(!mail.data.html.includes('Private pickup address'));record('Concurrent queue runs create one localized branded test request with secure CTA and QR');
 assert.equal((await rep('request',{booking:first.id,command:'resend'})).status,400);assert.equal((await rep('run',{})).data.queued,0);record('Immediate reminders and manual spam resends are blocked');
 await database.prepare("UPDATE records SET data=json_set(data,'$.dueAt',?,'$.lastQueuedAt',?) WHERE id=?").bind(new Date(Date.now()-1000).toISOString(),new Date(Date.now()-4*86400000).toISOString(),req.id).run();assert.equal((await rep('run',{})).data.queued,1);await database.prepare("UPDATE records SET data=json_set(data,'$.dueAt',?) WHERE id=?").bind(new Date(Date.now()-1000).toISOString(),req.id).run();assert.equal((await rep('run',{})).data.queued,0);record('One delayed reminder is allowed and the maximum is enforced');
 const review={token,rating:2,title:'An honest experience',text:'A real test review with mixed feedback.',displayName:'Sarah M.',country:'Canada',travelerType:'Families'};assert.equal((await rep('submit',review,null)).status,400);assert.equal((await rep('submit',{...review,publicationConsent:true,displayName:'secret@example.test'},null)).status,400);let submitted=await rep('submit',{...review,publicationConsent:true},null);assert.equal(submitted.status,200,JSON.stringify(submitted));assert.equal(submitted.data.platforms.length,3);assert.equal((await get('review-request:'+first.id)).data.workflowComplete,true);assert.equal((await get('review:'+first.id)).data.attention.status,'open');assert.equal((await rep('submit',{...review,publicationConsent:true},null)).status,400);record('Low-rating submission requires consent, prevents duplicate reviews and stops reminders without gating external options');
 assert.equal((await request('reviews',undefined,null)).data.length,0);await rep('visit',{token},null);await rep('visit',{token},null);await rep('external',{token,platform:'google'},null);await rep('external',{token,platform:'google'},null);let workspace=(await rep('admin')).data;assert.equal(workspace.events.filter(e=>e.data.event==='page-visit').length,1);assert.equal(workspace.events.filter(e=>e.data.event==='external-click').length,1);assert.equal(workspace.delivery,null);assert.equal(workspace.opens,null);assert.equal(workspace.reviews.length,1);record('Pending content is private and unique funnel events never fabricate delivery or external publication');
 assert.equal((await rep('moderate',{id:'review:'+first.id,action:'moderate',status:'rejected',reason:'low rating'})).status,400);assert.equal((await rep('moderate',{id:'review:'+first.id,action:'moderate',status:'published'})).status,200);let publicReviews=(await request('reviews',undefined,null)).data;assert.equal(publicReviews[0].rating,2);assert.equal(publicReviews[0].verified,true);assert.ok(!JSON.stringify(publicReviews).includes(first.id));assert.ok(!JSON.stringify(publicReviews).includes('secret.customer'));record('Legitimate criticism can be published; public review payload excludes booking identifiers and private data');
 await rep('moderate',{id:'review:'+first.id,action:'reply',response:'Thank you for your candid feedback.',notify:true});await rep('moderate',{id:'review:'+first.id,action:'attention',assignee:'Operations',notes:'Internal-only issue details',contactAction:'Contact planned; no message sent',resolution:'Resolved in test',resolved:true});const savedReview=await get('review:'+first.id);assert.equal(savedReview.data.attention.status,'resolved');assert.ok(savedReview.data.history.length>=4);publicReviews=(await request('reviews',undefined,null)).data;assert.equal(publicReviews[0].response,'Thank you for your candid feedback.');assert.ok(!JSON.stringify(publicReviews).includes('Internal-only'));record('Public replies and private issue resolution persist with moderation history');
 html=await (await mf.dispatchFetch('http://test.local'+tour)).text();assert.ok(html.includes(review.text));assert.ok(html.includes('Thank you for your candid feedback.'));assert.ok(!html.includes('Internal-only issue details'));record('Published tour reviews and official replies render in the initial server response');
 settings=(await rep('admin')).data.settings;const landing=(await rep('admin')).data.pages.find(p=>p.kind!=='tour'&&p.path!=='/').path;await rep('settings',{...settings,landingTours:{[landing]:[tour]}});html=await (await mf.dispatchFetch('http://test.local'+landing)).text();assert.ok(html.includes(review.text));assert.equal((await rep('admin')).data.reviews.length,1);html=await (await mf.dispatchFetch('http://test.local/tangier-excursions-reviews/')).text();assert.ok(html.includes(review.text));record('Landing-page and existing review-archive social proof use relationships without duplicating review records');
 const opted=await booking('reputation-optout','es');const or=await get('review-request:'+opted.id);assert.equal((await rep('optout',{token:or.data.token},null)).status,200);await database.prepare("UPDATE records SET data=json_set(data,'$.dueAt',?) WHERE id=?").bind(new Date(Date.now()-1000).toISOString(),or.id).run();assert.equal((await rep('run',{})).data.queued,0);assert.equal((await rep('request',{booking:opted.id,command:'resend'})).status,400);assert.equal((await rep('external',{token:or.data.token,platform:'google'},null)).status,200);record('Opt-out persists and blocks automatic/manual requests without blocking independent review choices');
 const photoBooking=await booking('reputation-photos');const pr=await get('review-request:'+photoBooking.id);async function upload(){const form=new FormData();form.set('token',pr.data.token);form.set('file',new File([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aZQAAAABJRU5ErkJggg==','base64')],'qa.png',{type:'image/png'}));const req=new Request('http://test.local/api/review-photo',{method:'POST',body:form});const res=await mf.dispatchFetch(req.url,{method:'POST',headers:{Origin:'http://test.local','Content-Type':req.headers.get('Content-Type')},body:await req.arrayBuffer()});return {status:res.status,data:await res.json()}}
 const photo=await upload();assert.equal(photo.status,200,JSON.stringify(photo));assert.equal((await mf.dispatchFetch('http://test.local'+photo.data.url)).status,404);assert.equal((await mf.dispatchFetch('http://test.local'+photo.data.url+'?token='+pr.data.token)).status,200);assert.equal((await mf.dispatchFetch('http://test.local'+photo.data.url+'?token='+token)).status,404);record('Secure-link photo upload and preview enforce completed-booking ownership');
 await rep('photo-caption',{token:pr.data.token,id:photo.data.id,caption:'The harbor'},null);const photoReview={token:pr.data.token,rating:5,text:'Photo review test.',publicationConsent:true,photos:[photo.data.id]};assert.equal((await rep('submit',photoReview,null)).status,400);assert.equal((await rep('submit',{...photoReview,photoConsent:true},null)).status,200);await rep('moderate',{id:'review:'+photoBooking.id,action:'moderate',status:'published'});assert.equal((await mf.dispatchFetch('http://test.local'+photo.data.url)).status,200);assert.equal((await get(photo.data.id)).data.caption,'The harbor');record('Photos need explicit consent and moderation before public display');
 assert.equal((await rep('remove-photo',{id:photo.data.id,reason:'customer request'})).status,200);assert.equal((await mf.dispatchFetch('http://test.local'+photo.data.url)).status,404);publicReviews=(await request('reviews',undefined,null)).data;assert.ok(publicReviews.every(r=>!r.photos.includes(photo.data.url)));record('Approved photo deletion revokes media access and removes it from public review data');
 assert.equal((await request('booking-status',{id:opted.id,status:'cancelled',reason:'Reviewed exceptional cancellation after completion'},admin)).status,200);assert.equal((await rep('visit',{token:or.data.token},null)).status,400);assert.equal((await mf.dispatchFetch('http://test.local/review-qr/'+or.data.token+'/')).status,404);assert.equal((await mf.dispatchFetch('http://test.local/review-qr/'+token+'/')).status,200);record('Cancelled bookings revoke review link actions and QR generation');
 const en=await mf.dispatchFetch('http://test.local/api/email?name=Review%20request&lang=es',{headers:{'oai-authenticated-user-id':admin,'oai-authenticated-user-email':'admin@example.test'}});assert.ok((await en.text()).includes('Cómo fue'));assert.equal((await request('template',{name:'Review reminder',language:'es',subject:'Tu viaje',body:'Hola {{guest_first_name}}',showDetails:false},admin)).status,200);const es=await mf.dispatchFetch('http://test.local/api/email?name=Review%20reminder&lang=es',{headers:{'oai-authenticated-user-id':admin,'oai-authenticated-user-email':'admin@example.test'}});assert.ok((await es.text()).includes('Tu viaje'));record('Localized review email templates are editable and persist after fresh reads');
 fs.writeFileSync('migration/reputation-engine-test-results.json',JSON.stringify({passed:evidence.length,checks:evidence},null,2));
}finally{await mf.dispose()}
