import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const wranglerRequire=createRequire(require.resolve('wrangler/package.json'));
const {Miniflare}=wranglerRequire('miniflare');
const root=process.cwd();
const mf=new Miniflare({modules:[{type:'ESModule',path:path.join(root,'dist/server/index.js')},...fs.readdirSync('dist/server',{recursive:true}).filter(x=>x.endsWith('.js')&&x!=='index.js').map(x=>({type:'ESModule',path:path.join(root,'dist/server',x)}))],modulesRoot:path.join(root,'dist/server'),modulesRules:[{type:'ESModule',include:['**/*.js'],fallthrough:true}],compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'test-database'},bindings:{ADMIN_USER_IDS:'test-admin'},assets:{directory:path.join(root,'dist/client'),binding:'ASSETS',routerConfig:{has_user_worker:true,invoke_user_worker_ahead_of_assets:true}},cf:false});
const evidence=[];
const record=(name)=>{evidence.push({name,status:'passed'});console.log('PASS',name)};
try{
 const database=await mf.getD1Database('DB');
 for(const filename of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())for(const stmt of fs.readFileSync('drizzle/'+filename,'utf8').split('--> statement-breakpoint').map(x=>x.trim()).filter(Boolean))await database.prepare(stmt).run();
 async function request(op,body,user='test-customer'){const headers={'Content-Type':'application/json',Origin:'http://test.local'};if(user){headers['oai-authenticated-user-id']=user;headers['oai-authenticated-user-email']=user+'@example.test'}const r=await mf.dispatchFetch('http://test.local/api/'+op,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:JSON.stringify(body)})});const raw=await r.text();if(!raw)throw new Error('Empty '+r.status+' response for '+op+' '+JSON.stringify([...r.headers]));const data=JSON.parse(raw);return {status:r.status,data}}
 const tour='/tangier-day-trips/full-day-trip-to-tangier-from-tarifa-spain/';const date='2027-06-15';

 const create=(key,extra={},user='test-customer')=>request('booking',{tour,date,guests:4,currency:'EUR',name:'QA Purchaser',email:'buyer@example.test',accepted:true,requestKey:key,...extra},user);
 let r=await create('unified-direct-01');assert.equal(r.status,200);const direct=r.data;assert.equal(direct.total,34800);assert.equal(direct.bookingType,'DIRECT');record('Direct booking uses canonical record and server pricing');
 r=await request('booking-payment',{id:direct.id,kind:'payment',amount:direct.data.deposit,reason:'QA deposit',requestKey:'deposit-test-01'},'test-admin');assert.equal(r.status,200);assert.equal(r.data.paymentStatus,'deposit-paid');record('Deposit ledger and derived balance');
 await request('booking-payment',{id:direct.id,kind:'payment',amount:direct.data.deposit,reason:'QA deposit',requestKey:'deposit-test-01'},'test-admin');assert.equal((await request('booking-detail?id='+direct.id)).data.payments.length,1);record('Payment idempotency');
 r=await request('partner-save',{name:'Staging luxury hotel in Gibraltar',rate:15,users:['hotel-a'],active:true},'test-admin');assert.equal(r.status,200);const partner=r.data;
 const traveler={name:'Hotel guest',email:'guest@example.test'};let partnerBooking;
 for(const mode of ['guest','partner']){r=await create('partner-mode-'+mode,{bookingType:'PARTNER',partnerId:partner.id,partnerPaymentMode:mode,traveler},'hotel-a');assert.equal(r.status,200);assert.equal(r.data.data.commission,5220);assert.equal(r.data.total,34800);partnerBooking=r.data;record('Partner '+mode+' arrangement shares base price and canonical booking');}
 assert.equal((await request('booking-detail?id='+partnerBooking.id,undefined,'hotel-b')).status,403);assert.equal((await request('bookings',undefined,'hotel-b')).data.bookings.length,0);assert.equal((await request('passengers?booking='+partnerBooking.id,undefined,'hotel-a')).status,403);record('Partner tenant isolation and document privacy');
 r=await create('unified-someone-01',{bookingType:'BOOK_FOR_SOMEONE',traveler});assert.equal(r.status,200);assert.equal(r.data.data.participants[0].name,'QA Purchaser');assert.equal(r.data.data.name,'Hotel guest');record('Purchaser and traveler identities separated');
 r=await create('unified-gift-fixed',{bookingType:'GIFT',traveler});assert.equal(r.status,200);assert.equal(r.data.data.gift.state,'scheduled');record('Fixed-date gift references same canonical table');
 r=await create('unified-gift-flex',{bookingType:'GIFT',traveler,flexible:true,date:''});assert.equal(r.status,200);const gift=r.data;assert.equal(gift.status,'unscheduled');
 r=await request('booking-amend',{id:gift.id,date:'2027-08-10',guests:4,reason:'Recipient selected date'});assert.equal(r.status,200);assert.equal(r.data.id,gift.id);assert.equal(r.data.data.gift.state,'redeemed');record('Flexible gift scheduling updates the original booking');
 r=await create('unified-admin-01',{bookingType:'ADMIN_CREATED'},'test-admin');assert.equal(r.status,200);assert.equal(r.data.bookingType,'ADMIN_CREATED');assert.equal((await create('unauthorized-admin',{bookingType:'ADMIN_CREATED'})).status,403);record('Admin journey and server authorization');
 r=await request('lead',{name:'Custom QA',email:'custom@example.test',start:'Tangier',destinations:'Fes',guests:'4',consent:true},null);assert.equal(r.status,200);const lead=r.data.id;
 r=await create('unified-custom-01',{bookingType:'CUSTOM_TOUR',customTourId:lead},'test-admin');assert.equal(r.status,200);const custom=r.data;assert.equal((await create('unified-custom-02',{bookingType:'CUSTOM_TOUR',customTourId:lead},'test-admin')).data.id,custom.id);record('Custom enquiry conversion is linked and nonduplicating');
 r=await request('booking-payment',{id:direct.id,kind:'refund',amount:1000,reason:'QA partial refund',requestKey:'refund-test-01'},'test-admin');assert.equal(r.status,200);assert.equal(r.data.refunded,1000);assert.equal(r.data.balanceDue,direct.total-direct.data.deposit);record('Partial refund updates payment projection without recreating refunded debt');
 r=await request('booking-status',{id:custom.id,status:'completed'},'test-admin');assert.equal(r.status,200);assert.equal((await request('booking-detail?id='+custom.id,undefined,'test-admin')).data.booking.status,'completed');assert.ok(await database.prepare("SELECT id FROM records WHERE id=? AND kind='review-request'").bind('review-request:'+custom.id).first());record('Shared completion transition schedules review workflow');
 r=await request('cancel',{id:partnerBooking.id,reason:'QA cancellation'},'hotel-a');assert.equal(r.status,200);assert.equal(r.data.commissionAmount,0);record('Cancellation releases capacity and reverses commission projection');
 await request('tour-settings',{path:tour,tiers:[{min:1,max:99,price:100}],capacity:4,blackouts:[]},'test-admin');
 const races=await Promise.all([create('last-slot-direct',{date:'2027-09-10',guests:3}),create('last-slot-partner',{date:'2027-09-10',guests:3,bookingType:'PARTNER',partnerId:partner.id,traveler},'hotel-a')]);assert.equal(races.filter(r=>r.status===200).length,1);record('Public/partner race cannot overbook shared capacity');
 const before=await database.prepare('SELECT COUNT(*) AS n,SUM(total) AS total FROM bookings').first();const all=(await request('bookings',undefined,'test-admin')).data.bookings;assert.equal(all.length,before.n);assert.equal(all.reduce((n,b)=>n+b.total,0),before.total);record('All channel totals reconcile to canonical bookings');
 r=await create('repeat-key-check',{date:'2027-09-11',guests:2});const repeat=await create('repeat-key-check',{date:'2027-09-11',guests:2});assert.equal(r.data.id,repeat.data.id);record('Booking retry returns same reference');

 const legacyData=JSON.stringify({name:'Historic traveler',email:'historic@example.test',notes:'Preserve this note',deposit:1234,payment:'Legacy simulation',extraLegacyField:'keep me'});
 await database.prepare('INSERT INTO bookings(id,owner,tour,date,guests,total,status,token,data,created,request_key) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind('TE-HISTORIC','historic-owner',tour,'2025-01-01',2,12345,'completed','historic-qr',legacyData,'2025-01-01','historic-key').run();
 const legacy=(await request('booking-detail?id=TE-HISTORIC',undefined,'test-admin')).data.booking;assert.equal(legacy.bookingType,'DIRECT');assert.equal(legacy.total,12345);assert.equal(legacy.data.extraLegacyField,'keep me');assert.equal((await database.prepare("SELECT data FROM bookings WHERE id='TE-HISTORIC'").first()).data,legacyData);record('Legacy IDs, amounts and unknown fields remain unchanged');
 const op=await create('operations-change-test',{date:'2027-09-20',guests:2});assert.equal(op.status,200);const opId=op.data.id;
 await database.prepare('INSERT INTO records(id,kind,owner,data,created) VALUES (?,?,?,?,?)').bind('passengers:'+opId,'passengers','test-customer',JSON.stringify({status:'Complete',received:2}),new Date().toISOString()).run();
 await database.prepare('INSERT INTO records(id,kind,owner,data,created) VALUES (?,?,?,?,?)').bind('supplier:'+opId,'supplier-notification','admin',JSON.stringify({reference:opId,status:'test-outbox',date:'2027-09-20',travelers:2}),new Date().toISOString()).run();
 r=await request('booking-amend',{id:opId,date:'2027-09-21',guests:3,reason:'Changed travel party'});assert.equal(r.status,200);const opDetail=(await request('booking-detail?id='+opId)).data;assert.match(opDetail.documents,/review/);const supplier=await database.prepare("SELECT data FROM records WHERE id=?").bind('supplier:'+opId).first();assert.equal(JSON.parse(supplier.data).travelers,3);assert.equal(JSON.parse(supplier.data).status,'change-requires-confirmation');
 await request('cancel',{id:opId,reason:'Test cancelled'});assert.equal((await request('booking-detail?id='+opId)).data.booking.balanceDue,0);assert.equal(JSON.parse((await database.prepare('SELECT data FROM records WHERE id=?').bind('supplier:'+opId).first()).data).status,'cancelled');record('Amendment and cancellation reconcile document/supplier state and balance');

 const documentsHeaders={'oai-authenticated-user-id':'test-customer','oai-authenticated-user-email':'test-customer@example.test'};
 const giftDoc=await mf.dispatchFetch('http://test.local/api/booking-document?id='+gift.id+'&type=gift',{headers:documentsHeaders});assert.equal(giftDoc.status,200);const giftHTML=await giftDoc.text();assert.ok(giftHTML.includes('A journey, just for you'));assert.ok(giftHTML.includes('data:image/png;base64,'));assert.ok(!giftHTML.includes('<dt>Total</dt>'));assert.ok(!giftHTML.includes('<dt>Deposit required</dt>'));record('Gift voucher uses same booking and hides financial rows');
 const deniedDoc=await mf.dispatchFetch('http://test.local/api/booking-document?id='+gift.id+'&type=invoice',{headers:{'oai-authenticated-user-id':'outsider','oai-authenticated-user-email':'outsider@example.test'}});assert.equal(deniedDoc.status,403);record('Document endpoints enforce booking access');
 const originalPartner=await request('partner-save',{...partner,tourRates:{[tour]:12}},'test-admin');assert.equal(originalPartner.status,200);
 const partnerQuote=await request('quote',{tour,date:'2027-10-01',guests:4,bookingType:'PARTNER',partnerId:partner.id},'hotel-a');assert.equal(partnerQuote.status,200);assert.equal(partnerQuote.data.commission,4800);assert.equal(partnerQuote.data.commissionRule,'partner-tour');record('Partner-tour override takes priority over partner commission');

 const payLink=(await request('booking-link-create',{id:direct.id,kind:'payment',purpose:'balance',email:'payer@example.test'})).data;
 assert.match(payLink.token,/^[a-f0-9]{64}$/);assert.equal((await request('booking-link?token='+payLink.token,undefined,'wrong-payer')).status,403);
 const payInfo=(await request('booking-link?token='+payLink.token,undefined,'payer')).data;assert.equal(payInfo.reference,direct.id);assert.equal(payInfo.total,direct.total);assert.equal(payInfo.email,undefined);
 r=await request('booking-link-use',{token:payLink.token,expectedTotal:payInfo.total},'payer');assert.equal(r.status,200);const paymentCount=(await request('booking-detail?id='+direct.id)).data.payments.length;
 assert.equal((await request('booking-link-use',{token:payLink.token,expectedTotal:payInfo.total},'payer')).status,200);assert.equal((await request('booking-detail?id='+direct.id)).data.payments.length,paymentCount);record('Recipient-bound guest payment link pays the same booking once');
 const gift2=(await create('gift-recipient-link',{bookingType:'GIFT',traveler,flexible:true,date:''})).data;
 const giftLink=(await request('booking-link-create',{id:gift2.id,kind:'gift'})).data;
 const giftInfo=(await request('booking-link?token='+giftLink.token,undefined,'guest')).data;assert.equal(giftInfo.total,undefined);assert.equal(giftInfo.name,undefined);
 const countBefore=(await database.prepare('SELECT COUNT(*) AS n FROM bookings').first()).n;
 r=await request('booking-link-use',{token:giftLink.token,date:'2027-10-20'},'guest');assert.equal(r.status,200);assert.equal(r.data.reference,gift2.id);assert.equal((await database.prepare('SELECT COUNT(*) AS n FROM bookings').first()).n,countBefore);
 assert.equal((await request('booking-link-use',{token:giftLink.token,date:'2027-10-21'},'guest')).data.alreadyUsed,true);assert.equal((await request('booking-detail?id='+gift2.id)).data.booking.date,'2027-10-20');record('Secure gift recipient redemption preserves booking identity and hides prices');
 const tokens=(await database.prepare("SELECT data FROM records WHERE kind='booking-link'").all()).results;assert.ok(tokens.every(r=>!r.data.includes(giftLink.token)));await database.prepare("UPDATE records SET data=json_set(data,'$.expires',0) WHERE kind='booking-link'").run();assert.equal((await request('booking-link?token='+giftLink.token,undefined,'guest')).status,403);record('Booking links are hashed at rest and expire');
 await request('partner-save',{...partner,active:false},'test-admin');assert.equal((await request('booking-detail?id='+partnerBooking.id,undefined,'hotel-a')).status,403);assert.equal((await request('account',undefined,'hotel-a')).data.bookings.length,0);record('Revoked partner membership also blocks owner/account access');
 fs.writeFileSync('migration/booking-engine/qa-results.json',JSON.stringify({scope:'isolated staging fixtures, not hosted historical records',tests:evidence,canonicalCount:(await database.prepare('SELECT COUNT(*) AS n FROM bookings').first()).n,canonicalTotal:(await database.prepare('SELECT SUM(total) AS total FROM bookings').first()).total,externalPayments:'not connected'},null,2));
}finally{await mf.dispose()}
