'use client';
import {HomeReviewCarousel} from './home-reviews';
import {DiscoverySearch} from './search-discovery';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowLeft,Compass,Users,Route,Sun,Ship,MapPin,Star,ShieldCheck,Plus,ChevronDown} from 'lucide-react';
import {ResponsivePhoto} from './responsive-photo';
import {discoveryUrl} from '@/lib/discovery-engine';
const icons:any={compass:Compass,users:Users,route:Route,sun:Sun};
const labels:any={story:'Our story',crossing:'The crossing',people:'Our people',values:'Our approach',journeys:'Your journey',reviews:'Guest stories'};
function Photo({photo,hero=false,className=''}:any){return photo?.url?<figure className={'te-photo '+className}><ResponsivePhoto src={photo.url} alt={photo.alt||''} width={900} height={700} sizes={hero?'(max-width:767px) 100vw, 55vw':'(max-width:767px) 100vw, 550px'} loading={hero?'eager':'lazy'} fetchPriority={hero?'high':undefined} style={{objectPosition:photo.x+'% '+photo.y+'%'}}/>{photo.caption&&<figcaption>{photo.caption}</figcaption>}</figure>:null}
function Action({label,url,custom,secondary=false}:any){if(!label||!url)return null;const cls='te-button '+(secondary?'te-button-secondary':'');return url==='custom'?<button className={cls} onClick={custom}>{label}<ArrowRight size={18}/></button>:<a className={cls} href={url}>{label}<ArrowRight size={18}/></a>}
function Prose({html,expand=false}:any){const end=expand?[...String(html||'').matchAll(/<\/p>/gi)][1]:null;const split=end?end.index!+4:0;const remainder=split?html.slice(split):'';return <div className="te-prose"><div dangerouslySetInnerHTML={{__html:split?html.slice(0,split):html}}/>{remainder.replace(/<[^>]*>/g,'').trim()&&<details className="te-read-more"><summary><span className="te-read-label">Read more</span><span className="te-close-label">Show less</span><ChevronDown size={17}/></summary><div dangerouslySetInnerHTML={{__html:remainder}}/></details>}</div>}
export function AboutStory({document:doc,discovery,reviews=[],custom,Carousel}:any){
 const root=useRef<HTMLElement>(null),track=useRef<HTMLDivElement>(null);const [active,setActive]=useState('');
 const sections=doc.sections.filter((s:any)=>s.enabled);const selected=(doc.reviews.mode==='manual'?reviews.filter((r:any)=>doc.reviews.ids.includes(r.id)):reviews).slice(0,doc.reviews.limit);
 const nav=sections.filter((s:any)=>labels[s.type]&&(s.type!=='reviews'||selected.length||doc.reviews.demoWhenEmpty!==false));
 const cats=doc.categoryMode==='manual'?doc.categories.filter((c:any)=>c.visible).map((c:any)=>({...discovery.terms.find((t:any)=>t.id===c.id),override:c})).filter((c:any)=>c.id&&c.count):discovery.terms.filter((t:any)=>t.kind==='type'&&t.visible!==false&&t.count>0).slice(0,6);
 useEffect(()=>{const update=()=>{const targets=Array.from(root.current?.querySelectorAll<HTMLElement>('[data-story-section]')||[]);let id='';for(const el of targets){if(el.getBoundingClientRect().top<=190)id=el.id}setActive(id)};update();window.addEventListener('scroll',update,{passive:true});return()=>window.removeEventListener('scroll',update)},[doc]);
 const scrollReviews=(direction:number)=>{const el=track.current;if(el)el.scrollBy({left:direction*((el.firstElementChild?.getBoundingClientRect().width||320)+20),behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})};
 return <main ref={root} className="about-story te-about">{sections.map((s:any,index:number)=>{
 const copy=<div className="te-copy">{s.eyebrow&&<span className="te-eyebrow">{s.eyebrow}</span>}{s.type==='hero'?<h1>{s.heading}</h1>:<h2>{s.heading}</h2>}<Prose html={s.body} expand={['story','local','people','crossing','private'].includes(s.type)}/><div className="te-actions"><Action label={s.ctaLabel} url={s.ctaUrl} custom={custom}/><Action secondary label={s.secondaryCtaLabel} url={s.secondaryCtaUrl} custom={custom}/></div>{s.type==='hero'&&<div className="te-hero-search"><DiscoverySearch data={discovery} compact onCustom={custom}/></div>}</div>;
 if(s.type==='reviews'&&!selected.length)return doc.reviews.demoWhenEmpty!==false?<section key={s.id} id={s.id} data-story-section className="te-review-fallback"><HomeReviewCarousel Carousel={Carousel}/></section>:null;
 return <div key={s.id} className="te-section-wrap"><section id={s.id} data-story-section={labels[s.type]?true:undefined} className={'te-scene te-'+s.type+' te-tone-'+s.background+(!s.image?.url?' te-no-image':'')}>
 <div className="te-container">
 {s.type==='hero'&&<div className="te-breadcrumb"><a href="/">Home</a><span>/</span><span>About us</span></div>}
 <div className="te-scene-grid">{copy}{(s.image?.url||s.secondaryImage?.url)&&<div className="te-visual"><Photo photo={s.image} hero={s.type==='hero'}/><Photo photo={s.secondaryImage} className="te-secondary"/>{s.type==='hero'&&<span className="te-image-label"><MapPin size={17}/> Tangier, Morocco</span>}</div>}</div>
 {s.type==='crossing'&&<div className="te-route"><span className="te-route-caption">A journey we connect for you</span><ol aria-label="Illustrative Spain to Morocco journey">{doc.route.map((stop:string,i:number)=><li key={i}><span className="te-route-icon">{i===2?<Ship size={23}/>:<MapPin size={21}/>}</span><span>{stop}</span></li>)}</ol></div>}
 {s.type==='values'&&<div className="te-values">{doc.values.filter((v:any)=>v.visible).map((v:any,i:number)=>{const Icon=icons[v.icon]||Compass;return <details key={v.id} open={i===0} name="company-values"><summary><span className="te-value-number">{String(i+1).padStart(2,'0')}</span><Icon size={24}/><h3>{v.title}</h3><Plus className="te-value-plus" size={22}/></summary><p>{v.description}</p></details>})}</div>}
 {s.type==='people'&&doc.team.some((t:any)=>t.visible)&&<div className="te-team"><h3>{doc.teamHeading}</h3><div>{doc.team.filter((t:any)=>t.visible).map((t:any)=><article key={t.id}><Photo photo={t.photo}/><h4>{t.name}</h4><span>{t.role}</span><p>{t.bio}</p>{t.languages&&<small>{t.languages}</small>}{t.speciality&&<p>{t.speciality}</p>}</article>)}</div></div>}
 {s.type==='journeys'&&cats.length>0&&<div className="te-categories">{cats.map((c:any,i:number)=><a key={c.id} href={c.seoUrl||discoveryUrl([c.id])}>{(c.override?.image?.url||c.image)&&<ResponsivePhoto src={c.override?.image?.url||c.image} alt={c.override?.image?.alt||c.name} width={500} height={350} sizes="(max-width:767px) 85vw, 370px" loading="lazy"/>}<span><small>{String(i+1).padStart(2,'0')}</small><strong>{c.override?.label||c.name}</strong><ArrowRight size={21}/></span></a>)}</div>}
 {s.type==='reviews'&&<div className="te-reviews"><div className="te-review-controls"><button aria-label="Previous guest reviews" onClick={()=>scrollReviews(-1)}><ArrowLeft size={19}/></button><button aria-label="Next guest reviews" onClick={()=>scrollReviews(1)}><ArrowRight size={19}/></button></div><div ref={track} tabIndex={0} role="region" aria-label="Guest reviews" className="te-review-track">{selected.map((r:any)=><article key={r.id}><span className="te-stars" aria-label={r.rating+' out of 5 stars'}>{[1,2,3,4,5].map(i=><Star size={16} key={i} fill={i<=r.rating?'currentColor':'none'}/>)}</span><h3>{r.title}</h3><p>{r.text}</p><strong>{r.name}</strong>{r.verified&&<small><ShieldCheck size={14}/>Verified booking</small>}<a href={r.tour}>{r.tourName}</a>{r.photos?.slice(0,2).map((src:string)=><img key={src} src={src+'?size=small'} alt="Photo shared by a guest" width="100" height="75" loading="lazy"/>)}</article>)}</div><a className="te-review-link" href="/tangier-excursions-reviews/">Read more reviews <ArrowRight size={17}/></a></div>}
 </div></section>{s.type==='hero'&&nav.length>0&&<nav className="te-story-nav" aria-label="About Tangier Excursions"><div className="te-container"><span className="te-nav-intro">Get to know us</span><div>{nav.map((item:any)=><a key={item.id} href={'#'+item.id} aria-current={active===item.id?'location':undefined}>{labels[item.type]}</a>)}</div></div></nav>}</div>;
 })}</main>
}
