'use client';
import {useEffect,useState} from 'react';
import {readPreference,writePreference} from '@/lib/browser-preferences';
import {LayoutDashboard,CalendarDays,Compass,Users,Files,Handshake,Route,Wallet,Megaphone,ChartNoAxesCombined,Settings,PanelLeftClose,Menu,Search,Plus,Bell,CircleHelp,ChevronRight,ExternalLink} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Command,CommandInput,CommandList,CommandEmpty,CommandGroup,CommandItem} from '@/components/ui/command';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import {canAdminView} from '@/lib/admin-permissions';
import {adminGroups,screenSlug,screenFromSlug} from '@/lib/admin-navigation';
const icons:any={home:LayoutDashboard,calendar:CalendarDays,compass:Compass,users:Users,files:Files,partners:Handshake,route:Route,wallet:Wallet,marketing:Megaphone,chart:ChartNoAxesCombined,settings:Settings};
export function AdminFrame({view,navigate,user,data,catalog,children}:any){const [collapsed,setCollapsed]=useState(false),[mobile,setMobile]=useState(false),[search,setSearch]=useState(false),[help,setHelp]=useState(false),[notifications,setNotifications]=useState(false);const groups=adminGroups.map(g=>({...g,items:g.items.filter(v=>canAdminView(user.role,v))})).filter(g=>g.items.length);const activeGroup=adminGroups.find(g=>g.items.includes(view))?.label||'Dashboard';const [expanded,setExpanded]=useState('Dashboard');useEffect(()=>{try{setCollapsed(readPreference('te-admin-sidebar')==='collapsed')}catch{};navigate(screenFromSlug(new URLSearchParams(location.search).get('section')||''));const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearch(v=>!v)}};const pop=()=>navigate(screenFromSlug(new URLSearchParams(location.search).get('section')||''));window.addEventListener('keydown',key);window.addEventListener('popstate',pop);return()=>{window.removeEventListener('keydown',key);window.removeEventListener('popstate',pop)}},[]);useEffect(()=>setExpanded(activeGroup),[activeGroup]);
const go=(v:string,extra:any={})=>{if(navigate(v)===false)return;const url=new URL(location.href);url.searchParams.set('section',screenSlug(v));for(const k of ['record','create'])url.searchParams.delete(k);for(const [k,value] of Object.entries(extra))url.searchParams.set(k,String(value));history.pushState({},'',url);window.dispatchEvent(new Event('admin-navigation'));setMobile(false);setSearch(false)};
const nav=<><a className="workspace-brand" href="/" aria-label="Tangier Excursions preview"><Compass size={27}/><span>Tangier Excursions<small>Business workspace</small></span></a><nav aria-label="Administration"><p className="workspace-nav-label">YOUR WORKSPACE</p>{groups.map(g=>{const Icon=icons[g.icon];return <div className="workspace-nav-group" key={g.label}><button className={activeGroup===g.label?'active':''} aria-expanded={expanded===g.label} title={collapsed?g.label:undefined} onClick={()=>{setExpanded(expanded===g.label?'':g.label);if(g.items.length===1)go(g.items[0]);if(collapsed){setCollapsed(false);writePreference('te-admin-sidebar','expanded')}}}><Icon size={19}/><span>{g.label}</span>{g.items.length>1&&<ChevronRight size={15}/>}</button>{expanded===g.label&&g.items.length>1&&<div className="workspace-subnav">{g.items.map(item=><button key={item} aria-current={view===item?'page':undefined} onClick={()=>go(item)}>{item==='Settings'?'Booking & currencies':item==='Homepage offers'?'Gift offer & newsletter':item}</button>)}</div>}</div>})}</nav><div className="workspace-side-bottom"><a href="/" target="_blank" rel="noreferrer"><ExternalLink size={16}/><span>Open website preview</span></a><small>Private development · Test activity</small></div></>;
const pending=(data?.leads||[]).filter((r:any)=>!['closed','replied'].includes(r.data.status)).length;
return <div className={'workspace admin-shell '+(collapsed?'workspace-collapsed':'')}><a className="admin-skip" href="#admin-content">Skip to workspace content</a><aside className="workspace-sidebar">{nav}<button className="workspace-collapse" onClick={()=>{setCollapsed(!collapsed);writePreference('te-admin-sidebar',!collapsed?'collapsed':'expanded')}} aria-label={collapsed?'Expand sidebar':'Collapse sidebar'}><PanelLeftClose size={18}/><span>Collapse sidebar</span></button></aside><Sheet open={mobile} onOpenChange={setMobile}><SheetContent side="left" className="workspace-mobile-nav"><SheetTitle className="sr-only">Administration navigation</SheetTitle><SheetDescription className="sr-only">Choose a business workspace.</SheetDescription>{nav}</SheetContent></Sheet><div className="workspace-body"><header className="workspace-topbar"><button className="workspace-mobile-toggle" aria-label="Open administration menu" onClick={()=>setMobile(true)}><Menu/></button><button className="workspace-search" onClick={()=>setSearch(true)}><Search size={17}/><span>Search your workspace</span><kbd>⌘ K</kbd></button><div className="workspace-tools"><DropdownMenu><DropdownMenuTrigger className="primary"><Plus size={17}/><span>Create</span></DropdownMenuTrigger><DropdownMenuContent>{[['New booking','Bookings'],['New tour','Tours'],['New partner','Partners'],['New page','Pages'],['New blog post','Blog'],['New gift booking','Bookings']].filter(([,target])=>canAdminView(user.role,target)).map(([label,target])=><DropdownMenuItem key={label} onSelect={()=>go(target,{create:label==='New gift booking'?'gift':'1'})}>{label}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu><button title="Notifications" aria-label={`Notifications: ${pending} open enquiries`} onClick={()=>setNotifications(true)}><Bell size={19}/>{pending>0&&<span className="workspace-count">{pending}</span>}</button><button title="Workspace help" aria-label="Workspace help" onClick={()=>setHelp(true)}><CircleHelp size={19}/></button><DropdownMenu><DropdownMenuTrigger className="workspace-avatar" aria-label="User menu">{(user.name||user.email||'A').slice(0,1).toUpperCase()}</DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem disabled>{user.name||user.email} · {user.role}</DropdownMenuItem>{canAdminView(user.role,'Users')&&<DropdownMenuItem onSelect={()=>go('Users')}>Users & permissions</DropdownMenuItem>}<DropdownMenuItem asChild><a href="/signout-with-chatgpt?return_to=/admin/" target="_top">Sign out</a></DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header><main id="admin-content" className="admin-main workspace-main"><div className="workspace-environment"><span>PRIVATE PREVIEW</span> Your WordPress website is separate and remains live.</div><div className="workspace-breadcrumb">Workspace <ChevronRight size={14}/> {activeGroup}{activeGroup!==view&&<><ChevronRight size={14}/>{view}</>}</div>{children}</main></div>
<Dialog open={search} onOpenChange={setSearch}><DialogContent className="workspace-command"><DialogTitle>Search workspace</DialogTitle><DialogDescription>Find a module, tour, page, booking or customer.</DialogDescription><Command><CommandInput placeholder="Search name, email, reference or page…"/><CommandList><CommandEmpty>No matching records. Try a shorter name or reference.</CommandEmpty><CommandGroup heading="Workspaces">{groups.flatMap(g=>g.items).map(v=><CommandItem key={v} onSelect={()=>go(v)}>{v}</CommandItem>)}</CommandGroup><CommandGroup heading="Tours & pages">{catalog.map((p:any)=><CommandItem key={p.path} value={p.name+' '+p.path} onSelect={()=>go(p.kind==='tour'?'Tours':p.kind==='article'?'Blog':'Pages',{record:p.path})}>{p.name}<small>{p.path}</small></CommandItem>)}</CommandGroup><CommandGroup heading="Bookings & guests">{(data?.bookings||[]).map((b:any)=><CommandItem key={b.id} value={[b.id,b.data.name,b.data.email,b.data.phone,b.data.partnerReference].join(' ')} onSelect={()=>go('Bookings',{record:b.id})}>{b.id} · {b.data.name}</CommandItem>)}</CommandGroup></CommandList></Command></DialogContent></Dialog>
<Dialog open={help} onOpenChange={setHelp}><DialogContent className="modal"><DialogTitle>Workspace guide</DialogTitle><DialogDescription>Daily work, without changing the live website.</DialogDescription><dl><dt>Tour content</dt><dd>Open Tours, choose an experience and edit its sections. Recoverable drafts are separate from saved tour content.</dd><dt>Homepage</dt><dd>Use Content → Homepage to manage sections and carousel sources. Tour paragraphs never control homepage layout.</dd><dt>Booking operations</dt><dd>Bookings contains every booking type. Payments and Operations are views of those same records.</dd><dt>Keyboard</dt><dd>⌘ / Ctrl K opens search. ⌘ / Ctrl S saves the active tour draft.</dd></dl></DialogContent></Dialog>
<Dialog open={notifications} onOpenChange={setNotifications}><DialogContent className="modal"><DialogTitle>Needs attention</DialogTitle><DialogDescription>From saved development records.</DialogDescription><button className="outline" onClick={()=>{go('Enquiries');setNotifications(false)}}>{pending} open enquiries</button><button className="outline" onClick={()=>{go('Reviews');setNotifications(false)}}>{(data?.reviews||[]).filter((r:any)=>r.data.status==='pending-review').length} reviews awaiting moderation</button><button className="outline" onClick={()=>{go('Operations');setNotifications(false)}}>Inspect upcoming journeys</button></DialogContent></Dialog></div>}
