'use client';
import {useEffect,useRef,useState} from 'react';
import {Undo2,Redo2,History,Save,Clock,Users,Car,Ship,Languages,MapPin,Info,Compass,Sun,Mountain,Camera,Utensils,Route,Search} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {api} from './site';
import {toast} from 'sonner';
export function useEditorDraft(key:string,value:any,onChange:(v:any)=>void){const [leave,setLeave]=useState<any>(null),[status,setStatus]=useState('Saved'),[remote,setRemote]=useState<any>(null),[revisions,setRevisions]=useState<any[]>([]);const initial=useRef(''),current=useRef(value),undo=useRef<any[]>([]),redo=useRef<any[]>([]),tracked=useRef<any>(null),skip=useRef(false),generation=useRef(0);current.current=value;const serialized=JSON.stringify(value);
useEffect(()=>{generation.current++;initial.current=JSON.stringify(value);tracked.current=value;undo.current=[];redo.current=[];setStatus('Saved');setRemote(null);setRevisions([]);if(key)api('editor-state?key='+encodeURIComponent(key)).then(d=>{setRemote(d.draft);setRevisions(d.revisions)}).catch(e=>toast.error(e.message))},[key]);
useEffect(()=>{if(!key||value===null||initial.current===serialized)return;setStatus('Unsaved changes');const version=generation.current;const t=setTimeout(async()=>{if(!skip.current&&tracked.current){undo.current=[...undo.current.slice(-29),tracked.current];redo.current=[]}skip.current=false;tracked.current=value;setStatus('Saving draft…');try{await api('editor-draft',{key,value});if(generation.current===version&&JSON.stringify(current.current)===serialized){initial.current=serialized;setStatus('Draft saved')}}catch(e:any){if(generation.current===version)setStatus('Draft not saved — retry');toast.error(e.message)}},1000);return()=>clearTimeout(t)},[serialized,key]);
useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(key&&JSON.stringify(current.current)!==initial.current){e.preventDefault();e.returnValue=''}};const shortcut=(e:KeyboardEvent)=>{if(key&&(e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();api('editor-draft',{key,value:current.current}).then(()=>{initial.current=JSON.stringify(current.current);setStatus('Draft saved')}).catch(e=>toast.error(e.message))}};window.addEventListener('beforeunload',before);window.addEventListener('keydown',shortcut);return()=>{window.removeEventListener('beforeunload',before);window.removeEventListener('keydown',shortcut)}},[key]);
useEffect(()=>{const guard=(e:any)=>{if(key&&JSON.stringify(current.current)!==initial.current){e.preventDefault();setLeave(()=>e.detail.proceed)}};window.addEventListener('admin-leave',guard);return()=>window.removeEventListener('admin-leave',guard)},[key]);
return {leave,setLeave,status,remote,revisions,recover:()=>{if(remote){onChange(remote.value);setRemote(null)}},restore:(v:any)=>onChange(structuredClone(v)),undo:()=>{if(undo.current.length){redo.current.push(current.current);skip.current=true;onChange(undo.current.pop())}},redo:()=>{if(redo.current.length){undo.current.push(current.current);skip.current=true;onChange(redo.current.pop())}},canUndo:undo.current.length>0,canRedo:redo.current.length>0,saved:()=>{initial.current=JSON.stringify(current.current);setStatus('Saved');api('editor-state?key='+encodeURIComponent(key)).then(d=>setRevisions(d.revisions)).catch(()=>{})},saveDraft:async()=>{await api('editor-draft',{key,value:current.current});initial.current=JSON.stringify(current.current);setStatus('Draft saved')}}}
export function DraftControls({draft}:any){const [history,setHistory]=useState(false);return <><Dialog open={!!draft.leave} onOpenChange={v=>!v&&draft.setLeave(null)}><DialogContent className="modal"><DialogTitle>Keep your changes?</DialogTitle><DialogDescription>Your latest edits have not been saved. Save a recoverable draft before leaving this editor.</DialogDescription><div className="row"><button className="outline" onClick={()=>draft.setLeave(null)}>Keep editing</button><button className="primary" onClick={async()=>{try{await draft.saveDraft();const go=draft.leave;draft.setLeave(null);go()}catch(e:any){toast.error(e.message)}}}>Save draft & leave</button></div></DialogContent></Dialog><span className="editor-save-status" role="status">{draft.status}</span><button type="button" className="outline" onClick={draft.saveDraft}><Save size={15}/>Save draft</button><button type="button" className="outline" disabled={!draft.canUndo} onClick={draft.undo} aria-label="Undo edit"><Undo2 size={16}/></button><button type="button" className="outline" disabled={!draft.canRedo} onClick={draft.redo} aria-label="Redo edit"><Redo2 size={16}/></button><button type="button" className="outline" onClick={()=>setHistory(true)}><History size={15}/>History</button>{draft.remote&&<button type="button" className="outline" onClick={draft.recover}>Recover draft</button>}<Dialog open={history} onOpenChange={setHistory}><DialogContent className="modal"><DialogTitle>Revision history</DialogTitle><DialogDescription>Restore into the editor, review, then save. Restoring never publishes automatically.</DialogDescription>{draft.revisions.length?draft.revisions.map((r:any)=><div className="booking-row" key={r.id}><div><strong>{r.data.action}</strong><p>{new Date(r.created).toLocaleString()} · {r.owner}</p></div><button className="outline" onClick={()=>{draft.restore(r.data.value);setHistory(false)}}>Restore draft</button></div>):<p>Saved updates will appear here. Original migration data remains preserved.</p>}</DialogContent></Dialog></>}
const iconSet:any={clock:Clock,users:Users,car:Car,ferry:Ship,language:Languages,pin:MapPin,info:Info,compass:Compass,sun:Sun,mountain:Mountain,camera:Camera,utensils:Utensils,route:Route};
export function IconPicker({value,onChange,allowed=Object.keys(iconSet)}:any){const [query,setQuery]=useState('');return <div><label className="field"><span>Find an icon</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Clock, ferry, people…"/></label><div className="icon-picker" role="group" aria-label="Choose icon">{allowed.filter((k:string)=>k.includes(query.toLowerCase())).map((k:string)=>{const Icon=iconSet[k]||Info;return <button type="button" key={k} aria-pressed={value===k} onClick={()=>onChange(k)}><Icon size={18}/>{k}</button>})}</div></div>}
