'use client';
import {useRef,useState} from 'react';
import {ImagePlus,Images,Upload} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export function BannerImagePicker({value,onChange,onBusy=()=>{},title="Gift-banner background",allowedUrls}:{value:string;onChange:(v:string)=>void;onBusy?:(v:boolean)=>void;title?:string;allowedUrls?:string[]}){
 const input=useRef<HTMLInputElement>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[open,setOpen]=useState(false),[items,setItems]=useState<any[]>([]),[query,setQuery]=useState('');
 async function upload(file?:File){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024){setError('Choose a JPG, PNG or WebP image smaller than 8 MB.');return}setBusy(true);onBusy(true);setError('');try{const form=new FormData();form.append('file',file);const r=await fetch('/api/upload',{method:'POST',body:form}),d:any=await r.json();if(!r.ok)throw Error(d.error||'Upload failed. Please try again.');onChange(d.url)}catch(e:any){setError(e.message)}finally{setBusy(false);onBusy(false);if(input.current)input.current.value=''}}
 async function library(){setOpen(true);setError('');try{const r=await fetch('/api/editor-media'),d:any=await r.json();if(!r.ok)throw Error(d.error||'Unable to load images');setItems(d)}catch(e:any){setError(e.message)}}
 return <section className="banner-image-picker"><div className="banner-image-preview">{value?<img src={value} alt="Selected image"/>:<ImagePlus size={32}/>}</div><div><h3>{title}</h3><p>Choose a clear, relevant photograph.</p><input ref={input} type="file" className="sr-only" tabIndex={-1} accept="image/jpeg,image/png,image/webp" aria-label="Upload image" onChange={e=>upload(e.target.files?.[0])}/><div className="row"><button type="button" className="primary" disabled={busy} onClick={()=>input.current?.click()}><Upload size={17}/>{busy?'Uploading…':'Upload image'}</button><button type="button" className="outline" disabled={busy} onClick={library}><Images size={17}/>Choose from library</button></div><small>JPG, PNG or WebP · up to 8 MB. Save your changes to apply the image.</small>{error&&<p role="alert">{error}</p>}</div><Dialog open={open} onOpenChange={setOpen}><DialogContent className="modal banner-media-dialog"><DialogTitle>Choose an image</DialogTitle><DialogDescription>Select an image, then save your changes.</DialogDescription><label className="field"><span>Search images</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Photo name or description"/></label>{error&&<p role="alert">{error}</p>}<div className="banner-library-grid">{items.filter(m=>(!allowedUrls||allowedUrls.includes(m.url)||m.url.startsWith("/media/"))).filter(m=>[m.alt,m.name,m.url].join(' ').toLowerCase().includes(query.toLowerCase())).slice(0,120).map(m=><button type="button" key={m.url} onClick={()=>{onChange(m.url);setOpen(false)}}><img src={m.url} alt={m.alt||m.name||'Banner image'} loading="lazy"/><span>{m.alt||m.name||m.url.split('/').pop()}</span></button>)}</div>{!items.length&&!error&&<p>No images loaded yet. You can upload a background instead.</p>}</DialogContent></Dialog></section>
}
