'use client';
import {OrganicEditorStatus} from './organic-editor-status';
import {useEffect,useState} from 'react';
import {api,Field,Choice} from './site';
import {BannerImagePicker} from './banner-image-picker';
export function ContentVisibility({path}:{path:string}){
 const [seo,setSeo]=useState<any>(null),[facts,setFacts]=useState<any>(null),[image,setImage]=useState(''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let active=true;setSeo(null);setError('');api('content-visibility?path='+encodeURIComponent(path)).then(d=>{if(active){setSeo(d.seo);setFacts(d.presence);setImage(d.image)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[path]);
 const patch=(k:string,v:any)=>{setSeo((s:any)=>({...s,[k]:v}));setMessage('')};
 const factual=(v:any)=>{setFacts((s:any)=>({...s,...v,reviewed:false}));setMessage('')};
 async function save(kind:'seo'|'facts'){setBusy(true);setError('');setMessage('');try{const saved=await api(kind==='seo'?'seo-save':'presence-save',{...(kind==='seo'?seo:facts),path});if(kind==='seo')setSeo(saved);else setFacts(saved);setMessage(kind==='seo'?'Search and social settings saved.':'Traveler answers and sources saved.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(!seo||!facts)return <section className="visibility-editor"><h2>Search & AI visibility</h2><p role={error?'alert':'status'}>{error||'Loading visibility settings…'}</p></section>;
 return <section className="visibility-editor"><header><span className="status">SEO · AEO · GEO</span><h2>Help travelers discover this content</h2><p>Write useful search previews, answer real questions and cite reliable sources. Settings save separately from your content.</p></header><p className="notice">This private preview remains noindex. Search settings are prepared for launch; publishing them here does not make the preview searchable.</p>
 <OrganicEditorStatus path={path}/><details open><summary>Search appearance</summary><div className="admin-editor-grid"><div><Field label="SEO title" value={seo.title} maxLength={300} onChange={(e:any)=>patch('title',e.target.value)}/><small>{seo.title.length} characters · aim for a clear, specific title</small><label className="field"><span>Meta description</span><textarea value={seo.description} maxLength={500} onChange={e=>patch('description',e.target.value)}/></label><small>{seo.description.length} characters · search engines may choose a different excerpt</small><Field label="Focus search phrase (editorial guidance)" value={seo.primaryKeyword} onChange={(e:any)=>patch('primaryKeyword',e.target.value)}/></div><div className="visibility-preview"><small>Search preview · illustrative</small><p>{seo.canonical}</p><h3>{seo.title||'Your page title'}</h3><p>{seo.description||'Describe what makes this page useful to travelers.'}</p>{image&&<img src={image} alt="Saved featured image"/>}</div></div></details>
 <details><summary>Social sharing image & text</summary><p>Use a dedicated social image, or leave the override empty to use the saved featured image. X uses these values when its separate overrides are empty.</p><Field label="Social title" value={seo.openGraph.title} onChange={(e:any)=>patch('openGraph',{...seo.openGraph,title:e.target.value})}/><Field label="Social description" value={seo.openGraph.description} onChange={(e:any)=>patch('openGraph',{...seo.openGraph,description:e.target.value})}/><BannerImagePicker title="Social sharing image" value={seo.openGraph.image||image} onBusy={setUploading} onChange={v=>patch('openGraph',{...seo.openGraph,image:v})}/><button type="button" className="text-btn" onClick={()=>{patch('openGraph',{...seo.openGraph,image:''});patch('twitter',{...seo.twitter,image:''})}}>Use featured image for sharing</button></details>
 <details><summary>Advanced SEO & indexing</summary><Field label="Canonical URL" value={seo.canonical} onChange={(e:any)=>patch('canonical',e.target.value)}/>{[['index','Allow indexing after launch'],['follow','Allow following links after launch'],['sitemap','Include in sitemap after launch'],['confirmProtected','I reviewed any canonical or indexing changes']].map(([k,l])=><label className="check-row" key={k}><input type="checkbox" checked={!!seo[k]} onChange={e=>patch(k,e.target.checked)}/>{l}</label>)}<Choice label="Image preview permission" value={seo.maxImagePreview} onChange={v=>patch('maxImagePreview',v)} items={['none','standard','large'].map(v=>({value:v,label:v}))}/><p className="fine">Existing structured data is preserved unless changed in the dedicated SEO workspace. Only factual, page-visible information belongs in schema.</p></details>
 <div className="editor-actions"><Choice label="SEO workflow" value={seo.status} onChange={v=>patch('status',v)} items={[{value:'draft',label:'Draft — not applied'},{value:'review',label:'Needs review — not applied'},{value:'published',label:'Apply to preview'}]}/><button type="button" className="primary" disabled={busy||uploading} onClick={()=>save('seo')}>{busy?'Saving…':'Save search & social settings'}</button></div>
 <details><summary>Traveler answers & trusted sources · AEO / GEO</summary><p>These reviewed answers appear on the page for travelers and search systems. Add specific, accurate information; avoid duplicating existing FAQs.</p><label className="field"><span>Concise factual summary</span><textarea maxLength={2000} value={facts.summary} onChange={e=>factual({summary:e.target.value})}/></label>{facts.questions.map((q:any,i:number)=><div className="presence-answer" key={i}><Field label={'Traveler question '+(i+1)} value={q.question} maxLength={200} onChange={(e:any)=>factual({questions:facts.questions.map((v:any,n:number)=>n===i?{...v,question:e.target.value}:v)})}/><label className="field"><span>Direct, factual answer</span><textarea maxLength={2000} value={q.answer} onChange={e=>factual({questions:facts.questions.map((v:any,n:number)=>n===i?{...v,answer:e.target.value}:v)})}/></label><button type="button" className="text-btn" onClick={()=>factual({questions:facts.questions.filter((_:any,n:number)=>n!==i)})}>Remove question</button></div>)}<button type="button" className="outline" disabled={facts.questions.length>=12} onClick={()=>factual({questions:[...facts.questions,{question:'',answer:''}]})}>Add traveler question</button><h3>Sources supporting these facts</h3>{facts.sources.map((s:any,i:number)=><div className="presence-answer" key={i}>{['label','url'].map(k=><Field key={k} label={k==='label'?'Source name':'HTTPS source URL'} value={s[k]} onChange={(e:any)=>factual({sources:facts.sources.map((v:any,n:number)=>n===i?{...v,[k]:e.target.value}:v)})}/>)}<button type="button" className="text-btn" onClick={()=>factual({sources:facts.sources.filter((_:any,n:number)=>n!==i)})}>Remove source</button></div>)}<button type="button" className="outline" disabled={facts.sources.length>=12} onClick={()=>factual({sources:[...facts.sources,{label:'',url:''}]})}>Add source</button><Field label="Facts checked by" value={facts.reviewer} onChange={(e:any)=>factual({reviewer:e.target.value})}/><label className="check-row"><input type="checkbox" checked={facts.reviewed} onChange={e=>setFacts({...facts,reviewed:e.target.checked})}/>I checked these facts and want them visible on the page</label><button type="button" className="primary" disabled={busy} onClick={()=>save('facts')}>Save answers & sources</button></details>{message&&<p role="status">{message}</p>}{error&&<p role="alert">{error}</p>}</section>
}
