'use client';
import {useRef,useState} from 'react';
import {ArrowRight,ArrowLeft,Check,Compass,Users,Minus,Plus,MapPin} from 'lucide-react';
import {api,Field} from './site';
import {DateField,localDate} from './date-field';

const stages=['Your journey','Your preferences','Your details'];
export function CustomTourForm({origin='Tangier',tour,currency}:any){
 const [step,setStep]=useState(0),[busy,setBusy]=useState(false),[done,setDone]=useState(''),[consent,setConsent]=useState(false),[flexible,setFlexible]=useState(false),[error,setError]=useState(''),[interests,setInterests]=useState<string[]>([]);
 const scroll=useRef<HTMLDivElement>(null),heading=useRef<HTMLHeadingElement>(null),errorBox=useRef<HTMLParagraphElement>(null);
 const [data,setData]=useState<any>({tour:tour?.path||'',tourName:tour?.name||'',url:tour?.path||'',currency,start:origin,destinations:tour?.product?.destination||'',date:'',guests:2,duration:'',interests:'',accommodation:'',notes:'',name:'',email:'',phone:''});
 const patch=(key:string,v:any)=>{setData((d:any)=>({...d,[key]:v}));setError('')};
 const field=(key:string,label:string,props:any={})=><Field label={label} value={data[key]} onChange={(e:any)=>patch(key,e.target.value)} {...props}/>;
 const advance=(next:number)=>{setStep(next);setError('');scroll.current?.scrollTo({top:0});requestAnimationFrame(()=>heading.current?.focus())};
 const validateStep=(stage:number)=>{if(stage===0){if(!data.start.trim())return 'Enter your starting city.';if(!data.destinations.trim())return 'Tell us where you would like to go.';if(!flexible&&!data.date)return 'Choose a travel date, or select “My dates are flexible”.';if(!flexible&&data.date<localDate(new Date()))return 'Choose today or a future date.';if(!Number.isInteger(data.guests)||data.guests<1||data.guests>99)return 'Choose between 1 and 99 travelers.'}if(stage===1){if(!data.duration)return 'Choose how much time you have, or select “Help me decide”.';if(!interests.length)return 'Choose at least one experience you would enjoy.';if(!data.accommodation)return 'Choose an accommodation option, including “No accommodation needed” if appropriate.'}if(stage===2){if(!data.name.trim())return 'Enter your name.';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email.trim()))return 'Enter a valid email address.';if(!consent)return 'Please agree that we may contact you about this request.'}return ''};
 const showError=(message:string,stage=step)=>{setStep(stage);setError(message);requestAnimationFrame(()=>{scroll.current?.scrollTo({top:0});errorBox.current?.focus()})};
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const message=validateStep(step);if(message){showError(message);return}if(step<2){advance(step+1);return}for(const stage of [0,1]){const missing=validateStep(stage);if(missing){showError(missing,stage);return}}setBusy(true);setError('');try{const r=await api('lead',{...data,name:data.name.trim(),email:data.email.trim(),date:flexible?'':data.date,dateFlexible:flexible,interests:[...interests,data.interests].filter(Boolean).join(', '),consent});setDone(r.id)}catch(e:any){showError(e.message)}finally{setBusy(false)}}

 if(done)return <div className="custom-success" role="status"><span><Check size={30}/></span><h3>Your journey request is saved</h3><p>Reference: {done}</p><p>This is a test enquiry. Our preview dashboard now contains your request.</p></div>;
 return <form className="custom-planner" noValidate onSubmit={submit}><ol className="custom-progress" aria-label="Request progress">{stages.map((title,i)=><li key={title} aria-current={step===i?'step':undefined} className={i<step?'complete':''}><span>{i<step?<Check size={14}/>:i+1}</span><small>{title}</small></li>)}</ol><div className="custom-planner-scroll" ref={scroll}>{error&&<p ref={errorBox} tabIndex={-1} className="custom-error" role="alert">{error}</p>}<div className="custom-stage-heading"><span className="eyebrow">LET’S MAKE IT YOURS</span><h3 ref={heading} tabIndex={-1}>{['Where shall we take you?','What does your ideal trip look like?','Let’s put a plan together.'][step]}</h3><p>{['Start with the essentials. We’ll help with the details.','Choose a duration, at least one interest and an accommodation option.','Check your journey and tell us how to reach you.'][step]}</p></div>
 {step===0&&<><div className="form-grid">{field('start','Starting city *',{required:true,autoComplete:'address-level2',placeholder:'Your pickup city'})}{field('destinations','Where would you like to go? *',{required:true,placeholder:'Tangier, Chefchaouen, Fes…'})}</div><DateField calendarPresentation="dialog" required={!flexible} label="Travel date" placeholder={flexible?'Flexible dates':'Choose your travel date'} value={data.date} min={localDate(new Date())} disabled={flexible} onChange={(e:any)=>patch('date',e.target.value)}/><label className="custom-flexible"><input type="checkbox" checked={flexible} onChange={e=>{setFlexible(e.target.checked);setError('')}}/>My dates are flexible</label><div className="custom-travelers"><div><strong><Users size={19}/>Who’s coming?</strong><small>Total travelers in your group</small></div><div className="stepper"><button type="button" aria-label="Remove traveler" disabled={data.guests<=1} onClick={()=>patch('guests',data.guests-1)}><Minus size={17}/></button><span aria-live="polite">{data.guests}</span><button type="button" aria-label="Add traveler" disabled={data.guests>=99} onClick={()=>patch('guests',data.guests+1)}><Plus size={17}/></button></div></div></>}
 {step===1&&<><fieldset className="custom-options"><legend>How much time do you have? *</legend><div className="custom-choice-grid">{['1 day','2–3 days','4–7 days','8+ days','Help me decide'].map(v=><button type="button" key={v} aria-pressed={data.duration===v} onClick={()=>patch('duration',v)}>{v}</button>)}</div></fieldset><fieldset className="custom-options"><legend>What would you love to experience? * <small>Choose at least one</small></legend><div className="custom-choice-grid">{['Culture & history','Food & markets','Coast & nature','Desert','Photography','Family time'].map(v=><button type="button" key={v} aria-pressed={interests.includes(v)} onClick={()=>{setInterests(prev=>prev.includes(v)?prev.filter(x=>x!==v):[...prev,v]);setError('')}}>{interests.includes(v)&&<Check size={14}/>} {v}</button>)}</div></fieldset>{field('interests','Other interests (optional)',{placeholder:'Anything special you have in mind?'})}<label className="field"><span>Accommodation *</span><select required value={data.accommodation} onChange={e=>patch('accommodation',e.target.value)}><option value="" disabled>Choose an option</option>{['No accommodation needed','Comfortable riad or hotel','Luxury riad or hotel','Help me choose'].map(v=><option key={v}>{v}</option>)}</select></label><label className="field"><span>Anything else we should know? (optional)</span><textarea rows={3} value={data.notes} onChange={e=>patch('notes',e.target.value)} placeholder="A celebration, accessibility needs or a special request…"/></label></>}
 {step===2&&<><div className="custom-summary"><span><Compass size={20}/>Your journey</span><strong>{data.start}{data.destinations?' → '+data.destinations:''}</strong><p>{flexible?'Flexible dates':new Date(data.date+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})} · {data.guests} travelers · {data.duration}</p><button type="button" onClick={()=>advance(0)}>Edit journey</button></div>{field('name','Your name *',{required:true,autoComplete:'name',placeholder:'Full name'})}{field('email','Email address *',{type:'email',required:true,autoComplete:'email',placeholder:'you@example.com'})}{field('phone','Phone or WhatsApp (optional)',{type:'tel',autoComplete:'tel',placeholder:'Include country code'})}<label className="custom-consent"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/>You may contact me about this tour request.</label><p className="fine">Submitting a request does not make a booking or take a payment.</p></>}
 </div><div className="custom-planner-actions">{step>0?<button type="button" className="outline" disabled={busy} onClick={()=>advance(step-1)}><ArrowLeft size={17}/>Back</button>:<span>Step 1 of 3</span>}<button type="submit" className="primary" disabled={busy}>{busy?'Sending…':step===2?'Send test enquiry':'Continue'}<ArrowRight size={17}/></button></div></form>
}
