'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,Mail,ShieldCheck,ChevronLeft,Compass} from 'lucide-react';
import {InputOTP,InputOTPGroup,InputOTPSlot} from '@/components/ui/input-otp';
import {safeReturn} from '@/lib/customer-auth-core';
async function request(action:string,body?:any){const response=await fetch('/api/customer-auth/'+action,{...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(20000)});const data:any=await response.json();if(!response.ok)throw Error(data.error||'Please try again.');return data}
export async function signOutCustomer(user:any,all=false){if(user?.id?.startsWith('customer:')){await request('logout',{all});location.href='/login/'}else{await fetch('/api/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});location.assign('/signout-with-chatgpt?return_to=/login/')}}
export function CustomerLogin({compact=false,signup=false,returnTo}: {compact?:boolean,signup?:boolean,returnTo?:string}){
 const [status,setStatus]=useState<any>(null),[email,setEmail]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[seconds,setSeconds]=useState(0),[next,setNext]=useState('/account/');
 useEffect(()=>{request('status').then(setStatus).catch(()=>setError('We couldn’t load sign-in options. Please refresh and try again.'));const q=new URLSearchParams(location.search);setNext(safeReturn((returnTo?returnTo+(location.pathname.replace(/\/$/,'')===returnTo.replace(/\/$/,'')?location.search:''):null)||q.get('next')||((location.pathname==='/login/'||location.pathname==='/signup/')?'/account/':location.pathname+location.search)));if(q.has('error'))setError('Sign-in was cancelled or expired. Please try again.')},[returnTo]);
 useEffect(()=>{if(seconds<=0)return;const timer=setTimeout(()=>setSeconds(seconds-1),1000);return()=>clearTimeout(timer)},[seconds]);
 async function send(){setBusy('email');setError('');try{await request('send',{email});setSent(true);setCode('');setSeconds(60)}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function social(provider:string){setBusy(provider);setError('');try{const data=await request('oauth',{provider,next});location.assign(data.url)}catch(e:any){setError(e.message);setBusy('')}}
 const partner=next.startsWith('/partners/');
 const content=<div className="customer-login-form"><span className="customer-kicker"><Compass size={16}/> {partner?'YOUR PARTNER WORKSPACE':'YOUR MOROCCO, YOUR WAY'}</span><h1>{sent?'Check your inbox':signup?'Your next journey starts here':partner?'Welcome, partner':'Welcome back'}</h1><p className="customer-intro">{sent?<>Enter the verification code sent to <strong>{email}</strong>.</>:partner?<>Sign in to manage your guests, bookings and team.<br/>Use the email associated with your partner account.</>:<>Your bookings, saved experiences and travel details.<br/>All in one place.</>}</p>
 {!status&&!error&&<p role="status">Loading sign-in options…</p>}
 {status?.preview&&<p className="customer-launch-note">Our new customer accounts open at launch. You can preview the sign-in options below.</p>}
 {!sent?<><div className="customer-social"><button disabled={!status?.google||!!busy} onClick={()=>social('google')}><span className="provider-google" aria-hidden="true">G</span>{busy==='google'?'Connecting…':'Continue with Google'}<ArrowRight size={17}/></button><button disabled={!status?.facebook||!!busy} onClick={()=>social('facebook')}><span className="provider-facebook" aria-hidden="true">f</span>{busy==='facebook'?'Connecting…':'Continue with Facebook'}<ArrowRight size={17}/></button></div><div className="customer-divider"><span>or use your email</span></div><form onSubmit={e=>{e.preventDefault();send()}}><label className="field"><span>Email address</span><input type="email" autoComplete="email" required maxLength={254} placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)} disabled={!!busy}/></label><button className="primary customer-submit" disabled={!status?.email||!!busy}><Mail size={18}/>{busy==='email'?'Sending your code…':'Continue with email'}<ArrowRight size={18}/></button><p className="customer-assurance"><ShieldCheck size={16}/> We’ll email a one-time code. No password to remember.</p></form></>:<form onSubmit={async e=>{e.preventDefault();setBusy('verify');setError('');try{const data=await request('verify',{email,code,next});location.assign(data.next)}catch(e:any){setError(e.message);setBusy('')}}}><label className="customer-code-label" htmlFor="customer-code">Verification code</label><InputOTP id="customer-code" maxLength={6} value={code} onChange={setCode} autoComplete="one-time-code" inputMode="numeric" disabled={!!busy}><InputOTPGroup>{[0,1,2,3,4,5].map(i=><InputOTPSlot key={i} index={i}/>)}</InputOTPGroup></InputOTP><button className="primary customer-submit" disabled={code.length!==6||!!busy}>{busy==='verify'?'Verifying…':'Verify & continue'}<ArrowRight size={18}/></button><div className="customer-resend"><button type="button" className="text-btn" disabled={!!busy||seconds>0} onClick={send}>{seconds>0?`Resend code in ${seconds}s`:'Resend code'}</button><button type="button" className="text-btn" disabled={!!busy} onClick={()=>{setSent(false);setCode('');setError('')}}>Change email</button></div><p className="customer-assurance">Can’t find it? Check your spam folder. Codes can only be used once.</p></form>}
 {error&&<p className="customer-error" role="alert">{error}</p>}
 {!sent&&<p className="customer-privacy">{signup?'Already have an account?':'New to Tangier Excursions?'} <a href={(signup?'/login/':'/signup/')+'?next='+encodeURIComponent(next)}>{signup?'Sign in':'Create your account'}</a><br/>Your email is used for your account and bookings. Signing in does not subscribe you to marketing.</p>}
 {status?.preview&&<a className="customer-preview-access" href={'/signin-with-chatgpt?return_to='+encodeURIComponent(next)} target="_top">Continue to preview account <ArrowRight size={15}/></a>}
 </div>;
 return compact?<div className="customer-login-compact">{content}</div>:<section className="customer-login-page"><div className="customer-login-visual"><img src="/assets/customer-login-morocco.jpg" alt="A Moroccan coastal journey"/><div><span>TANGIER EXCURSIONS</span><h2>A warm welcome.<br/>A world to discover.</h2><p>Private journeys between southern Spain and Morocco, brought together by local people.</p></div></div><div className="customer-login-panel"><a className="customer-back" href="/"><ChevronLeft size={16}/> Back to exploring</a>{content}</div></section>
}
