'use client';
import {useEffect,useRef,useState} from 'react';
import {Plus,Minus,LocateFixed,MapPin} from 'lucide-react';
const providers:Record<string,{tile:(z:number,x:number,y:number)=>string;attribution:string;link:string}>={openstreetmap:{tile:(z,x,y)=>`https://tile.openstreetmap.org/${z}/${x}/${y}.png`,attribution:'© OpenStreetMap contributors',link:'https://www.openstreetmap.org/copyright'}};
const project=(lat:number,lng:number,z:number)=>{const scale=256*2**z;const sin=Math.sin(lat*Math.PI/180);return {x:(lng+180)/360*scale,y:(.5-Math.log((1+sin)/(1-sin))/(4*Math.PI))*scale}};
export default function GoldenRouteMap({stops,active,onSelect,settings}:any){const points=stops.filter((s:any)=>Number.isFinite(s.lat)&&Number.isFinite(s.lng)).sort((a:any,b:any)=>a.mapOrder-b.mapOrder);const ref=useRef<HTMLDivElement>(null);const [width,setWidth]=useState(650),[zoom,setZoom]=useState(settings.zoom||10),[loaded,setLoaded]=useState(false),[failed,setFailed]=useState(false),[offset,setOffset]=useState({x:0,y:0});const drag=useRef<any>(null);const provider=providers[settings.provider];const height=350;useEffect(()=>{if(!ref.current||!provider)return;const obs=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){setLoaded(true);obs.disconnect()}},{rootMargin:'150px'});obs.observe(ref.current);return()=>obs.disconnect()},[provider]);useEffect(()=>{if(!ref.current)return;const el=ref.current;const resize=new ResizeObserver(()=>setWidth(el.clientWidth));resize.observe(el);return()=>resize.disconnect()},[]);
const pointKey=points.map((p:any)=>p.id+':'+p.lat+':'+p.lng).join('|');const lastActive=useRef(active);function fitZoom(){let z=settings.zoom||10;while(z>3){const ps=points.map((p:any)=>project(p.lat,p.lng,z));if(Math.max(...ps.map((p:any)=>p.x))-Math.min(...ps.map((p:any)=>p.x))<width-100&&Math.max(...ps.map((p:any)=>p.y))-Math.min(...ps.map((p:any)=>p.y))<height-90)break;z--}return z}useEffect(()=>{if(points.length){setZoom(fitZoom());setOffset({x:0,y:0})}},[pointKey,width,settings.zoom]);useEffect(()=>{if(lastActive.current===active)return;lastActive.current=active;const chosen=points.find((p:any)=>p.id===active);if(!chosen)return;const ps=points.map((p:any)=>project(p.lat,p.lng,zoom)),target=project(chosen.lat,chosen.lng,zoom);setOffset({x:(Math.min(...ps.map((p:any)=>p.x))+Math.max(...ps.map((p:any)=>p.x)))/2-target.x,y:(Math.min(...ps.map((p:any)=>p.y))+Math.max(...ps.map((p:any)=>p.y)))/2-target.y})},[active,pointKey,zoom]);if(!points.length)return <p>Route locations are being reviewed.</p>;const projected=points.map((s:any)=>({...project(s.lat,s.lng,zoom),stop:s}));const center={x:(Math.min(...projected.map((p:any)=>p.x))+Math.max(...projected.map((p:any)=>p.x)))/2,y:(Math.min(...projected.map((p:any)=>p.y))+Math.max(...projected.map((p:any)=>p.y)))/2};const left=center.x-width/2-offset.x,top=center.y-height/2-offset.y;const tiles=[];if(provider&&loaded)for(let x=Math.floor(left/256);x<=Math.floor((left+width)/256);x++)for(let y=Math.floor(top/256);y<=Math.floor((top+height)/256);y++)tiles.push({x,y});const chosen=points.find((s:any)=>s.id===active)||points[0];const progress=points.findIndex((s:any)=>s.id===active);return <div className="golden-route"><div className={'route-canvas '+(settings.animate?'route-animate':'')} ref={ref} role="group" aria-label="Interactive itinerary route map" onPointerDown={e=>{if((e.target as HTMLElement).closest('button,a'))return;drag.current={x:e.clientX,y:e.clientY,offset};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag.current)setOffset({x:drag.current.offset.x+e.clientX-drag.current.x,y:drag.current.offset.y+e.clientY-drag.current.y})}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
{tiles.map(t=><img key={`${zoom}-${t.x}-${t.y}`} className="map-tile" src={provider.tile(zoom,t.x,t.y)} alt="" width={256} height={256} draggable={false} style={{left:t.x*256-left,top:t.y*256-top}} onError={()=>setFailed(true)}/>)}
{settings.connectRoute!==false&&<svg className="route-lines" width={width} height={height} aria-hidden="true"><polyline points={projected.map((p:any)=>`${p.x-left},${p.y-top}`).join(' ')} fill="none" stroke="#8499b7" strokeWidth="3" strokeDasharray="5 7"/><polyline points={projected.slice(0,progress+1).map((p:any)=>`${p.x-left},${p.y-top}`).join(' ')} fill="none" stroke="#335ed2" strokeWidth="4"/></svg>}
{projected.map((p:any,i:number)=><button key={p.stop.id} className={'route-marker '+(p.stop.id===active?'selected':'')} style={{left:p.x-left,top:p.y-top,marginLeft:i===points.length-1?18:0}} onClick={()=>onSelect(p.stop.id)} aria-label={`${i+1}. ${p.stop.location}`} aria-pressed={p.stop.id===active}>{i+1}<span className="route-place-label">{p.stop.location}</span></button>)}
<div className="map-controls"><button aria-label="Zoom in" disabled={zoom>=15} onClick={()=>setZoom(zoom+1)}><Plus size={18}/></button><button aria-label="Zoom out" disabled={zoom<=3} onClick={()=>setZoom(zoom-1)}><Minus size={18}/></button><button aria-label="Reset route view" onClick={()=>{setOffset({x:0,y:0});setZoom(fitZoom())}}><LocateFixed size={18}/></button></div>
{provider&&!loaded&&<button className="map-load" onClick={()=>setLoaded(true)}>Load street map</button>}{provider&&loaded&&<a className="map-attribution" href={provider.link} target="_blank" rel="noreferrer">{provider.attribution}</a>}
</div>{failed&&<p className="fine" role="status">Street tiles could not load. The itinerary points and route remain available.</p>}<div className="route-stop-selector" aria-label="Route stops">{points.map((s:any,i:number)=><button key={s.id} className={s.id===active?'active':''} aria-pressed={s.id===active} onClick={()=>{onSelect(s.id);const p=project(s.lat,s.lng,zoom);setOffset({x:center.x-p.x,y:center.y-p.y})}}>{i+1}. {s.location}</button>)}</div><div className="map-selected" aria-live="polite">{chosen.image&&<img src={chosen.image} alt={chosen.location} loading="lazy"/>}<div><span><MapPin size={16}/>{chosen.location}</span><h3>{chosen.title}</h3><p>{chosen.description[0]?.text}</p>{(!chosen.coordinateSource||chosen.sourceStopId)&&<a href={'#journey-'+(chosen.sourceStopId||chosen.id)}>View itinerary stop →</a>}</div></div><p className="fine">{settings.connectRoute===false&&"Named locations from the tour content. Exact stops and sequence await review. "}Illustrative itinerary route with approximate locations. Lines connect stops and do not represent road or ferry navigation. This is not live GPS tracking. City coordinates: <a href="https://www.geonames.org/" target="_blank" rel="noreferrer">GeoNames (CC BY 4.0)</a>.</p></div>}
