'use client';
import {Star,Quote,MapPin} from 'lucide-react';

const examples=[
 {title:'A day that felt entirely ours',text:'From the crossing to the winding medina streets, this sample story shows how a guest’s favourite moments will appear here.',route:'Tarifa → Tangier',name:'Sample guest A'},
 {title:'Little details, lasting memories',text:'A relaxed pace, time to explore and a warm welcome. This is demonstration copy for the new guest-story carousel.',route:'Spain → Morocco',name:'Sample guest B'},
 {title:'More than a place on the map',text:'Colourful lanes and a journey shared together. Real, approved guest feedback will replace this illustrative story.',route:'Tangier → Chefchaouen',name:'Sample guest C'},
 {title:'Room for a little discovery',text:'An example of a longer journey’s review, with space for the moments that made the experience personal.',route:'Private Morocco journey',name:'Sample guest D'},
];
export function HomeReviewCarousel({Carousel}:any){return <section className="section home-review-stories" aria-labelledby="home-review-title"><div className="section-heading"><div><span className="eyebrow">STORIES FROM OUR GUESTS</span><h2 id="home-review-title">Good journeys stay with you.</h2></div><span className="review-demo-label">Design preview · sample reviews</span></div><p className="review-demo-note">Illustrative reviews and stars—not verified customer feedback.</p><Carousel label="Demo guest stories">{examples.map((r,i)=><article className="home-story-card" key={r.name}><div className="home-story-top"><span className="home-story-stars" aria-label="Illustrative 5 out of 5 stars">{Array.from({length:5},(_,n)=><Star key={n} size={17} fill="currentColor"/>)}</span><Quote size={27} aria-hidden="true"/></div><h3>{r.title}</h3><p>{r.text}</p><div className="home-story-route"><MapPin size={15}/>{r.route}</div><footer><span className="home-story-avatar" aria-hidden="true">{String(i+1).padStart(2,'0')}</span><div><strong>{r.name}</strong><small>Demo review · not a real booking</small></div></footer></article>)}</Carousel><a className="text-btn" href="/tangier-excursions-reviews/">Read our existing guest stories →</a></section>}
