'use client';
import {useState} from 'react';
import {Gift,ArrowRight,Mail} from 'lucide-react';
import {homeMarketingDefaults} from '@/lib/home-marketing';
import {api,Field} from './site';
import {BannerImagePicker} from './banner-image-picker';
export function GiftBanner({settings}:any){const s={...homeMarketingDefaults,...settings};if(!s.enabled)return null;return <section className="home-gift-banner" aria-labelledby="gift-banner-title"><img src={s.image} alt="" loading="lazy" style={{objectPosition:s.position}}/><div className="home-gift-shade"/><div className="home-gift-copy"><span className="home-gift-label"><Gift size={18}/>{s.eyebrow}</span><h2 id="gift-banner-title">{s.heading}</h2><p>{s.body}</p><a className="primary gold" href={s.url}>{s.cta}<ArrowRight size={18}/></a></div><span className="gift-ribbon" aria-hidden="true"><Gift size={30}/></span></section>}
export function HomeNewsletter({settings}:any){const s={...homeMarketingDefaults,...settings};const [busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState('');if(!s.newsletterEnabled)return null;return <section className="home-newsletter"><div className="home-newsletter-inner"><div><span className="home-newsletter-label"><Mail size={17}/>LET’S KEEP IN TOUCH</span><h2>{s.newsletterHeading}</h2><p>{s.newsletterBody}</p></div>{done?<p role="status">You’re on the list. Thank you for joining us!</p>:<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await api('newsletter-subscribe',{email:f.get('email'),consent:f.get('consent')==='on',website:f.get('website'),source:'/'});setDone(true)}catch(e:any){setError(e.message)}finally{setBusy(false)}}}><label className="sr-only" htmlFor="home-newsletter-email">Email address</label><div className="home-newsletter-input"><input id="home-newsletter-email" name="email" type="email" autoComplete="email" placeholder="Your email address" maxLength={254} required/><button disabled={busy}>{busy?'Joining…':'Join us'}<ArrowRight size={18}/></button></div><div className="hub-honeypot" aria-hidden="true"><input name="website" tabIndex={-1} autoComplete="off"/></div><label className="home-newsletter-consent"><input name="consent" type="checkbox" required/>I agree to receive travel emails. I can ask to be removed at any time.</label>{error&&<p role="alert">{error}</p>}</form>}</div></section>}
export function HomeMarketingAdmin({cfg,setCfg}:any){const [s,setS]=useState({...homeMarketingDefaults,...cfg.homeMarketing}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const update=(k:string,v:any)=>setS({...s,[k]:v});return <div className="admin-surface"><h2>Homepage · gifts & newsletter</h2><p>Choose a background from Media library or upload a new image. Changes apply to the homepage after saving.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{const saved=await api('home-marketing-save',s);setCfg({...cfg,homeMarketing:saved});setMessage('Saved. Your homepage has been updated.')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}}><label className="check-row"><input type="checkbox" checked={s.enabled} onChange={e=>update('enabled',e.target.checked)}/>Show gift banner</label><div className="form-grid">{[['eyebrow','Offer label'],['heading','Heading'],['body','Supporting text'],['cta','Button text'],['url','Button destination']].map(([k,l])=><Field key={k} label={l} required value={(s as any)[k]} onChange={(e:any)=>update(k,e.target.value)}/>)}</div><BannerImagePicker value={s.image} onChange={v=>update('image',v)} onBusy={setBusy}/><label className="field"><span>Image focal point</span><select value={s.position} onChange={e=>update('position',e.target.value)}>{['center','left','right','top','bottom'].map(x=><option key={x}>{x}</option>)}</select></label><label className="check-row"><input type="checkbox" checked={s.newsletterEnabled} onChange={e=>update('newsletterEnabled',e.target.checked)}/>Show newsletter</label>{[['newsletterHeading','Newsletter heading'],['newsletterBody','Newsletter text']].map(([k,l])=><Field key={k} label={l} required value={(s as any)[k]} onChange={(e:any)=>update(k,e.target.value)}/>)}<button className="primary" disabled={busy}>{busy?'Saving…':'Save homepage offer'}</button><p role="status">{message}</p></form><h3>Banner preview</h3><GiftBanner settings={s}/><p>Subscribers remain available in About Us → newsletter subscribers.</p></div>}
