'use client';
import {DraftControls,useEditorDraft} from './admin-editing';
import {useState,useEffect} from 'react';
import {api} from './site';
import {toast} from 'sonner';
export function HubWorkspace({mode,catalog}:any){const [data,setData]=useState<any>(null),[edit,setEdit]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[q,setQ]=useState('');const draft=useEditorDraft(edit?.kind==='faq'?'faq:'+(edit.id||'new'):'',edit,setEdit);async function load(){try{setData(await api('hub-admin'))}catch(e:any){setError(e.message)}}useEffect(()=>{setEdit(null);load()},[mode]);async function save(v:any){setBusy(true);try{await api(mode==='Enquiries'?'hub-enquiry':'hub-save',v);toast.success('Saved. Changes persist after refresh.');setEdit(null);await load()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}if(error)return <p role="alert">{error}</p>;if(!data)return <p>Loading content workspace…</p>;
 const field=(key:string,label:string,large=false,type='text')=><label className="field" key={key}><span>{label}</span>{large?<textarea value={edit[key]||''} onChange={e=>setEdit({...edit,[key]:e.target.value})}/>:<input type={type} value={edit[key]??''} onChange={e=>setEdit({...edit,[key]:e.target.value})}/>}</label>;
 const choices=(key:string,title:string,list:any[])=><fieldset><legend>{title}</legend><div className="hub-admin-choices">{list.map(p=><label key={p.path}><input type="checkbox" checked={(edit[key]||[]).includes(p.path)} onChange={e=>setEdit({...edit,[key]:e.target.checked?[...(edit[key]||[]),p.path]:(edit[key]||[]).filter((x:string)=>x!==p.path)})}/>{p.name}</label>)}</div></fieldset>;
 return <div className="admin-surface hub-editor"><h2>{mode==='Destinations'?'Destination pages & hierarchy':mode}</h2>{mode==='Destinations'&&<p>These records extend the existing destination and starting-location taxonomy below. Existing landing-page URLs take priority. SEO metadata is managed in SEO & AI Visibility after publication.</p>}{!edit&&mode!=='About imagery'&&<input aria-label="Search records" placeholder="Search…" value={q} onChange={e=>setQ(e.target.value)}/>}
 {mode==='Help Center'&&!edit&&<><p>Published tour FAQs are reused here with their source tour. New answers remain drafts until reviewed. Reuse answers by selecting related pages or tours.</p><button className="primary" onClick={()=>setEdit({kind:'faq',question:'',shortAnswer:'',answer:'',category:'Travel planning',published:false,relatedTours:[],relatedPages:[],order:data.faqs.length})}>Add question</button>{data.faqs.filter((f:any)=>(f.question+f.category).toLowerCase().includes(q.toLowerCase())).map((f:any)=><div className="hub-admin-row" key={f.id}><div><strong>{f.question}</strong><small>{f.category} · {f.published?'Published':'Draft'} · {f.source}</small></div><button className="outline" onClick={()=>setEdit({...f,kind:'faq'})}>Edit</button></div>)}</>}
 {mode==='Destinations'&&!edit&&data.discovery.terms.filter((t:any)=>['destination','origin'].includes(t.kind)&&t.name.toLowerCase().includes(q.toLowerCase())).map((t:any)=><div className="hub-admin-row" key={t.id}><div><strong>{t.name}</strong><small>{t.country} · {t.count} tours · {t.seoUrl|| (data.settings['destination:'+t.id]?.published?'Destination page published':'Internal discovery record')}</small></div><button className="outline" onClick={()=>setEdit({kind:'destination',id:t.id,slug:t.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/-$/,''),country:t.country,region:'',published:false,relatedBlog:[],...(data.settings['destination:'+t.id]||{})})}>Edit page</button></div>)}
 {mode==='About imagery'&&!edit&&<><p>Replaceable editorial images only. Original About Us text and SEO remain unchanged.</p><button className="primary" onClick={()=>setEdit({kind:'about',images:data.settings.about?.images||[]})}>Manage images</button></>}
 {mode==='Enquiries'&&!edit&&data.enquiries.filter((r:any)=>JSON.stringify(r.data).toLowerCase().includes(q.toLowerCase())).map((r:any)=><div className="hub-admin-row" key={r.id}><div><strong>{r.data.name} · {r.data.category||r.data.type}</strong><small>{r.id} · {r.data.status} · {r.created}</small></div><button className="outline" onClick={()=>setEdit({id:r.id,...r.data})}>Open</button></div>)}
 {edit&&<form onSubmit={e=>{e.preventDefault();save(edit)}}>{edit.kind==='faq'&&<><div className="editor-actions"><DraftControls draft={draft}/></div>{field('question','Question')}{field('shortAnswer','Short direct answer',true)}{field('answer','Supporting detail',true)}<div className="admin-editor-grid">{field('category','Category')}{field('keywords','Search keywords')}{field('order','Display order',false,'number')}{field('reviewed','Last reviewed date',false,'date')}</div>{choices('relatedTours','Reuse on these tours',catalog.filter((p:any)=>p.kind==='tour'))}{choices('relatedPages','Reuse on destination / journal pages',catalog.filter((p:any)=>p.kind!=='tour'))}</>}
 {edit.kind==='destination'&&<><div className="admin-editor-grid">{field('slug','New destination slug (published URLs protected)')}{field('country','Country')}{field('region','Region')}{field('lat','Latitude',false,'number')}{field('lng','Longitude',false,'number')}</div>{field('longDescription','Destination introduction',true)}<label className="field"><span>Gallery · permanent media paths, one per line</span><textarea value={(edit.gallery||[]).join('\n')} onChange={e=>setEdit({...edit,gallery:e.target.value.split('\n').filter(Boolean)})}/></label>{field('highlights','Local highlights',true)}{field('tips','Practical travel information',true)}<label className="field"><span>Curated badge (editorial designation, not a measured metric)</span><select value={edit.badge||''} onChange={e=>setEdit({...edit,badge:e.target.value})}>{['','Featured','New','Popular','Top Destination'].map(x=><option key={x}>{x}</option>)}</select></label>{choices('relatedBlog','Related travel articles',catalog.filter((p:any)=>p.kind==='article'))}<p>Use the taxonomy editor below for featured image, tour assignments, visibility and display order.</p></>}
 {edit.kind==='about'&&<>{edit.images.map((im:any,i:number)=><div className="hub-admin-row" key={i}><img src={im.url} alt={im.alt} width="100"/><label className="field"><span>Alt text</span><input value={im.alt} onChange={e=>setEdit({...edit,images:edit.images.map((x:any,j:number)=>j===i?{...x,alt:e.target.value}:x)})}/></label><span>Replaceable demo image</span><button type="button" onClick={()=>setEdit({...edit,images:edit.images.filter((_:any,j:number)=>j!==i)})}>Remove</button></div>)}<label className="field"><span>Choose existing destination photography</span><select value="" onChange={e=>{if(e.target.value)setEdit({...edit,images:[...edit.images,{url:e.target.value,alt:catalog.find((p:any)=>p.image===e.target.value)?.name||'Morocco travel scene',demo:true}]})}}><option value="">Choose image…</option>{catalog.filter((p:any)=>p.image).map((p:any)=><option key={p.path} value={p.image}>{p.name}</option>)}</select></label><label className="field"><span>Upload replacement photo</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{const form=new FormData();form.set('file',f);const res=await fetch('/api/upload',{method:'POST',body:form});const r:any=await res.json();if(!res.ok)throw Error(r.error);setEdit({...edit,images:[...edit.images,{url:r.url,alt:f.name,demo:true}]})}catch(err:any){toast.error(err.message)}}}/></label></>}
 {mode==='Enquiries'&&<><h3>{edit.name}</h3><p>{edit.email} · {edit.phone}</p><dl className="hub-enquiry-details">{['category','source','reference','date','guests','pickup','destinations','language','subject','message','notes'].filter(k=>edit[k]).map(k=><div key={k}><dt>{k}</dt><dd>{edit[k]}</dd></div>)}</dl><label className="field"><span>Status</span><select value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}>{['new','in-progress','replied','closed'].map(x=><option key={x}>{x}</option>)}</select></label>{field('assigned','Assigned administrator')}{field('internalNotes','Private staff notes',true)}</>}
 {['faq','destination'].includes(edit.kind)&&<label className="check-row"><input type="checkbox" checked={!!edit.published} onChange={e=>setEdit({...edit,published:e.target.checked})}/>Reviewed and published in preview</label>}<div className="row"><button className="primary" disabled={busy}>{busy?'Saving…':'Save'}</button><button className="outline" type="button" onClick={()=>setEdit(null)}>Back</button></div></form>}</div>
}
