import type { Metadata } from 'next';
import './globals.css';
import './marketing.css';
import './partner.css';
import './rubik.css';
import './refinement.css';
import './precision.css';
import './golden.css';
import './golden-refinement.css';
import './reputation.css';
import './experience-system.css';
import './home-refinement.css';
import './mobile-navigation.css';
import './hero-background.css';
import './hero-copy.css';
import './seo-platform.css';
import './home-stories.css';
import './travel-hub.css';
import './about-story.css';
import './about-modern.css';
import './booking-refinement.css';
import './modal-stability.css';
import './home-marketing.css';
import './gift-cards.css';
import './admin-design.css';
import './visual-editor.css';
import './admin-experience.css';
import './login-settings.css';
import './customer-account.css';
import './destination-cards.css';
import './experience-refresh.css';
import './footer-finish.css';
import ModalViewport from './modal-viewport';
export const metadata:Metadata={title:'Tangier Excursions — Development',robots:{index:false,follow:false},icons:{icon:'/assets/brand/icon.png'}};
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="en"><head><link rel="preload" href="/assets/rubik-0.woff" as="font" type="font/woff" crossOrigin="anonymous"/></head><body><ModalViewport/>{children}</body></html>}
