'use client';
import {useState,useEffect,useId} from 'react';
import {Clock,Plus,X} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {pickupLabel,validatePickupTimes} from '@/lib/pickup-times';
import {api} from './site';
import {toast} from 'sonner';
export function PickupTimeSelect({times,value,onChange}:any){const id=useId();if(!times?.length)return null;return <div className="pickup-time-field"><label htmlFor={id}><Clock size={18}/>Pickup time</label><Select value={times.includes(value)?value:''} onValueChange={onChange}><SelectTrigger id={id} className="pickup-time-trigger"><SelectValue placeholder="Choose a pickup time"/></SelectTrigger><SelectContent position="popper" className="pickup-time-options">{times.map((t:string)=><SelectItem key={t} value={t}>{pickupLabel(t)}</SelectItem>)}</SelectContent></Select><small>Local time at your pickup location.</small></div>}
export function PickupTimesEditor({path,onSaved}:any){const [times,setTimes]=useState<string[]>([]),[time,setTime]=useState('09:00'),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{let active=true;setReady(false);api('tour?path='+encodeURIComponent(path)).then(c=>{if(active){setTimes(c.pickupTimes||[]);setReady(true)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[path]);return <section className="pickup-times-editor"><h3><Clock size={19}/>Bookable pickup times</h3><p>Choose the times guests can select in the travel-date popup. Leave the list empty when pickup is arranged after booking.</p><div className="pickup-time-add"><label className="field"><span>New pickup time</span><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><button type="button" className="outline" disabled={!ready||!time||busy} onClick={()=>{try{setTimes(validatePickupTimes([...times,time]));setError('')}catch(e:any){setError(e.message)}}}><Plus size={16}/>Add time</button></div><div className="pickup-time-chips">{times.map(t=><button type="button" className="outline" key={t} disabled={busy} aria-label={'Remove '+pickupLabel(t)} onClick={()=>setTimes(times.filter(x=>x!==t))}>{pickupLabel(t)}<X size={14}/></button>)}</div>{ready&&!times.length&&<p className="fine">No fixed times. Pickup will be arranged separately.</p>}{error&&<p role="alert" className="error">{error}</p>}<button type="button" className="primary" disabled={!ready||busy} onClick={async()=>{setBusy(true);try{const current=await api('tour?path='+encodeURIComponent(path));const next={...current,path,pickupTimes:validatePickupTimes(times)};await api('tour-settings',next);onSaved(next);setError('');toast.success('Pickup times saved')}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>{busy?'Saving…':'Save pickup times'}</button></section>}
