'use client';
import {trackEvent} from '@/lib/marketing-client';
import {PickupTimeSelect} from './pickup-times';
import {pickupLabel} from '@/lib/pickup-times';
import {priceQuote} from '@/lib/pricing';
import {TourEnquiry as Enquiry} from './tour-enquiry';
import {trackDiscovery,analyticsContext} from './search-discovery';
"use client";
import {useEffect,useState,useRef} from 'react';
import {Minus,Plus,ShieldCheck,ArrowRight,Check,Users,CalendarDays,LoaderCircle,MessageCircle,Sparkles} from 'lucide-react';
import {Calendar} from '@/components/ui/calendar';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {api,Field,Money} from './site';
import {toast} from 'sonner';
const dateString=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const steps=['Date','Travelers','Options','Summary'];
export default function Reservation({page,cfg,currency,user,signin,onBooked,onCustom,lang='en'}:any){
const [config,setConfig]=useState<any>(null),[availability,setAvailability]=useState<Record<string,number>>({}),[loaded,setLoaded]=useState(false),[retry,setRetry]=useState(0),[cart,setCart]=useState<any>({date:'',pickupTime:'',adults:2,children:0,infants:0,extras:[],coupon:''}),[ready,setReady]=useState(false),[modal,setModal]=useState(''),[step,setStep]=useState(0),[quote,setQuote]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[accepted,setAccepted]=useState(false),[details,setDetails]=useState<any>({name:user?.name||'',email:user?.email||'',phone:'',pickup:'',notes:'',bookingType:'DIRECT',traveler:{name:'',email:''}});
const [liveQuote,setLiveQuote]=useState<any>(null),[liveBusy,setLiveBusy]=useState(false);
const key=useRef('');const storage='te-booking:'+page.path;const signature=JSON.stringify({...cart,currency});const quoted=useRef('');const guests=cart.adults+cart.children+cart.infants;
useEffect(()=>{let active=true;setLoaded(false);setError('');Promise.all([api('tour?path='+encodeURIComponent(page.path)),api('availability?path='+encodeURIComponent(page.path))]).then(([c,a])=>{if(active){setConfig(c);setAvailability(a);setLoaded(true)}}).catch(e=>{if(active)setError(e.message)});try{const saved=JSON.parse(sessionStorage.getItem(storage)||'null');if(saved&&typeof saved.date==='string'&&['adults','children','infants'].every(k=>Number.isInteger(saved[k])&&saved[k]>=0)&&saved.adults>=1&&saved.adults+saved.children+(saved.infants||0)<=99&&Array.isArray(saved.extras))setCart({...saved,children:saved.children+(Number.isInteger(saved.infants)?saved.infants:0),infants:0,date:saved.date>=dateString(new Date())?saved.date:''})}catch{}setReady(true);return()=>{active=false}},[page.path,retry]);
useEffect(()=>{if(ready)try{sessionStorage.setItem(storage,JSON.stringify(cart))}catch{}setQuote(null);setAccepted(false);key.current=''},[signature,ready]);
useEffect(()=>{if(!loaded||!cart.date||modal!=='booking'||step<1||step>2)return;let valid=true;setLiveBusy(true);const timer=setTimeout(()=>api('quote',{tour:page.path,...cart,currency}).then(q=>{if(valid){setLiveQuote(q);setError('')}}).catch(e=>{if(valid){setLiveQuote(null);setError(e.message)}}).finally(()=>{if(valid)setLiveBusy(false)}),250);return()=>{valid=false;clearTimeout(timer)}},[signature,loaded,modal,step]);
useEffect(()=>{if(user)setDetails((d:any)=>({...d,name:d.name||user.name,email:d.email||user.email}))},[user]);
const money=(v:number)=><Money amount={v/100} currency={currency} config={cfg}/>;const fromTier=config?.tiers?.length?[...config.tiers].sort((a:any,b:any)=>a.price-b.price)[0]:null;const from=fromTier?.price??null;const fromBasis=fromTier?.basis||config?.mode||'person';
let travelerPrices:any=null;try{if(config&&cart.date)travelerPrices=priceQuote(config,cart)}catch{}
const timeRequired=!!config?.pickupTimes?.length;const timeValid=!timeRequired||config.pickupTimes.includes(cart.pickupTime);
const update=(patch:any)=>{if(patch.date)trackEvent('select_date',{trip_id:page.path});if(patch.adults!==undefined||patch.children!==undefined)trackEvent('select_travelers',{trip_id:page.path,party_size:(patch.adults??cart.adults)+(patch.children??cart.children)});if(patch.extras?.length>cart.extras.length)trackEvent('add_extra',{trip_id:page.path});setCart((c:any)=>({...c,...patch}));setError('')};
const open=()=>{trackDiscovery('availability',{tour:page.path});setError('');setStep(0);setModal('booking');if(!loaded)setRetry(n=>n+1)};
async function check(){setBusy(true);setError('');try{const q=await api('quote',{tour:page.path,...cart,currency});quoted.current=signature;setQuote(q);setStep(3)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
const enquiry=()=>{trackDiscovery('enquiry-click',{tour:page.path});setError('');setModal('enquiry')};
useEffect(()=>{if(loaded&&modal==='booking'&&(!config.tiers?.length||['enquiry','custom'].includes(config.bookingMode)))setModal('enquiry')},[loaded,modal,config]);
const bookable=loaded&&from!==null&&!['enquiry','custom'].includes(config?.bookingMode)&&config?.status!=='archived';
return <><aside className="booking-panel compact-booking"><small>FROM</small><div className="booking-price">{from!==null?<><strong><Money amount={from} currency={currency} config={cfg}/></strong><span> / {fromBasis==='person'?'person':fromBasis==='fixed'?'booking':'group'}</span></>:<strong>{loaded?'On request':'Loading…'}</strong>}</div>{bookable&&<><button className="booking-date-choice" onClick={open}><span className="booking-date-icon"><CalendarDays size={21}/></span><span><small>YOUR JOURNEY STARTS HERE</small><strong>{cart.date||'Choose your date'}</strong></span><ArrowRight size={18}/></button><p className="booking-flow-hint">Choose a date, then add your travelers.</p></>}<button className="primary full" onClick={!loaded||bookable?open:enquiry}>{!loaded||bookable?'Check availability':'Enquire about this tour'}<ArrowRight size={17}/></button>{bookable&&<button className="outline full" onClick={enquiry}>{page.product?.golden?'Ask about this trip':'Enquire about this tour'}</button>}<ul className="booking-assurances"><li><Check size={15}/>{page.product?.experienceType==='shared'?'Shared experience':'Private experience'}</li><li><ShieldCheck size={15}/>Secure test checkout</li><li><Check size={15}/>Cancellation according to tour policy</li></ul>{!loaded&&error&&<p className="error" role="alert">{error}</p>}</aside>
<div className="mobile-book mobile-book-refined" hidden={!!modal}><div className="mobile-book-main"><span>{from!==null?<>From <strong><Money amount={from} currency={currency} config={cfg}/></strong></>:'Experience on request'}</span><button className="primary" onClick={!loaded||bookable?open:enquiry}>{!loaded||bookable?'Check availability':'Enquire'}<ArrowRight size={16}/></button></div><div className="mobile-book-help"><button onClick={enquiry}><MessageCircle size={15}/>Ask about this trip</button>{onCustom&&<button onClick={onCustom}><Sparkles size={15}/>Customize trip</button>}</div></div>
<Dialog open={!!modal} onOpenChange={v=>{if(!v&&!busy)setModal('')}}><DialogContent className={'modal booking-modal '+(modal==='enquiry'?'tour-enquiry-modal ':'')+(step===0&&modal==='booking'?'calendar-modal':'')}><DialogTitle>{modal==='enquiry'?'Enquire about this tour':modal==='checkout'?'Complete your test booking':['Choose your travel date','Who’s coming along?','Make it your journey','Your price summary'][step]}</DialogTitle><DialogDescription>{page.name}</DialogDescription>
{modal==='booking'&&!loaded&&<div className="booking-loading" role="status">{error?<><p>We couldn’t load availability. Please try again.</p><button className="primary" onClick={()=>setRetry(n=>n+1)}>Retry availability</button></>:<><LoaderCircle className="loading-icon"/>Loading available dates…</>}</div>}
{modal==='booking'&&loaded&&<><ol className="booking-steps" aria-label="Booking progress">{steps.map((s,i)=><li key={s} aria-current={step===i?'step':undefined}><span>{i===0?<CalendarDays size={15}/>:i===1?<Users size={15}/>:i+1}</span>{s}</li>)}</ol>
<div className="booking-scroll">{step===0&&<><Calendar mode="single" selected={cart.date?new Date(cart.date+'T12:00:00'):undefined} onSelect={d=>d&&update({date:dateString(d)})} disabled={d=>dateString(d)<dateString(new Date())||[...(cfg.blackouts||[]),...(config.blackouts||[])].includes(dateString(d))||(availability[dateString(d)]||0)+1>config.capacity||config.availableDays?.length>0&&!config.availableDays.includes(d.getDay())} defaultMonth={cart.date?new Date(cart.date+'T12:00:00'):new Date()}/>{!timeRequired&&<p className="fine">Pickup time will be confirmed by our team.</p>}<PickupTimeSelect times={config.pickupTimes} value={cart.pickupTime} onChange={(pickupTime:string)=>update({pickupTime})}/><p className="fine">Dates with space for at least one traveler are shown. Your full party’s availability is checked with your price quote.</p></>}
{step===1&&<><p className="fine">Rates below reflect your selected date and party size. Extras and discounts appear in the total.</p>{(['adults','children'] as const).map(k=><div className="traveler-row" key={k}><span><strong><Users size={17} aria-hidden="true"/>{k[0].toUpperCase()+k.slice(1)}</strong><small>{k==='adults'?'18+ years':'Under 18 years'}</small><small className="traveler-unit-price">{travelerPrices?(travelerPrices.mode==='person'?<>{money(k==='adults'?travelerPrices.adultUnit:travelerPrices.childUnit)} / {k==='adults'?'adult':'child'}</>:<>Included in {money(travelerPrices.baseTotal)} group price</>):'Price unavailable for this party size'}</small></span><div className="stepper"><button aria-label={'Remove '+k} disabled={cart[k]<=(k==='adults'?1:0)} onClick={()=>update({[k]:cart[k]-1})}><Minus size={17}/></button><span aria-live="polite">{cart[k]}</span><button aria-label={'Add '+k} disabled={guests>=99} onClick={()=>update({[k]:cart[k]+1})}><Plus size={17}/></button></div></div>)}</>}
{step===2&&<>{config.extras?.length?config.extras.map((x:any)=><label className="check-row" key={x.id}><Checkbox checked={x.required||cart.extras.includes(x.id)} disabled={x.required} onCheckedChange={v=>update({extras:v?[...cart.extras,x.id]:cart.extras.filter((id:string)=>id!==x.id)})}/><span>{x.name} · {money(x.price*100)} / {x.mode==='person'?'person':'group'}{x.required?' (required)':''}</span></label>):<div className="notice">No optional extras are configured for this experience.</div>}<Field label="Promotional code (optional)" value={cart.coupon} onChange={(e:any)=>update({coupon:e.target.value.toUpperCase()})}/></>}
{step===3&&quote&&<div className="quote-summary"><strong>{cart.date}{cart.pickupTime?' · '+pickupLabel(cart.pickupTime):''} · {guests} travelers</strong>{quote.breakdown?.map((x:any,i:number)=><div className="row" key={i}><span>{x.label}</span><strong>{money(x.amount)}</strong></div>)}<div className="total"><span>Total</span><strong>{money(quote.total)}</strong></div><p>Deposit {money(quote.deposit)} · Balance {money(quote.total-quote.deposit)}</p><p>Settlement: €{(quote.total/100).toFixed(2)} EUR. Other currencies are indicative.</p></div>}
{step===3&&!quote&&<p role="status">Your selections changed. Recalculate your price to continue.</p>}
{step>=1&&step<=2&&<div className="live-price" aria-live="polite">{liveBusy?'Updating your price…':liveQuote?<><span>{liveQuote.mode==='person'?<>{money(liveQuote.unit)} / traveler on average</>:<>Private group price</>}</span><strong>Total {money(liveQuote.total)}</strong><small>Deposit {money(liveQuote.deposit)} · Balance {money(liveQuote.total-liveQuote.deposit)}</small></>:null}</div>}</div><div className="booking-actions"><span className="selected-booking-date">{cart.date||'Select a date'}{cart.pickupTime?' · '+pickupLabel(cart.pickupTime):''}</span>{step>0&&<button className="outline" disabled={busy} onClick={()=>{setStep(step-1);setError('')}}>Back</button>}<button className="primary" disabled={busy||!cart.date||!timeValid} onClick={()=>{if(step<2)setStep(step+1);else if(step===2||!quote)check();else {trackDiscovery('booking-start',{tour:page.path});setModal('checkout')}}}>{busy?'Checking availability…':step===2||step===3&&!quote?'Calculate price':step===3?'Continue to checkout':'Continue'}<ArrowRight size={17}/></button></div></>}
{modal==='checkout'&&<form onSubmit={async e=>{e.preventDefault();if(!user){signin();return}if(!quote||quoted.current!==signature){setModal('booking');setStep(2);setError('Please review an updated quote.');return}setBusy(true);setError('');try{key.current||=crypto.randomUUID();const b=await api('booking',{language:lang,analytics:analyticsContext(),tour:page.path,...cart,currency,...details,accepted,expectedTotal:quote.total,expectedDeposit:quote.deposit,requestKey:key.current});try{sessionStorage.removeItem(storage)}catch{}setModal('');onBooked({...b,date:cart.date,guests});key.current='';toast.success(b.status==='pending'?'Test booking request saved':'Test booking confirmed')}catch(e:any){setError(e.message);if(/price|deposit/.test(e.message)){setQuote(null);setModal('booking');setStep(2)}}finally{setBusy(false)}}}><p>{cart.date}{cart.pickupTime?' · '+pickupLabel(cart.pickupTime):''} · {guests} travelers · {quote?money(quote.total):'Updated quote required'}</p><label className="field"><span>Who are you booking for?</span><select value={details.bookingType} onChange={e=>{setDetails({...details,bookingType:e.target.value});key.current=''}}><option value="DIRECT">Myself and my group</option><option value="BOOK_FOR_SOMEONE">Someone else</option><option value="GIFT">A gift for someone</option></select></label>{details.bookingType!=='DIRECT'&&<div className="form-grid">{['name','email'].map(k=><Field key={k} label={'Traveler '+k} required type={k==='email'?'email':'text'} value={details.traveler[k]} onChange={(e:any)=>setDetails({...details,traveler:{...details.traveler,[k]:e.target.value}})}/>)}</div>}<div className="form-grid">{[['name','Purchaser name'],['email','Email'],['phone','Phone / WhatsApp'],['pickup','Pickup address']].map(([k,l])=><Field key={k} label={l} type={k==='email'?'email':'text'} required={k==='name'||k==='email'} value={details[k]} onChange={(e:any)=>setDetails({...details,[k]:e.target.value})}/>)}</div><Field label="Special requests" value={details.notes} onChange={(e:any)=>setDetails({...details,notes:e.target.value})}/><label className="check-row"><Checkbox checked={accepted} onCheckedChange={v=>setAccepted(v===true)}/><span>I accept the <a href="/terms-conditions/" target="_blank">booking terms</a>. No payment or external email is sent in this development preview.</span></label><div className="booking-actions"><button type="button" className="outline" onClick={()=>{setModal('booking');setStep(3)}}>Back</button><button className="primary" disabled={busy||!accepted||!quote}>{busy?'Confirming…':user?'Confirm test booking':'Sign in to continue'}</button></div></form>}
{modal==='enquiry'&&<Enquiry page={page} date={cart.date} guests={guests} pickup={details.pickup} currency={currency} lang={lang} displayedPrice={from===null?'On request':new Intl.NumberFormat('en',{style:'currency',currency}).format(from*(cfg.currencies[currency]||1))}/>}{error&&<p className="error" role="alert">{error}</p>}
</DialogContent></Dialog></>}
export {Enquiry};
