'use client';
import {useEffect,useState} from 'react';
import {Check} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
export const languageNames:Record<string,string>={en:'English',fr:'Français',es:'Español'};
export const currencyNames:Record<string,string[]>={EUR:['€','Euro'],USD:['$','US Dollar'],GBP:['£','British Pound'],MAD:['د.م.','Moroccan Dirham'],CAD:['$','Canadian Dollar'],AUD:['$','Australian Dollar']};
export function usePreferenceViewport(open:boolean){const [v,setV]=useState({height:0,top:0});useEffect(()=>{if(!open)return;const update=()=>setV({height:window.visualViewport?.height||window.innerHeight,top:window.visualViewport?.offsetTop||0});update();window.visualViewport?.addEventListener('resize',update);window.visualViewport?.addEventListener('scroll',update);window.addEventListener('resize',update);return()=>{window.visualViewport?.removeEventListener('resize',update);window.visualViewport?.removeEventListener('scroll',update);window.removeEventListener('resize',update)}},[open]);return {'--preference-height':v.height?v.height+'px':'100dvh','--preference-top':v.top+'px'} as any}
export function TravelPreferences({mode,setMode,lang,setLang,currency,setCurrency,cfg}:any){const viewport=usePreferenceViewport(!!mode);return <Dialog open={!!mode} onOpenChange={o=>!o&&setMode('')}><DialogContent className="preferences-modal" style={viewport}><DialogTitle>{mode==='language'?'Make yourself at home':'Choose your currency'}</DialogTitle><DialogDescription>{mode==='language'?'Choose your preferred language. Reviewed translations appear where available.':'Prices are converted for planning. Bookings settle in EUR.'}</DialogDescription><div className="preference-scroll"><RadioGroup className="preference-grid" value={mode==='language'?lang:currency} onValueChange={v=>{mode==='language'?setLang(v):setCurrency(v);setMode('')}}>{(mode==='language'?Object.keys(languageNames):Object.keys(cfg.currencies)).map(v=><label className="preference-option" key={v}><RadioGroupItem value={v}/><span className="preference-symbol">{mode==='language'?v.toUpperCase():currencyNames[v]?.[0]||v}</span><span><strong>{mode==='language'?languageNames[v]:v}</strong><small>{mode==='language'?'Navigation & reviewed content':currencyNames[v]?.[1]||v}</small></span>{(mode==='language'?lang:currency)===v&&<Check size={17}/>}</label>)}</RadioGroup></div></DialogContent></Dialog>}
