'use client';
import {useEffect,useRef,useState} from 'react';
import {EditorContent,useEditor} from '@tiptap/react';
import {Extension} from '@tiptap/core';
import StarterKit from '@tiptap/starter-kit';
import Image from '@tiptap/extension-image';
import {TableKit} from '@tiptap/extension-table';
import TextAlign from '@tiptap/extension-text-align';
import {TextStyle} from '@tiptap/extension-text-style';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Bold,Italic,Underline,Link as LinkIcon,Unlink,ImagePlus,Undo2,Redo2,ArrowUp,ArrowDown,Trash2} from 'lucide-react';
import {toast} from 'sonner';

const Anchors=Extension.create({name:'contentAnchors',addGlobalAttributes(){return [{types:['paragraph','heading'],attributes:{id:{default:null,parseHTML:el=>el.getAttribute('id'),renderHTML:attrs=>attrs.id?{id:attrs.id}:{}}}}]}});
const Weight=Extension.create({name:'fontWeight',addGlobalAttributes(){return [{types:['textStyle'],attributes:{fontWeight:{default:null,parseHTML:el=>el.style.fontWeight||null,renderHTML:attrs=>attrs.fontWeight?{style:`font-weight: ${attrs.fontWeight}`}:{}}}}]}});
const escape=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function blockHTML(block:any){if(block.html!==undefined)return block.html;const text=block.text||'';let cursor=0,html='';for(const link of (block.links||[]).map((l:any)=>({...l,start:text.indexOf(l.text)})).filter((l:any)=>l.text&&l.start>=0).sort((a:any,b:any)=>a.start-b.start)){if(link.start<cursor)continue;html+=escape(text.slice(cursor,link.start))+`<a href="${escape(link.href)}">${escape(link.text)}</a>`;cursor=link.start+link.text.length}return html+escape(text.slice(cursor)).replaceAll('\n','<br>')}
export function VisualEditor({value='',onChange,label='Content',inline=false}: {value?:string;onChange:(html:string,text:string)=>void;label?:string;inline?:boolean}){
 const change=useRef(onChange);change.current=onChange;
 const [linkOpen,setLinkOpen]=useState(false),[href,setHref]=useState(''),[anchor,setAnchor]=useState(''),[newTab,setNewTab]=useState(false),[imageOpen,setImageOpen]=useState(false),[imageUrl,setImageUrl]=useState(''),[alt,setAlt]=useState(''),[uploading,setUploading]=useState(false),[library,setLibrary]=useState<any[]>([]),[preview,setPreview]=useState(false),[mobile,setMobile]=useState(false),[tick,refresh]=useState(0);
 const selection=useRef({from:1,to:1});
 const editor=useEditor({immediatelyRender:false,extensions:[Anchors,TableKit,StarterKit.configure({heading:{levels:[2,3,4]},link:{openOnClick:false,defaultProtocol:'https'}}),Image.configure({inline,allowBase64:false}),TextStyle,Weight,TextAlign.configure({types:['heading','paragraph']})],content:value,editorProps:{attributes:{class:'visual-canvas',role:'textbox','aria-label':label,'aria-multiline':'true'}},onUpdate:({editor})=>{let html=editor.getHTML();if(inline)html=html.replace(/<\/p>\s*<p[^>]*>/g,'<br>').replace(/^<p[^>]*>|<\/p>$/g,'');change.current(html,editor.getText());refresh(n=>n+1)},onSelectionUpdate:()=>refresh(n=>n+1)});
 useEffect(()=>{if(!editor)return;let current=editor.getHTML();if(inline)current=current.replace(/<\/p>\s*<p[^>]*>/g,'<br>').replace(/^<p[^>]*>|<\/p>$/g,'');if(value!==current)editor.commands.setContent(value,{emitUpdate:false})},[value,editor,inline]);
 function remember(){if(editor)selection.current={from:editor.state.selection.from,to:editor.state.selection.to}}
 function openLink(){if(!editor)return;editor.chain().extendMarkRange('link').run();remember();setHref(editor.getAttributes('link').href||'');setAnchor(editor.state.doc.textBetween(selection.current.from,selection.current.to,' '));setNewTab(editor.getAttributes('link').target==='_blank');setLinkOpen(true)}
 async function openImage(){remember();setImageUrl('');setAlt('');setImageOpen(true);try{const r=await fetch('/api/editor-media');const d:any=await r.json();if(!r.ok)throw Error(d.error);setLibrary(d)}catch(e:any){toast.error(e.message)}}
 function moveBlock(delta:number){if(!editor)return;const {doc,selection:s}=editor.state,index=s.$from.index(0),nodes:any[]=[];doc.forEach(n=>nodes.push(n));if(index+delta<0||index+delta>=nodes.length)return;[nodes[index],nodes[index+delta]]=[nodes[index+delta],nodes[index]];const tr=editor.state.tr.replaceWith(0,doc.content.size,nodes);editor.view.dispatch(tr);editor.commands.focus();refresh(n=>n+1)}
 if(!editor)return <div className="visual-editor"><p role="status">Opening visual editor…</p></div>;
 const tool=(title:string,icon:any,action:()=>void,active=false,disabled=false)=><button type="button" title={title} aria-label={title} aria-pressed={active} disabled={disabled} onMouseDown={e=>e.preventDefault()} onClick={action}>{icon}</button>;
 return <section className={'visual-editor '+(inline?'visual-inline':'')} aria-label={label+' editor'}><div className="visual-heading"><strong>{label}</strong><div><button type="button" aria-pressed={!preview} onClick={()=>setPreview(false)}>Write</button><button type="button" aria-pressed={preview} onClick={()=>setPreview(true)}>Preview</button>{preview&&<button type="button" onClick={()=>setMobile(!mobile)}>{mobile?'Desktop width':'Mobile width'}</button>}</div></div>{!preview&&<div className="visual-toolbar" role="toolbar" aria-label="Text formatting">
 {!inline&&<select aria-label="Paragraph or heading" value={editor.isActive('heading')?String(editor.getAttributes('heading').level):'p'} onChange={e=>e.target.value==='p'?editor.chain().focus().setParagraph().run():editor.chain().focus().setHeading({level:Number(e.target.value) as 2|3|4}).run()}><option value="p">Paragraph</option><option value="2">Heading 2</option><option value="3">Heading 3</option><option value="4">Heading 4</option></select>}
 {tool('Bold',<Bold size={17}/>,()=>editor.chain().focus().toggleBold().run(),editor.isActive('bold'))}{tool('Italic',<Italic size={17}/>,()=>editor.chain().focus().toggleItalic().run(),editor.isActive('italic'))}{tool('Underline',<Underline size={17}/>,()=>editor.chain().focus().toggleUnderline().run(),editor.isActive('underline'))}
 <select aria-label="Font weight" value={editor.getAttributes('textStyle').fontWeight||(editor.isActive('bold')?'700':'400')} onChange={e=>{editor.chain().focus().unsetBold().setMark('textStyle',{fontWeight:e.target.value}).run();refresh(n=>n+1)}}>{[['400','Regular'],['500','Medium'],['600','Semibold'],['700','Bold'],['800','Extra bold']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select>
 {tool('Add or edit link',<LinkIcon size={17}/>,openLink,editor.isActive('link'))}{tool('Remove link',<Unlink size={17}/>,()=>editor.chain().focus().unsetLink().run(),false,!editor.isActive('link'))}{tool('Insert image',<ImagePlus size={17}/>,openImage)}
 {!inline&&<><button type="button" onClick={()=>editor.chain().focus().toggleBulletList().run()}>• List</button><button type="button" onClick={()=>editor.chain().focus().toggleOrderedList().run()}>1. List</button><select aria-label="Text alignment" value={editor.getAttributes('paragraph').textAlign||editor.getAttributes('heading').textAlign||'left'} onChange={e=>editor.chain().focus().setTextAlign(e.target.value).run()}><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></>}
 {tool('Undo',<Undo2 size={17}/>,()=>editor.chain().focus().undo().run(),false,!editor.can().undo())}{tool('Redo',<Redo2 size={17}/>,()=>editor.chain().focus().redo().run(),false,!editor.can().redo())}<button type="button" onClick={()=>editor.chain().focus().unsetAllMarks().run()}>Clear style</button>
 </div>}
 {preview?<div className={'visual-preview editorial-copy '+(mobile?'is-mobile':'')} dangerouslySetInnerHTML={{__html:editor.getHTML()}}/>:<EditorContent editor={editor}/>}
 {!inline&&!preview&&<div className="visual-blocks"><span>Add block</span><button type="button" onClick={()=>editor.chain().focus('end').insertContent('<p>New paragraph</p>').run()}>+ Text</button><button type="button" onClick={()=>editor.chain().focus('end').insertContent('<h2>New heading</h2>').run()}>+ Heading</button><button type="button" onClick={()=>editor.chain().focus('end').insertContent('<blockquote><p>New quote</p></blockquote>').run()}>+ Quote</button><button type="button" onClick={()=>editor.chain().focus('end').setHorizontalRule().run()}>+ Divider</button>{tool('Move current block up',<ArrowUp size={16}/>,()=>moveBlock(-1))}{tool('Move current block down',<ArrowDown size={16}/>,()=>moveBlock(1))}<span>Click inside a block to move it.</span></div>}
 <Dialog open={linkOpen} onOpenChange={setLinkOpen}><DialogContent className="modal"><DialogTitle>Link selected text</DialogTitle><DialogDescription>Choose a destination for this word or sentence.</DialogDescription><label className="field"><span>Link text</span><input value={anchor} onChange={e=>setAnchor(e.target.value)}/></label><label className="field"><span>Destination</span><input placeholder="https://… or /tour-page/" value={href} onChange={e=>setHref(e.target.value)}/></label><label className="check-row"><input type="checkbox" checked={newTab} onChange={e=>setNewTab(e.target.checked)}/>Open in a new tab</label><button type="button" className="primary" onClick={()=>{if(!/^(https?:\/\/|mailto:|tel:|\/(?!\/)|#)/i.test(href.trim())||/[\u0000-\u0020]/.test(href.trim())){toast.error('Use a website URL, local path, email, phone or #anchor.');return}if(!anchor.trim()){toast.error('Enter the text to link.');return}const chain=editor.chain().focus().setTextSelection(selection.current);const attrs={href:href.trim(),target:newTab?'_blank':'_self'};if(editor.state.doc.textBetween(selection.current.from,selection.current.to,' ')===anchor){chain.setLink(attrs).run()}else{chain.insertContent({type:'text',text:anchor,marks:[{type:'link',attrs}]}).run()}setLinkOpen(false)}}>Apply link</button></DialogContent></Dialog>
 <Dialog open={imageOpen} onOpenChange={setImageOpen}><DialogContent className="modal visual-media"><DialogTitle>Insert an image</DialogTitle><DialogDescription>Upload a photo or select from your media library, then add alternative text.</DialogDescription><label className="field"><span>{uploading?'Uploading…':'Upload JPG, PNG or WebP · up to 8 MB'}</span><input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>8*1024*1024){toast.error('Choose an image smaller than 8 MB.');return}setUploading(true);try{const body=new FormData();body.set('file',f);const r=await fetch('/api/upload',{method:'POST',body});const d:any=await r.json();if(!r.ok)throw Error(d.error);setImageUrl(d.url);setAlt(f.name.replace(/\.[^.]+$/,''));setLibrary(v=>[{url:d.url,name:f.name},...v])}catch(e:any){toast.error(e.message)}finally{setUploading(false)}}}/></label><div className="visual-media-grid">{library.map((m:any)=><button type="button" key={m.url} aria-pressed={imageUrl===m.url} onClick={()=>{setImageUrl(m.url);setAlt(m.alt||m.name||'')}}><img src={m.url} alt={m.alt||m.name||''} loading="lazy"/></button>)}</div><label className="field"><span>Alternative text (describe the image)</span><input value={alt} onChange={e=>setAlt(e.target.value)}/></label><button type="button" className="primary" disabled={!imageUrl||uploading} onClick={()=>{editor.chain().focus().setTextSelection(selection.current).setImage({src:imageUrl,alt}).run();setImageOpen(false)}}>Insert selected image</button></DialogContent></Dialog>
 </section>
}

export function RichBlocksEditor({value=[],onChange,label}:any){const move=(i:number,n:number)=>{const next=[...value];[next[i],next[i+n]]=[next[i+n],next[i]];onChange(next)};return <div className="rich-block-editor"><h3>{label}</h3>{value.map((b:any,i:number)=><div key={i} className="rich-block-item"><VisualEditor inline label={label+' '+(i+1)} value={blockHTML(b)} onChange={(html,text)=>onChange(value.map((v:any,j:number)=>i===j?{...v,html,text,links:[]}:v))}/><div className="rich-block-actions"><button type="button" className="outline" disabled={i===0} onClick={()=>move(i,-1)}><ArrowUp size={15}/>Move up</button><button type="button" className="outline" disabled={i===value.length-1} onClick={()=>move(i,1)}><ArrowDown size={15}/>Move down</button><button type="button" className="outline" onClick={()=>onChange(value.filter((_:any,j:number)=>j!==i))}><Trash2 size={15}/>Remove block</button></div></div>)}<button type="button" className="outline" onClick={()=>onChange([...value,{text:'',html:'',links:[]}])}>+ Add {label.toLowerCase()} block</button></div>}
