import {cleanRich} from './rich-content';
import seed from '@/data/about-story.json';
import {db,now,rows,record} from './server';
import {pages} from './model';
import {aboutHTML,aboutLink,aboutTypes,aboutPath} from './about-content';
import {publishedReviews} from './review-engine';
import {discoveryData} from './discovery-server';
import {seoProfile} from './seo-platform';
export const aboutConnectDefaults={enabled:true,eyebrow:'LET’S KEEP IN TOUCH',heading:'A little Morocco in your inbox.',body:'Travel ideas, thoughtful routes and inspiration for your next journey.',companyHeading:'Real people. Right here in Morocco.'};
export async function aboutDocument(draft=false){const r=await db().prepare('SELECT value FROM settings WHERE key=?').bind(draft?'about:draft':'about:published').first<any>();const d=r?JSON.parse(r.value):structuredClone(seed);return {...d,connect:{...aboutConnectDefaults,...d.connect}}}
export async function publicAboutDocument(){const d=await aboutDocument();return {sections:d.sections.filter((s:any)=>s.enabled),values:d.values.filter((v:any)=>v.visible),team:d.team.filter((t:any)=>t.visible),teamHeading:d.teamHeading,route:d.route,categoryMode:d.categoryMode,categories:d.categories.filter((c:any)=>c.visible),reviews:d.reviews,connect:d.connect}}
export async function aboutAdmin(){return {draft:await aboutDocument(true),published:await aboutDocument(),revisions:(await rows('about-revision')).map(r=>({id:r.id,created:r.created,editor:r.owner,action:r.data.action})),subscribers:await rows('newsletter'),reviews:await publishedReviews(),discovery:await discoveryData(),media:(await rows('media')).filter(r=>!r.data.archived).map(r=>r.data),seo:await seoProfile(aboutPath)}}
const text=(v:any,n=500)=>String(v||'').trim().slice(0,n);
function photo(x:any={}){const url=text(x.url,1000);if(url&&!/^\/(?:media|assets|wp-content)\/[^\s<>"\\]+$/.test(url))throw Error('Choose permanent site media');return {url,alt:text(x.alt,300),caption:text(x.caption,500),demo:x.demo!==false,x:Math.max(0,Math.min(100,Number(x.x)||0)),y:Math.max(0,Math.min(100,Number(x.y)||0))}}
function validate(v:any){if(!Array.isArray(v.sections)||v.sections.length!==aboutTypes.length||new Set(v.sections.map((s:any)=>s.type)).size!==aboutTypes.length||v.sections.some((s:any)=>!aboutTypes.includes(s.type)))throw Error('Keep the structured About sections');const sections=v.sections.map((s:any)=>({id:s.type,type:s.type,enabled:s.type==='hero'||!!s.enabled,eyebrow:text(s.eyebrow,100),heading:text(s.heading,200),body:cleanRich(s.body),background:['white','sand','ink'].includes(s.background)?s.background:'white',image:photo(s.image),secondaryImage:photo(s.secondaryImage),ctaLabel:text(s.ctaLabel,80),ctaUrl:aboutLink(s.ctaUrl),secondaryCtaLabel:text(s.secondaryCtaLabel,80),secondaryCtaUrl:aboutLink(s.secondaryCtaUrl)}));if(!sections.find((s:any)=>s.type==='hero').heading)throw Error('Add the page heading');return {sections,connect:{enabled:v.connect?.enabled!==false,eyebrow:text(v.connect?.eyebrow||aboutConnectDefaults.eyebrow,100),heading:text(v.connect?.heading||aboutConnectDefaults.heading,200),body:text(v.connect?.body||aboutConnectDefaults.body,700),companyHeading:text(v.connect?.companyHeading||aboutConnectDefaults.companyHeading,200)},values:(v.values||[]).slice(0,12).map((x:any,i:number)=>({id:text(x.id)||'value-'+i,title:text(x.title,150),description:text(x.description,2000),icon:['compass','users','route','sun'].includes(x.icon)?x.icon:'compass',visible:!!x.visible})),team:(v.team||[]).slice(0,30).map((x:any,i:number)=>{if(x.visible&&(!x.name||!x.role||!x.bio))throw Error('Visible team profiles need a name, role and biography');return {id:text(x.id)||'team-'+i,name:text(x.name,120),role:text(x.role,120),bio:text(x.bio,2000),languages:text(x.languages,300),speciality:text(x.speciality,300),photo:photo(x.photo),visible:!!x.visible}}),teamHeading:text(v.teamHeading,200),route:(v.route||[]).slice(0,8).map((x:any)=>text(x,100)).filter(Boolean),categoryMode:v.categoryMode==='manual'?'manual':'auto',categories:(v.categories||[]).slice(0,20).map((x:any)=>({id:text(x.id,200),label:text(x.label,120),image:photo(x.image),visible:x.visible!==false})),reviews:{demoWhenEmpty:v.reviews?.demoWhenEmpty!==false,mode:v.reviews?.mode==='manual'?'manual':'auto',ids:(v.reviews?.ids||[]).slice(0,6).map((x:any)=>text(x,100)),limit:Math.max(3,Math.min(6,Number(v.reviews?.limit)||6))}}}
export async function saveAbout(b:any,actor:string){if(b.action==='restore'){const r=await db().prepare("SELECT data FROM records WHERE kind='about-revision' AND id=?").bind(b.id).first<any>();if(!r)throw Error('Revision not found');const restored=JSON.parse(r.data).document;return saveAbout({action:'draft',document:restored},actor)}if(!['draft','publish'].includes(b.action))throw Error('Choose Save draft or Publish');if(b.action==='publish'&&b.confirm!==true)throw Error('Review and confirm the About content before publishing');const value={...validate(b.document),updated:now(),editor:actor,revision:crypto.randomUUID()};const previous=await aboutDocument(b.action!=='publish');const original=pages.find(p=>p.path===aboutPath);const currentDraft=await aboutDocument(true);if(b.expectedRevision&&currentDraft.revision&&b.expectedRevision!==currentDraft.revision)throw Error('Another editor saved this page. Reload before saving your changes.');const queries=[db().prepare('INSERT OR IGNORE INTO settings(key,value) VALUES (?,?)').bind('about:legacy-source',JSON.stringify(original)),db().prepare('INSERT INTO records(id,kind,owner,data,created) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),'about-revision',actor,JSON.stringify({action:b.action==='publish'?'Before publication':'Before draft update',document:previous}),now()),db().prepare('INSERT INTO settings(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('about:draft',JSON.stringify(value))];if(b.action==='publish')queries.push(db().prepare('INSERT INTO settings(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('about:published',JSON.stringify(value)));await db().batch(queries);await record('admin-log',actor,{action:'About Us '+b.action,path:aboutPath,revision:value.revision});return value}
