export const staffRoles=['admin','operations','finance','content','seo','partner-manager'] as const;
const content=['content-visibility','seo-save','page-document','editor-media','cms-tours','cms-publish','cms-save','cms-duplicate','cms-bulk','golden-admin','golden-save','discovery-admin','discovery-manage','hub-admin','hub-save','page-edit','page-create','media-metadata','editor-state','editor-draft','homepage-layout','home-marketing-save','about-admin','about-save','tour-settings','translation','email','email-admin','template','presence-admin','presence-save'];
const groups:Record<string,string[]>={content,seo:['content-visibility','presence-save','editor-media','media-metadata','seo-platform-admin','seo-save','seo-keyword-research','seo-ai-draft','seo-collection-save','seo-bulk','discovery-analytics'],operations:['hub-admin','bookings','booking-detail','booking-status','booking-amend','booking-retry','booking-document','booking-link-create','operations-status','hub-enquiry'],finance:['bookings','booking-detail','booking-payment','booking-document','partner-dashboard','partner-invoices','partner-invoice-document','partner-statement','partner-payout'], 'partner-manager':['partner-dashboard','partner-catalog','partner-review','partner-organization','partner-invite','partner-member','partner-messages','partner-message','partner-statement']};
export function canAdminOperation(role:string,op:string){return role==='admin'||(groups[role]||[]).includes(op)}
export function canAdminView(role:string,view:string){if(role==='admin')return true;if(['Marketing Overview','Content Performance','Tracking & Attribution'].includes(view))return canMarketing(role,'view_analytics');if(view==='Internal Linking')return canMarketing(role,'manage_seo');if(view==='Landing Pages')return canMarketing(role,'manage_landing_pages');if(view==='Marketing Settings')return canMarketing(role,'manage_tracking');const views:Record<string,string[]>={content:['Tours','Transfers','Trip types','Activities','Destinations','Destination pages','Starting locations','Duration','Pricing','Availability','Tour Content Review','Homepage','Pages','Blog','About Us','Help Center','Media library','Reusable Information','Email templates','Homepage offers','Languages'],seo:['SEO & AI Visibility','Search & discovery'],operations:['Bookings','Calendar','Operations','Enquiries'],finance:['Payments','Bookings','Partners'], 'partner-manager':['Partners']};return (views[role]||[]).includes(view)}
export const firstAdminView=(role:string)=>({operations:'Bookings',finance:'Payments',content:'Tours',seo:'SEO & AI Visibility','partner-manager':'Partners'} as any)[role]||'Dashboard';

export const marketingPermissions:Record<string,string[]>={admin:['view_marketing','view_analytics','manage_seo','manage_landing_pages','manage_tracking'],seo:['view_marketing','view_analytics','manage_seo','manage_landing_pages'],content:['view_marketing','manage_landing_pages'],finance:['view_marketing','view_analytics']};
export function canMarketing(role:string,permission:string){return (marketingPermissions[role]||[]).includes(permission)}
