import {saveTour,tourModels} from './tour-cms';
import {saveGolden,goldenAdmin} from './golden-server';
import {db,now,record} from './server';
import {homeSections,normalizeHomeLayout} from './home-layout';
const allowed=/^(tour|page|faq|email|homepage|settings):.{1,600}$/;
export async function editorState(key:string,owner:string){if(!allowed.test(key))throw Error('Invalid editor');const draft=await db().prepare("SELECT data FROM records WHERE kind='editor-draft' AND id=? AND owner=?").bind('draft:'+owner+':'+key,owner).first<any>();const revisions=await db().prepare("SELECT id,owner,created,data FROM records WHERE kind='editor-revision' AND json_extract(data,'$.key')=? ORDER BY created DESC LIMIT 25").bind(key).all<any>();return {draft:draft?JSON.parse(draft.data):null,revisions:revisions.results.map(r=>({...r,data:JSON.parse(r.data)}))}}
export async function saveEditorDraft(b:any,owner:string){if(!allowed.test(b.key)||!b.value||JSON.stringify(b.value).length>400000)throw Error('Invalid draft');const id='draft:'+owner+':'+b.key,value={key:b.key,value:b.value,updated:now()};await db().prepare('INSERT INTO records(id,kind,owner,data,created) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,created=excluded.created').bind(id,'editor-draft',owner,JSON.stringify(value),value.updated).run();return value}
export async function revision(key:string,value:any,owner:string,action:string){return record('editor-revision',owner,{key,value,action},crypto.randomUUID())}
export async function homeLayout(){const row=await db().prepare("SELECT value FROM settings WHERE key='homepage-layout'").first<any>();return normalizeHomeLayout(row?JSON.parse(row.value):null)}
export async function saveHomeLayout(b:any,owner:string){if(!Array.isArray(b.sections)||b.sections.length!==homeSections.length||new Set(b.sections.map((s:any)=>s.id)).size!==homeSections.length)throw Error('Keep all homepage section records; disable a section instead of deleting it.');const sections=b.sections.map((s:any)=>{const base=homeSections.find(x=>x.id===s.id);if(!base||s.kind!==base.kind)throw Error('Unknown homepage section');if(!['all','selected','featured','spain-day','type','destination','origin','activity'].includes(s.source))throw Error('Choose a supported carousel source');if(s.url&&!/^\/(?!\/)[^\\\s]*$/.test(s.url))throw Error('Use a local CTA URL');if(!Array.isArray(s.paths)||s.paths.length>100||s.paths.some((p:any)=>typeof p!=='string'||!p.startsWith('/')))throw Error('Invalid tour selection');return {...base,enabled:s.enabled!==false,title:String(s.title||'').slice(0,200),kicker:String(s.kicker||'').slice(0,200),url:String(s.url||'').slice(0,600),source:s.source,term:String(s.term||'').slice(0,200),paths:s.paths,limit:Math.max(1,Math.min(50,Number(s.limit)||24))}});await revision('homepage:layout',await homeLayout(),owner,'Before homepage update');await db().prepare("INSERT INTO settings(key,value) VALUES ('homepage-layout',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(JSON.stringify({sections})).run();await record('admin-log',owner,{action:'Homepage sections updated',target:'/'});return {sections}}

export async function publishTour(b:any,owner:string){if(b.golden?.path!==b.path)throw Error('Tour and structured content URLs must match.');const previous=(await tourModels())[b.path];const product=await saveTour(b,undefined,true);const golden=await saveGolden({action:'save',tour:b.golden},owner,true);const revisionValue=previous?{...previous,golden:(await goldenAdmin(b.path)).tour}:null;const queries=[db().prepare('INSERT INTO settings(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('product:'+b.path,JSON.stringify(product)),db().prepare('INSERT INTO settings(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('golden:'+b.path,JSON.stringify(golden))];if(previous)queries.push(db().prepare('INSERT INTO records(id,kind,owner,data,created) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),'editor-revision',owner,JSON.stringify({key:'tour:'+b.path,value:revisionValue,action:'Before tour update'}),now()));queries.push(db().prepare('INSERT INTO records(id,kind,owner,data,created) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),'admin-log',owner,JSON.stringify({action:'Tour content and gallery updated',target:b.path}),now()));await db().batch(queries);return {...product,golden};}
