import {attachConversion,backendMarketingEvent} from './marketing';
import {selectedPickup} from './pickup-times';
import {creditOutstandingSQL,invoiceTerms,invoiceSnapshot} from './invoices';
import {giftDeliveryInput,queueGiftDelivery} from './gift-delivery';
import {partnerPermission,memberRole,allowedTour,commissionFor} from './partner-service';
import {db,now,config,tourConfig,applyCoupon,requireUser,rows,queueEmail} from './server';
import {priceQuote} from './pricing';
import {confirmOperations,reconcileOperations} from './booking-operations';
import {ensureReviewRequest} from './review-engine';

export const bookingTypes=['DIRECT','PARTNER','BOOK_FOR_SOMEONE','GIFT','ADMIN_CREATED','CUSTOM_TOUR'];
const clean=(v:any,n=500)=>String(v??'').trim().slice(0,n);
const parse=(b:any)=>({...b,data:typeof b.data==='string'?JSON.parse(b.data):b.data});
const active="status IN ('test-confirmed','pending','awaiting-payment','in-progress')";
const dateOK=(d:any)=>typeof d==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&!isNaN(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d&&d>=now().slice(0,10);
const person=(p:any,role:string)=>{const name=clean(p?.name,100),email=clean(p?.email,200).toLowerCase();if(!name||!/^\S+@\S+\.\S+$/.test(email))throw Error('Enter a name and valid email for '+role);return {id:crypto.randomUUID(),role,name,email,phone:clean(p.phone,40)}};

export async function partnersFor(u:any){const list=await rows('partner');return list.filter(r=>u.role==='admin'||memberRole(r.data,u)).map(r=>({id:r.id,...r.data}));}
async function partnerFor(input:any,u:any){if(!input.partnerId)throw Error('Choose an approved partner');const p=(await partnersFor(u)).find(p=>p.id===input.partnerId&&p.active);if(!p)throw Error('Partner access required');await partnerPermission(p.id,u,['admin','booker']);if(!allowedTour(p,input.tour))throw Error('This experience is not in your partner catalog');if(p.paymentModes&&!p.paymentModes.includes(input.partnerPaymentMode||'guest'))throw Error('This payment arrangement is not enabled for your organization');return p;}
export async function savePartner(b:any){await requireUser(true);const rate=b.rate===null||b.rate===''?null:Number(b.rate);if(!b.name||rate!==null&&(!Number.isFinite(rate)||rate<0||rate>100)||!Array.isArray(b.users))throw Error('Provide partner name, user IDs and commission from 0–100%.');const id=b.id||'partner:'+crypto.randomUUID();const tourRates=b.tourRates||{};if(Object.values(tourRates).some((r:any)=>!Number.isFinite(r)||r<0||r>100))throw Error('Invalid tour commission');const existing=await db().prepare("SELECT data FROM records WHERE id=? AND kind='partner'").bind(id).first<any>();if(existing&&JSON.parse(existing.data).members)throw Error('Use Partner management to edit this organization');const data={...(existing?JSON.parse(existing.data):{}),tourRates,name:clean(b.name,150),users:[...new Set(b.users.map((v:any)=>clean(v,150)).filter(Boolean))],rate,active:b.active!==false};await db().prepare('INSERT INTO records(id,kind,owner,data,created) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data WHERE records.kind=excluded.kind').bind(id,'partner','admin',JSON.stringify(data),now()).run();return {id,...data};}
export async function availability(tour:string,date?:string){const q=date?db().prepare(`SELECT date,SUM(guests) AS used FROM bookings WHERE tour=? AND date=? AND ${active} GROUP BY date`).bind(tour,date):db().prepare(`SELECT date,SUM(guests) AS used FROM bookings WHERE tour=? AND ${active} GROUP BY date`).bind(tour);return Object.fromEntries((await q.all<any>()).results.map(x=>[x.date,x.used]));}
export async function priceBooking(input:any,u?:any,excludeId?:string){const type=input.bookingType||'DIRECT';if(!bookingTypes.includes(type))throw Error('Invalid booking type');const t=await tourConfig(input.tour),c=await config();if(['archived','draft'].includes(t.status)||['enquiry','custom'].includes(t.bookingMode))throw Error('This experience is available by enquiry only.');const flexible=type==='GIFT'&&input.flexible===true;if(!flexible&&!dateOK(input.date))throw Error('Choose a valid future travel date.');if(flexible&&(t.seasons?.length||t.overrides?.length))throw Error('Choose a fixed date for this date-priced experience.');if(!flexible&&([...c.blackouts,...t.blackouts].includes(input.date)||t.availableDays?.length&&!t.availableDays.includes(new Date(input.date+'T12:00:00Z').getUTCDay())))throw Error('This date is unavailable.');const pickupTime=selectedPickup(t.pickupTimes,flexible?'':input.pickupTime,!flexible&&!excludeId);const price=await applyCoupon(priceQuote(t,input),input.coupon,input.date||'');if(!flexible){const used=await db().prepare(`SELECT COALESCE(SUM(guests),0) AS n FROM bookings WHERE tour=? AND date=? AND id<>? AND ${active}`).bind(input.tour,input.date,excludeId||'').first<any>();if(used.n+price.guests>t.capacity)throw Error('This date has insufficient availability.');}
 let partner:any=null,commission=0,commissionRule='none',commissionRate=0;if(type==='PARTNER'){u=u||await requireUser();partner=await partnerFor(input,u);const rule=await commissionFor(partner,input.tour,price.total,{tour:t.commissionRate,global:c.commissionRate});commissionRate=rule.rate;commission=rule.amount;commissionRule=rule.rule;}
 const currency=Object.hasOwn(c.currencies,input.currency)?input.currency:'EUR',rate=c.currencies[currency],deposit=Math.round(price.total*(t.deposit??c.deposit)/100);return {...price,pickupTime,currency,rate,displayTotal:Math.round(price.total*rate),deposit,balance:price.total-deposit,commission,commissionRate,commissionRule,netRevenue:price.total-commission,settlementCurrency:'EUR',testOnly:true,partnerId:partner?.id||null,capacity:t.capacity,bookingMode:t.bookingMode,flexible};}

function eventStatement(b:any,type:string,actor:string,detail:any={},key=crypto.randomUUID()){return db().prepare('INSERT OR IGNORE INTO records(id,kind,owner,data,created) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM bookings WHERE id=?)').bind('booking-event:'+b.id+':'+key,'booking-event',b.id,JSON.stringify({bookingId:b.id,type,actor,detail}),now(),b.id);}
export async function bookingView(raw:any){const b=parse(raw),d=b.data;const payments=(await rows('booking-payment',b.id)).map(r=>r.data);const received=payments.filter(p=>p.kind==='payment').reduce((s,p)=>s+p.amount,0),refunded=payments.filter(p=>p.kind==='refund').reduce((s,p)=>s+p.amount,0),paid=received-refunded;return {...b,bookingId:b.id,reference:b.id,bookingType:d.bookingType||'DIRECT',paymentStatus:refunded?(paid?'partially-refunded':'refunded'):paid>=b.total?'paid':paid>=d.deposit?'deposit-paid':paid?'partially-paid':'unpaid',paid,refunded,balanceDue:b.status==='cancelled'?0:Math.max(0,b.total-received),commissionAmount:b.status==='cancelled'?0:Math.round((d.commission||0)*(b.total?Math.max(0,b.total-refunded)/b.total:0)),netRevenue:paid-(b.status==='cancelled'?0:Math.round((d.commission||0)*(b.total?Math.max(0,b.total-refunded)/b.total:0)))};}
export async function accessibleBooking(id:string,u:any){const raw=await db().prepare('SELECT * FROM bookings WHERE id=?').bind(id).first<any>();if(!raw)throw Error('Booking access required');const b=parse(raw);if(u.role!=='admin'){const permitted=b.data.partnerId?(await partnersFor(u)).some(p=>p.active&&p.id===b.data.partnerId):b.owner===u.id;if(!permitted)throw Error('Booking access required');}return b;}
export async function listBookings(u:any){const partners=(await partnersFor(u)).filter(p=>p.active).map(p=>p.id);const result=await db().prepare('SELECT * FROM bookings ORDER BY created DESC').all<any>();const allowed=result.results.filter(b=>u.role==='admin'||(JSON.parse(b.data).partnerId?partners.includes(JSON.parse(b.data).partnerId):b.owner===u.id));return Promise.all(allowed.map(bookingView));}
export async function bookingDetail(id:string,u:any){const b=await accessibleBooking(id,u);return {booking:await bookingView(b),events:await rows('booking-event',id),payments:await rows('booking-payment',id),documents:(await db().prepare("SELECT json_extract(data,'$.status') AS status FROM records WHERE id=? AND kind='passengers'").bind('passengers:'+id).first<any>())?.status||'Not required'};}

export async function createBooking(input:any,u:any){if(!input.accepted)throw Error('Accept the booking terms to continue.');if(!/^[\w-]{8,100}$/.test(input.requestKey||''))throw Error('Invalid booking request.');const prior=await db().prepare('SELECT * FROM bookings WHERE owner=? AND request_key=?').bind(u.id,input.requestKey).first<any>();if(prior){await dispatchBookingEvents(prior.id);return bookingView(prior);}
 const type=input.bookingType||'DIRECT';if(['ADMIN_CREATED','CUSTOM_TOUR'].includes(type)&&u.role!=='admin')throw Error('Administrator access required.');if(type==='CUSTOM_TOUR'){const lead=await db().prepare("SELECT id FROM records WHERE id=? AND kind='lead'").bind(clean(input.customTourId)).first();if(!lead)throw Error('Select an existing custom enquiry');const existing=await db().prepare("SELECT * FROM bookings WHERE json_extract(data,'$.customTourId')=?").bind(input.customTourId).first<any>();if(existing)return bookingView(existing);}
 const purchaser=person({name:input.name,email:input.email,phone:input.phone},'purchaser');const traveler=['BOOK_FOR_SOMEONE','GIFT','PARTNER'].includes(type)?person(input.traveler,'primary-traveler'):{...purchaser,id:crypto.randomUUID(),role:'primary-traveler'};const quote=await priceBooking(input,u);if(input.expectedTotal!==undefined&&input.expectedTotal!==quote.total||input.expectedDeposit!==undefined&&input.expectedDeposit!==quote.deposit)throw Error('The price or deposit changed. Please review a fresh quote.');
 const terms=type==='PARTNER'&&input.partnerPaymentMode==='invoice'?await invoiceTerms(quote.partnerId,u):null;
 const id='TE-'+crypto.randomUUID().slice(0,8).toUpperCase(),stamp=now(),token=crypto.randomUUID()+crypto.randomUUID();const status=quote.flexible?'unscheduled':quote.bookingMode==='request'?'pending':'test-confirmed';const data={invoice:terms?invoiceSnapshot(id,terms):null,bookingType:type,source:clean(input.source||'website',80),partnerId:quote.partnerId,partnerUserId:type==='PARTNER'?u.id:null,partnerReference:clean(input.partnerReference,100),partnerPaymentMode:['guest','partner','invoice'].includes(input.partnerPaymentMode)?input.partnerPaymentMode:'guest',customTourId:type==='CUSTOM_TOUR'?input.customTourId:null,participants:[purchaser,traveler],name:traveler.name,email:traveler.email,purchaser,language:['en','fr','es'].includes(input.language)?input.language:'en',country:clean(input.country,80),pickup:clean(input.pickup),pickupTime:quote.pickupTime,notes:clean(input.notes,2000),currency:quote.currency,rate:quote.rate,deposit:quote.deposit,commission:quote.commission,commissionRate:quote.commissionRate,commissionBasis:quote.total,commissionRule:quote.commissionRule,settlementCurrency:'EUR',payment:'SIMULATED — no money charged',unit:quote.unit,party:{adults:quote.adults,children:quote.children,infants:quote.infants},breakdown:quote.breakdown,pricingInput:{pickupTime:quote.pickupTime,extras:input.extras||[],coupon:input.coupon||''},gift:type==='GIFT'?{delivery:giftDeliveryInput(input),recipient:traveler,message:clean(input.giftMessage,1000),hidePrice:input.hidePrice!==false,flexible:quote.flexible,state:quote.flexible?'unscheduled':'scheduled'}:null,updated:stamp,revision:crypto.randomUUID(),createdBy:u.id};
 const b={id,owner:u.id,tour:input.tour,date:quote.flexible?'':input.date,guests:quote.guests,total:quote.total,status,token,data,created:stamp};
 const insert=db().prepare(`INSERT INTO bookings(id,owner,tour,date,guests,total,status,token,data,created,request_key) SELECT ?,?,?,?,?,?,?,?,?,?,? WHERE (SELECT COALESCE(SUM(guests),0) FROM bookings WHERE tour=? AND date=? AND ${active})+?<=? AND (?='' OR NOT EXISTS(SELECT 1 FROM bookings WHERE json_extract(data,'$.customTourId')=?)) AND (?=0 OR ((${creditOutstandingSQL})+?<=?))`).bind(id,u.id,b.tour,b.date,b.guests,b.total,status,token,JSON.stringify(data),stamp,input.requestKey,b.tour,b.date,quote.flexible?0:b.guests,quote.capacity,data.customTourId||'',data.customTourId||'',terms?.creditEnabled?1:0,quote.partnerId||'',b.total,terms?.creditLimit||0);
 try{const result=await db().batch([insert,eventStatement(b,'booking.created',u.id,{status,total:b.total},'created')]);if(!result[0].meta.changes)throw Error('The date filled up, the partner credit limit was reached, or this proposal is already booked.');}catch(e){const concurrent=await db().prepare('SELECT * FROM bookings WHERE owner=? AND request_key=?').bind(u.id,input.requestKey).first<any>();if(concurrent)return bookingView(concurrent);throw e;}
 await attachConversion('booking',id,b.tour,undefined,data.customTourId||undefined);await dispatchBookingEvents(id);return bookingView(b);}

// Durable event records are committed with the booking. Failed delivery stays retryable.
export async function dispatchBookingEvents(id:string){const b=parse(await db().prepare('SELECT * FROM bookings WHERE id=?').bind(id).first<any>());const pending=(await rows('booking-event',id)).filter(r=>!r.data.delivered||!r.data.marketingDelivered);for(const e of pending){const marketing=await backendMarketingEvent(b,e);if(marketing!==null)e.data.marketingDelivered=now();if(e.data.delivered){await db().prepare('UPDATE records SET data=? WHERE id=?').bind(JSON.stringify(e.data),e.id).run();continue;}try{if(['booking.created','booking.confirmed'].includes(e.data.type)){await confirmOperations(b);}if(['booking.modified','booking.cancelled'].includes(e.data.type))await reconcileOperations(b,e.data.type,e.id);if(e.data.type==='booking.completed')await ensureReviewRequest(b);if(e.data.type==='booking.created'){await queueGiftDelivery(b);const existing=await db().prepare("SELECT id FROM records WHERE id=?").bind('booking-email:'+id).first();if(!existing){await queueEmail(b.status==='pending'?'Booking pending':'Booking confirmed',b.owner,{name:b.data.name,email:b.data.email,reference:id,message:'Your staging booking is '+b.status+'. No charge was made.'},'booking-email:'+id);await db().prepare('INSERT OR IGNORE INTO records(id,kind,owner,data,created) VALUES (?,?,?,?,?)').bind('booking-notice:'+id,'booking-notice',id,'{}',now()).run();}}await db().prepare('UPDATE records SET data=? WHERE id=?').bind(JSON.stringify({...e.data,delivered:now()}),e.id).run();}catch(error:any){await db().prepare('UPDATE records SET data=? WHERE id=?').bind(JSON.stringify({...e.data,error:clean(error.message)}),e.id).run();}}}

export async function changeBookingStatus(id:string,status:string,u:any,reason=''){const b=await accessibleBooking(id,u);if(b.data.partnerId)await partnerPermission(b.data.partnerId,u,['admin','booker']);if(status!=='cancelled'&&u.role!=='admin')throw Error('Administrator access required.');const transitions:any={pending:['test-confirmed','cancelled'],unscheduled:['cancelled'],'test-confirmed':['completed','cancelled'],'in-progress':['completed','cancelled'],completed:[],cancelled:[]};if(b.status===status)return bookingView(b);if(!transitions[b.status]?.includes(status)&&!(b.status==='completed'&&status==='cancelled'&&u.role==='admin'&&clean(reason)))throw Error('This booking status transition is not allowed.');const data={...b.data,updated:now(),revision:crypto.randomUUID()};if(status==='cancelled')data.cancellation={at:now(),actor:u.id,reason:clean(reason),refundStatus:'review-required'};
 const cap=await tourConfig(b.tour);const update=db().prepare(`UPDATE bookings SET status=?,token=?,data=? WHERE id=? AND data=? AND (SELECT COALESCE(SUM(guests),0) FROM bookings WHERE tour=? AND date=? AND id<>? AND ${active})+?<=?`).bind(status,crypto.randomUUID()+crypto.randomUUID(),JSON.stringify(data),id,JSON.stringify(b.data),b.tour,b.date,id,status==='test-confirmed'?b.guests:0,status==='test-confirmed'?cap.capacity:999999);
 const kind=status==='test-confirmed'?'booking.confirmed':'booking.'+status;const event=db().prepare('INSERT INTO records(id,kind,owner,data,created) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM bookings WHERE id=? AND data=?)').bind('booking-event:'+id+':'+data.revision,'booking-event',id,JSON.stringify({bookingId:id,type:kind,actor:u.id,detail:{from:b.status,to:status,reason:clean(reason)}}),now(),id,JSON.stringify(data));const r=await db().batch([update,event]);if(!r[0].meta.changes)throw Error('Booking changed or capacity is unavailable. Refresh and retry.');await dispatchBookingEvents(id);return bookingView({...b,status,data});}

export async function recordPayment(input:any,u:any){if(u.role!=='admin')throw Error('Administrator access required.');return applyPayment(input,u,await accessibleBooking(input.id,u));}
async function applyPayment(input:any,u:any,b:any){const view=await bookingView(b),amount=Number(input.amount);if(!Number.isSafeInteger(amount)||amount<=0||!['payment','refund'].includes(input.kind)||!clean(input.reason)||!/^[\w-]{8,100}$/.test(input.requestKey||''))throw Error('Provide an amount in cents, a reason and a unique request key.');const id='booking-payment:'+b.id+':'+input.requestKey;const prior=await db().prepare('SELECT id FROM records WHERE id=?').bind(id).first();if(prior)return view;if(input.kind==='refund'&&amount>view.paid||input.kind==='payment'&&(amount>view.balanceDue||b.status==='cancelled'))throw Error('Amount exceeds the available balance.');const data={...b.data,revision:crypto.randomUUID(),updated:now()};const payment={paidAfter:view.paid+(input.kind==='payment'?amount:-amount),depositAtEvent:b.data.deposit,bookingId:b.id,kind:input.kind,amount,currency:'EUR',mode:'simulation',actor:u.id,reason:clean(input.reason),created:now()};const r=await db().batch([db().prepare('UPDATE bookings SET data=? WHERE id=? AND data=?').bind(JSON.stringify(data),b.id,JSON.stringify(b.data)),db().prepare('INSERT INTO records(id,kind,owner,data,created) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM bookings WHERE id=? AND data=?)').bind(id,'booking-payment',b.id,JSON.stringify(payment),now(),b.id,JSON.stringify(data)),db().prepare('INSERT INTO records(id,kind,owner,data,created) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM bookings WHERE id=? AND data=?)').bind('booking-event:'+id,'booking-event',b.id,JSON.stringify({bookingId:b.id,type:input.kind==='payment'?'booking.payment_received':'booking.refunded',actor:u.id,detail:payment}),now(),b.id,JSON.stringify(data))]);if(!r[0].meta.changes)throw Error('Booking changed. Refresh and retry.');await dispatchBookingEvents(b.id);return bookingView({...b,data});}

export async function amendBooking(input:any,u:any){return applyAmendment(input,u,await accessibleBooking(input.id,u));}
async function applyAmendment(input:any,u:any,b:any){if(b.data.invoice)throw Error('This booking has an invoice. Contact finance before changing its date or price.');if(!['pending','test-confirmed','unscheduled'].includes(b.status))throw Error('This booking cannot be amended');if(!clean(input.reason))throw Error('Explain the booking change');const q=await priceBooking({...b.data.pricingInput,tour:b.tour,date:input.date,...(input.guests===b.guests?b.data.party||{guests:input.guests}:{guests:input.guests}),currency:b.data.currency,bookingType:b.data.bookingType||'DIRECT',partnerId:b.data.partnerId},u,b.id);const data={...b.data,party:{adults:q.adults,children:q.children,infants:q.infants},deposit:q.deposit,commission:q.commission,commissionRate:q.commissionRate,commissionBasis:q.total,commissionRule:q.commissionRule,unit:q.unit,breakdown:q.breakdown,revision:crypto.randomUUID(),updated:now(),gift:b.data.gift?{...b.data.gift,state:'redeemed',flexible:false}:null};const status=b.status==='unscheduled'?(q.bookingMode==='request'?'pending':'test-confirmed'):b.status;const r=await db().batch([db().prepare(`UPDATE bookings SET date=?,guests=?,total=?,status=?,data=? WHERE id=? AND data=? AND (SELECT COALESCE(SUM(guests),0) FROM bookings WHERE tour=? AND date=? AND id<>? AND ${active})+?<=?`).bind(input.date,q.guests,q.total,status,JSON.stringify(data),b.id,JSON.stringify(b.data),b.tour,input.date,b.id,q.guests,q.capacity),db().prepare('INSERT INTO records(id,kind,owner,data,created) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM bookings WHERE id=? AND data=?)').bind('booking-event:'+b.id+':'+data.revision,'booking-event',b.id,JSON.stringify({bookingId:b.id,type:b.status==='unscheduled'?'booking.confirmed':'booking.modified',actor:u.id,detail:{reason:clean(input.reason),before:{date:b.date,guests:b.guests,total:b.total},after:{date:input.date,guests:q.guests,total:q.total}}}),now(),b.id,JSON.stringify(data))]);if(!r[0].meta.changes)throw Error('Booking changed or capacity is unavailable. Refresh and retry.');await dispatchBookingEvents(b.id);return bookingView({...b,date:input.date,guests:q.guests,total:q.total,status,data});}

export async function updateBookingMetadata(input:any,u:any){if(u.role!=='admin')throw Error('Administrator access required.');const b=await accessibleBooking(input.id,u);const data={...b.data,guide:clean(input.guide,100),driver:clean(input.driver,100),language:['en','fr','es'].includes(input.language)?input.language:'en',country:clean(input.country,80),source:clean(input.source,100),revision:crypto.randomUUID(),updated:now()};const payload=JSON.stringify(data);const r=await db().batch([db().prepare('UPDATE bookings SET data=? WHERE id=? AND data=?').bind(payload,b.id,JSON.stringify(b.data)),db().prepare('INSERT INTO records(id,kind,owner,data,created) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM bookings WHERE id=? AND data=?)').bind('booking-event:'+b.id+':'+data.revision,'booking-event',b.id,JSON.stringify({bookingId:b.id,type:'booking.metadata_updated',actor:u.id,detail:{old:{guide:b.data.guide,driver:b.data.driver,language:b.data.language,country:b.data.country,source:b.data.source},new:{guide:data.guide,driver:data.driver,language:data.language,country:data.country,source:data.source}}}),now(),b.id,payload)]);if(!r[0].meta.changes)throw Error('Booking changed. Refresh and retry.');return data;}

async function linkHash(token:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token)))).map(v=>v.toString(16).padStart(2,'0')).join('');}
export async function issueBookingLink(input:any,u:any){const b=await accessibleBooking(input.id,u);if(b.data.partnerId)await partnerPermission(b.data.partnerId,u,['admin','booker','finance']);if(!['payment','gift'].includes(input.kind))throw Error('Choose payment or gift link');if(input.kind==='gift'&&!b.data.gift)throw Error('This booking is not a gift');if(b.status==='cancelled')throw Error('This booking is cancelled');const token=crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-',''),id='booking-link:'+await linkHash(token);const targetEmail=input.kind==='gift'?b.data.gift.recipient.email:clean(input.email,200).toLowerCase();if(!/^\S+@\S+\.\S+$/.test(targetEmail))throw Error('Provide the recipient email');const data={bookingId:b.id,kind:input.kind,purpose:input.purpose==='balance'?'balance':'deposit',targetEmail,expires:Date.now()+7*86400000,used:false,createdBy:u.id};await db().batch([db().prepare('INSERT INTO records(id,kind,owner,data,created) VALUES (?,?,?,?,?)').bind(id,'booking-link',b.id,JSON.stringify(data),now()),eventStatement(b,'booking.link_created',u.id,{kind:input.kind,targetEmail})]);return {token,expires:data.expires};}
async function authorizedLink(token:string,u:any){if(!/^[a-f0-9]{64}$/.test(token||''))throw Error('Booking link access required');const id='booking-link:'+await linkHash(token),r=await db().prepare("SELECT * FROM records WHERE id=? AND kind='booking-link'").bind(id).first<any>();if(!r)throw Error('Booking link access required');const d=JSON.parse(r.data);if(d.expires<Date.now()||d.targetEmail!==String(u.email||'').toLowerCase())throw Error('Booking link access required');const raw=await db().prepare('SELECT * FROM bookings WHERE id=?').bind(d.bookingId).first<any>();if(!raw||raw.status==='cancelled')throw Error('Booking link is no longer available');return {id,data:d,booking:parse(raw)};}
export async function bookingLinkInfo(token:string,u:any){const link=await authorizedLink(token,u),b=await bookingView(link.booking);const amount=link.data.purpose==='balance'?b.balanceDue:Math.min(b.balanceDue,Math.max(0,(b.data.deposit||0)-b.paid));return {reference:b.id,tour:b.tour,date:b.date,travelers:b.guests,kind:link.data.kind,used:link.data.used,expires:link.data.expires,...(link.data.kind==='payment'?{amount,total:b.total,currency:'EUR'}:{message:b.data.gift.message,scheduled:!!b.date}),testOnly:true};}
export async function useBookingLink(input:any,u:any){const link=await authorizedLink(input.token,u),b=link.booking;if(link.data.used)return {ok:true,reference:b.id,alreadyUsed:true};if(link.data.kind==='gift'){if(b.data.gift.state==='redeemed')return {ok:true,reference:b.id,alreadyUsed:true};if(!b.data.gift.flexible)throw Error('This gift already has a fixed travel date');const quote=await priceBooking({...b.data.pricingInput,tour:b.tour,date:input.date,...b.data.party,bookingType:'GIFT'},u,b.id);if(quote.total!==b.total)throw Error('Gift pricing has changed. Please contact the team before selecting this date.');await applyAmendment({id:b.id,date:input.date,guests:b.guests,reason:'Gift recipient selected travel date'},u,b);}else{const info=await bookingLinkInfo(input.token,u);if(!('total' in info))throw Error('Invalid payment link');if(input.expectedTotal!==info.total)throw Error('The price changed. Reload the payment summary.');if(info.amount>0)await applyPayment({id:b.id,kind:'payment',amount:info.amount,reason:'Simulated guest payment link',requestKey:link.id.slice(13)},u,b);}
 await db().prepare("UPDATE records SET data=json_set(data,'$.used',json('true'),'$.usedBy',?,'$.usedAt',?) WHERE id=?").bind(u.id,now(),link.id).run();return {ok:true,reference:b.id};}
