import {canonicalURL,ORIGIN} from './organic-core';
import {preservedSchema} from './schema-preservation';
export function socialImage(value:any){if(typeof value!=='string'||!value)return '';try{const u=new URL(value,'https://www.tangierexcursions.com');return u.protocol==='https:'&&!u.username&&!u.password?u.href:''}catch{return ''}}
export function visibleAnswers(presence:any,seo:any){const base=presence?.reviewed?presence:{summary:'',questions:[],sources:[],reviewer:'',updated:''};const questions=[...(base.questions||[])];if(seo?.status==='published')for(const q of seo.aeoQuestions||[])if(q.status==='published'&&q.answer&&!questions.some((x:any)=>x.question.trim().toLowerCase()===q.question.trim().toLowerCase()))questions.push({question:q.question,answer:q.answer});return {...base,questions,reviewed:!!(base.summary||questions.length)}}
export function contentSchemas(page:any,seo:any){const raw=seo?.status==='published'&&seo.schemaMode!=='preserve'?seo.schema:page.structured_data||[];const schemas:any[]=[];const prune=(v:any):any=>{if(!v||typeof v!=='object')return v;if(Array.isArray(v))return v.map(prune).filter(Boolean);if([v['@type']].flat().some(t=>['FAQPage','Review','AggregateRating','Offer',...(page.companyEntity?['Organization','TravelAgency']:[])].includes(t)))return null;return Object.fromEntries(Object.entries(v).filter(([k])=>!['aggregateRating','review','offers'].includes(k)).map(([k,x])=>[k,prune(x)]).filter(([,x])=>x!==null))};for(const item of raw||[])try{const value=prune(JSON.parse(preservedSchema(typeof item==='string'?item:JSON.stringify(item))));if(value)schemas.push(value)}catch{}const types=(v:any):string[]=>!v||typeof v!=='object'?[]:[...(Array.isArray(v['@type'])?v['@type']:[v['@type']]),...Object.values(v).flatMap(x=>Array.isArray(x)?x.flatMap(types):types(x))].filter(Boolean);if(page.kind==='article'&&!schemas.some(x=>types(x).some(t=>['Article','BlogPosting','NewsArticle'].includes(t)))){const e=page.editorial||{},url=seo?.status==='published'?seo.canonical:page.url;schemas.push({'@context':'https://schema.org','@type':'BlogPosting','@id':url+'#article',url,mainEntityOfPage:url,headline:page.name,description:e.excerpt||page.meta?.description||'',...(socialImage(page.featuredImage||page.gallery?.[0])?{image:socialImage(page.featuredImage||page.gallery?.[0])}:{}),...(e.author?{author:{'@type':'Person',name:e.author}}:{}),...(e.published?{datePublished:e.published}:{})})}let url=page.url||ORIGIN+page.path;try{url=canonicalURL(seo?.status==='published'?seo.canonical||url:url)}catch{url=ORIGIN+page.path}
const company=page.companyEntity;
const walkTypes=(v:any,t:string):boolean=>!!v&&typeof v==='object'&&(v['@type']===t||Array.isArray(v['@type'])&&v['@type'].includes(t)||Object.values(v).some(x=>Array.isArray(x)?x.some(y=>walkTypes(y,t)):walkTypes(x,t)));
if(company&&!schemas.some(x=>walkTypes(x,'Organization'))){schemas.push({'@context':'https://schema.org','@type':'Organization','@id':'https://www.tangierexcursions.com/#organization',name:company.tradingName||'Tangier Excursions',url:company.website, ...(company.legalName?{legalName:company.legalName}:{}),...(company.phone?{telephone:company.phone}:{}),...(company.generalEmail?{email:company.generalEmail}:{}),...(company.logos?.primary?{logo:socialImage(company.logos.primary)}:{}),sameAs:[company.googleBusiness,company.tripadvisor,company.trustpilot].filter(Boolean)})}
if(!schemas.some(x=>walkTypes(x,'WebPage')))schemas.push({'@context':'https://schema.org','@type':'WebPage','@id':url+'#webpage',url,name:page.name,description:seo?.description||page.meta?.description||''});
if(page.path==='/'&&!schemas.some(x=>walkTypes(x,'WebSite')))schemas.push({'@context':'https://schema.org','@type':'WebSite','@id':url+'#website',url,name:company?.tradingName||'Tangier Excursions'});
if(page.kind==='tour'&&!schemas.some(x=>walkTypes(x,'Trip')))schemas.push({'@context':'https://schema.org','@type':'Trip',name:page.name,url,description:seo?.description||page.meta?.description||''});
if(page.destinationId&&!schemas.some(x=>walkTypes(x,'TouristDestination')))schemas.push({'@context':'https://schema.org','@type':'TouristDestination',name:page.name,url});
if(page.knowledge){for(let i=schemas.length-1;i>=0;i--)if(walkTypes(schemas[i],'BlogPosting'))schemas.splice(i,1);if(page.knowledge.schemaEligible)schemas.push({'@context':'https://schema.org','@type':'Article',headline:page.name,url,dateModified:page.updatedAt,...(page.knowledge.publicAttribution&&page.knowledge.author?{author:{'@type':'Person',name:page.knowledge.author}}:{})});}
const faq=[...(page.landing?.faqs||[]),...(page.presence?.questions||[]),...(!page.product?.golden?.hiddenSections?.includes('faqs')?(page.product?.golden?.faqs||[]).map((f:any)=>({question:f.question,answer:(f.answer||[]).map((b:any)=>b.text||'').join(' ')})):[])].filter((f:any,i:number,a:any[])=>a.findIndex(x=>x.question===f.question)===i);
if(faq.length&&!schemas.some(x=>walkTypes(x,'FAQPage')))schemas.push({'@context':'https://schema.org','@type':'FAQPage',mainEntity:faq.filter((f:any)=>f.question&&f.answer).map((f:any)=>({'@type':'Question',name:f.question,acceptedAnswer:{'@type':'Answer',text:f.answer}}))});
if(!schemas.some(x=>walkTypes(x,'BreadcrumbList'))&&page.path!=='/')schemas.push({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{name:'Home',item:'https://www.tangierexcursions.com/'},...(page.knowledge?[{name:'Travel Knowledge Hub',item:'https://www.tangierexcursions.com/knowledge/'}]:[]),{name:page.name,item:url}].map((v,i)=>({'@type':'ListItem',position:i+1,...v}))});
return schemas.map(x=>JSON.stringify(x).replace(/</g,'\\u003c'))}

export function schemaInspection(page:any,seo:any){const generated=contentSchemas(page,seo),types:string[]=[],errors:string[]=[],warnings:string[]=[];for(const source of (seo?.status==='published'&&seo.schemaMode!=='preserve'?seo.schema:page.structured_data)||[])try{JSON.parse(preservedSchema(typeof source==='string'?source:JSON.stringify(source)))}catch{errors.push('A source schema block contains invalid JSON and was excluded')}function visit(v:any){if(!v||typeof v!=='object')return;if(v['@type'])types.push(...[v['@type']].flat());if(v['@type']==='Offer'&&(!v.priceCurrency||v.price==null))errors.push('Offer requires a visible price and currency');if(v['@type']==='AggregateRating'&&(!v.ratingValue||!v.ratingCount&&!v.reviewCount))errors.push('Rating is incomplete');if(v['@type']==='FAQPage'&&!v.mainEntity?.length)errors.push('FAQ has no visible answers');for(const x of Object.values(v))if(Array.isArray(x))x.forEach(visit);else if(typeof x==='object')visit(x)}for(const raw of generated)try{visit(JSON.parse(raw))}catch{errors.push('Invalid JSON-LD')}if(!generated.length)warnings.push('No schema generated');if(types.includes('FAQPage'))warnings.push('FAQ schema describes visible content; no Google FAQ rich-result eligibility is claimed.');return {types:[...new Set(types)],json:generated.map(x=>JSON.parse(x)),errors,warnings,sources:['Existing SEO profile','Visible page content','Reviewed answers','Canonical company settings'],validation:'Local structural checks; not an external rich-results certification'}}
