import discoveryAudit from '@/migration/discovery-inventory-audit.json';
import {homeLayout} from './admin-content';
import {auditedTourRating} from './tour-rating';
import {db,editablePages,now,record} from './server';
import {clientSummary} from './client-summary';
import {kinds,normalize} from './discovery-engine';
const typeIcons:Record<string,string>={"Private Day Trips":"sun","Short Morocco Trips":"compass","Multi-Day Morocco Tours":"route","Shore Excursions":"ship","Desert Tours":"mountain","City Tours":"footprints","Private Transfers":"car","Custom Tours":"sparkles"};
export async function discoveryData(admin=false){
 const [records,links,pages,setting,prices,reviews]=await Promise.all([db().prepare('SELECT * FROM discovery_terms').all<any>(),db().prepare('SELECT tour,term FROM discovery_links').all<any>(),editablePages(),db().prepare("SELECT value FROM settings WHERE key='discovery-config'").first<any>(),db().prepare("SELECT key,value FROM settings WHERE key LIKE 'tour:%'").all<any>(),db().prepare("SELECT data FROM records WHERE kind='review'").all<any>()]);
 const config=setting?JSON.parse(setting.value):{social:[],footer:[],recommendations:[],sections:[]};const priceMap=Object.fromEntries(prices.results.map(r=>[r.key.slice(5),JSON.parse(r.value)]));
 const terms=records.results.map(r=>({...JSON.parse(r.data),id:r.id,kind:r.kind})).map(t=>({...t,icon:!t.iconCustomized&&t.kind==='type'?(typeIcons[t.name]||t.icon):t.icon})).filter(t=>admin||t.visible).sort((a,b)=>a.order-b.order);
 const tours=pages.filter(p=>p.kind==='tour'&&(admin||!p.draft)).map(p=>{const tiers=priceMap[p.path]?.tiers||p.pricing||[];const rr=reviews.results.map((r:any)=>JSON.parse(r.data)).filter((r:any)=>r.tour===p.path&&r.status==='published');const publishedRating=auditedTourRating(p.structured_data);const summary=clientSummary(p,tiers);if(!admin){summary.gallery=[summary.featuredImage||summary.image].filter(Boolean);if(summary.product)summary.product.media=[]}return {...summary,rating:rr.length?rr.reduce((sum:number,r:any)=>sum+r.rating,0)/rr.length:publishedRating?.rating||0,reviewCount:rr.length||publishedRating?.reviewCount||0,reviewLabel:rr.length?'reviews':publishedRating?.reviewLabel||'reviews',reviewSource:rr.length?'Verified booking reviews':publishedRating?.reviewSource||'',terms:links.results.filter(l=>l.tour===p.path).map(l=>l.term),price:tiers.length?Math.min(...tiers.map((x:any)=>x.price)):null,featured:config.recommendations.includes(p.path),bookingMode:p.product?.bookingMode||'enquiry'}});
 const auditHas=(path:string,id:string)=>discoveryAudit.links.some(l=>l.tour===path&&l.term===id);const recovery=Object.fromEntries([['day-trips','type-private-day-trips'],['short-trips','type-short-morocco-trips'],['multi-day','type-multi-day-morocco-tours']].map(([section,type])=>[section,tours.filter(t=>auditHas(t.path,type)&&(section!=='day-trips'||discoveryAudit.terms.some(x=>x.kind==='origin'&&x.country==='Spain'&&auditHas(t.path,x.id)))).map(t=>t.path)]));
 return {homepage:{...await homeLayout(),recovery},terms:terms.map(t=>({...t,...(!admin?{evidence:undefined,notes:undefined}:{}),tours:links.results.filter(l=>l.term===t.id&&tours.some(p=>p.path===l.tour)).map(l=>l.tour),count:tours.filter(p=>p.terms.includes(t.id)).length})),tours,config,landings:pages.filter(p=>p.kind!=='tour'&&!p.draft).map(p=>({path:p.path,name:p.name,kind:p.kind}))};
}
const text=(v:any,n=500)=>String(v||'').trim().slice(0,n);
function translated(value:any){return Object.fromEntries(['fr','es'].map(lang=>[lang,{name:text(value?.[lang]?.name,150),description:text(value?.[lang]?.description,2000),reviewed:value?.[lang]?.reviewed===true}]))}
export async function saveDiscovery(b:any,owner:string){
 const data=await discoveryData(true);
 if(b.action==='config'){
  const safeUrl=(v:any)=>{const s=text(v,1000);if(s.startsWith('/')&&!s.startsWith('//')&&!/[\\\s]/.test(s))return s;const u=new URL(s);if(u.protocol!=='https:'||u.username||u.password)throw new Error('Use a secure URL');return u.href};
  if(!Array.isArray(b.social)||b.social.length>30||!Array.isArray(b.footer)||b.footer.length>40)throw new Error('Invalid navigation');
  const value={social:b.social.map((s:any)=>({id:text(s.id),name:text(s.name,80),url:safeUrl(s.url),enabled:s.enabled!==false,newTab:s.newTab!==false})),footer:b.footer.map((s:any)=>({id:text(s.id),group:text(s.group,60),translations:translated(s.translations),name:text(s.name,80),url:safeUrl(s.url),enabled:s.enabled!==false})),recommendations:(b.recommendations||[]).filter((p:string)=>data.tours.some((t:any)=>t.path===p)),sections:(b.sections||[]).slice(0,20).map((s:any)=>({id:text(s.id),title:text(s.title,120),translations:translated(s.translations),kind:Object.hasOwn(kinds,s.kind)?s.kind:'destination',enabled:s.enabled!==false}))};
  await db().prepare('INSERT INTO settings(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('discovery-config',JSON.stringify(value)).run();await record('admin-log',owner,{action:'Discovery navigation updated',previous:data.config});return value;
 }
 if(b.action==='assign'){if(!data.tours.some((t:any)=>t.path===b.tour))throw new Error('Unknown tour');const ids=[...new Set<string>(b.terms||[])];if(ids.some(id=>!data.terms.some((t:any)=>t.id===id)))throw new Error('Unknown classification');await record('admin-log',owner,{action:'Tour classifications updated',target:b.tour,previous:data.tours.find((t:any)=>t.path===b.tour)?.terms});await db().batch([db().prepare('DELETE FROM discovery_links WHERE tour=?').bind(b.tour),...ids.map(id=>db().prepare('INSERT INTO discovery_links(id,tour,term) VALUES (?,?,?)').bind(crypto.randomUUID(),b.tour,id))]);return {ok:true}}
 const old=data.terms.find((t:any)=>t.id===b.id);
 if(b.action==='delete'){if(!old)throw new Error('Record not found');if(old.tours.length)throw new Error('Remove tour assignments before deleting this classification. Existing SEO pages are never deleted.');await record('admin-log',owner,{action:'Unused classification deleted',previous:old});await db().prepare('DELETE FROM discovery_terms WHERE id=?').bind(b.id).run();return {ok:true}}
 if(!Object.hasOwn(kinds,b.kind)||!text(b.name,100))throw new Error('Name and classification required');
 if(data.terms.some((t:any)=>t.id!==b.id&&t.kind===b.kind&&normalize(t.name)===normalize(text(b.name))))throw new Error('This classification already exists');
 if(old&&old.kind!==b.kind)throw new Error('Classification type cannot change');
 if(b.seoUrl&&!data.landings.some((p:any)=>p.path===b.seoUrl))throw new Error('Select an existing landing page');
 if(old&&old.seoUrl!==(b.seoUrl||'')&&!b.approveSeoChange)throw new Error('Confirm the existing SEO relationship change');
 const images=new Set(data.tours.flatMap((t:any)=>t.gallery));if(b.image&&!images.has(b.image)&&!/^\/media\/[\w-]+$/.test(b.image))throw new Error('Choose an existing or uploaded image');
 const tours=[...new Set<string>(b.tours||[])];if(tours.some(p=>!data.tours.some((t:any)=>t.path===p)))throw new Error('Unknown tour assignment');
 const id=old?.id||crypto.randomUUID(),value={id,kind:b.kind,name:text(b.name,100),translations:translated(b.translations),description:text(b.description,2000),image:text(b.image,1000),iconCustomized:true,icon:['map','compass','ship','car','camera','utensils','clock','route','sun','mountain','footprints','sparkles'].includes(b.icon)?b.icon:'map',country:text(b.country,100),seoUrl:text(b.seoUrl),visible:b.visible!==false,featured:!!b.featured,order:Number.isFinite(+b.order)?+b.order:0,transferAvailable:!!b.transferAvailable,transferDestination:text(b.transferDestination),transferDuration:text(b.transferDuration),distance:text(b.distance),notes:text(b.notes,2000),evidence:old?.evidence||[]};
 await db().batch([db().prepare('INSERT INTO discovery_terms(id,kind,data,updated) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated=excluded.updated').bind(id,b.kind,JSON.stringify(value),now()),db().prepare('DELETE FROM discovery_links WHERE term=?').bind(id),...tours.map(p=>db().prepare('INSERT INTO discovery_links(id,tour,term) VALUES (?,?,?)').bind(crypto.randomUUID(),p,id))]);
 await record('admin-log',owner,{action:'Discovery classification saved',target:id,previous:old||null});return value;
}
