export type RichBlock={text:string;html?:string;links?:{text:string;href:string}[]};
export type ItineraryStop={id:string;type:'time'|'day'|'stop';label:string;title:string;location:string;description:RichBlock[];duration:string;image:string;lat:number|null;lng:number|null;mapOrder:number;admission:boolean;meal:boolean;transport:boolean;note:string};
export const goldenSections=['overview','reviews','highlights','itinerary','included','map','cancellation','before','faqs'];
export const goldenLabels:Record<string,string>={overview:'Overview',reviews:'What Our Guests Say',highlights:'Highlights',itinerary:'Detailed Itinerary',included:'Included & Not Included',map:'Your Route',cancellation:'Cancellation Policy',before:'Before You Go',faqs:'Frequently Asked Questions'};
export function coverage(g:any,segments:any[]){const words=(s:string)=>s.toLowerCase().normalize('NFKC').match(/[\p{L}\p{N}]+/gu)||[];return segments.map(s=>{const candidate=JSON.stringify(g[s.field]||[]).toLowerCase();const available=new Set(words(candidate));const w=[...new Set(words(s.text))];const missing=w.filter(x=>!available.has(x));const lostLinks=(s.links||[]).filter((l:any)=>!candidate.includes(l.href.toLowerCase()));return {...s,confidence:w.length?Math.round(100*(w.length-missing.length)/w.length):100,missing:missing.slice(0,20),lostLinks,needsReview:missing.length>0||lostLinks.length>0}})}
export function effectiveGolden(g:any,shared:any){const copy=structuredClone(g);const blocks=(shared.blocks||[]).filter((b:any)=>g.reusableIds.includes(b.id));if(g.cancellation.mode==='global')copy.cancellation.body=shared.cancellation||[];copy.before=[...g.before,...blocks.filter((b:any)=>b.kind==='information').map((b:any)=>({id:b.id,title:b.title,icon:b.icon||'info',body:b.body}))];copy.faqs=[...g.faqs,...blocks.filter((b:any)=>b.kind==='faq').filter((b:any)=>!g.faqs.some((f:any)=>f.question.toLowerCase()===b.title.toLowerCase())).map((b:any)=>({id:b.id,question:b.title,answer:b.body}))];return copy}

export const translatedFields=['overview','facts','highlights','itinerary','included','excluded','optional','before','cancellation','faqs'];

export function emptyTourContent(path:string){return {version:2,path,status:'REVIEW REQUIRED',overview:[],facts:[],highlights:[],itineraryMode:'stop',timeFormat:'24',itinerary:[],included:[],excluded:[],optional:[],before:[],cancellation:{mode:'custom',body:[]},faqs:[],reusableIds:[],reviews:[],links:[],sectionOrder:[...goldenSections],hiddenSections:[],map:{enabled:false,pointsReviewed:false},migration:{segments:[],checks:{},notes:{},decisions:{},approvedAt:null}}}
