import {cleanRich,richPlain} from './rich-content';
import routePoints from '@/data/tour-route-points.json';
function withRoute(g:any){const points=(routePoints as any)[g.path];return points&&g.routePoints===undefined?{...g,routePoints:structuredClone(points),map:{...g.map,enabled:true}}:g}
import baseline from '@/data/golden-tour.json';
import experienceBaselines from '@/data/structured-experiences.json';
import catalog from '@/data/catalog.json';
import {db,now,record} from './server';
import {coverage,goldenSections,effectiveGolden,translatedFields,emptyTourContent} from './golden-model';
export const goldenPath=baseline.path;
const sharedDefaults={cancellation:[],blocks:[],maps:{provider:'openstreetmap',zoom:10,style:'standard',animate:true}};
async function value(key:string,fallback:any){const r=await db().prepare('SELECT value FROM settings WHERE key=?').bind(key).first<any>();return r?JSON.parse(r.value):structuredClone(fallback)}
export async function goldenContents(){const [saved,shared]=await Promise.all([db().prepare("SELECT key,value FROM settings WHERE key LIKE 'golden:%'").all<any>(),value('golden-shared',sharedDefaults)]);const all:any=structuredClone(experienceBaselines);for(const r of saved.results)all[r.key.slice(7)]=JSON.parse(r.value);return Object.fromEntries(Object.entries(all).map(([path,g]:any)=>[path,{...effectiveGolden(withRoute(g),shared),mapSettings:shared.maps}]))}
export async function goldenContent(path=goldenPath){return (await goldenContents())[path]}
export async function goldenAdmin(path=goldenPath){const product=await value('product:'+path,null);const base=(experienceBaselines as any)[path]||(product?emptyTourContent(path):null);if(!base)throw Error('Tour not found');const [g,shared,all]=await Promise.all([value('golden:'+path,base),value('golden-shared',sharedDefaults),goldenContents()]);return {tour:withRoute(g),shared,coverage:coverage(g,base.migration.segments),original:catalog.find(p=>p.path===path)?.content,inventory:catalog.filter(p=>p.kind==='tour').map(p=>({path:p.path,name:p.name,status:all[p.path]?.status||'REVIEW REQUIRED',checks:all[p.path]?.migration.checks||{}}))}}
const str=(v:any,max=15000)=>{if(typeof v!=='string'||v.length>max)throw Error('Invalid text field');return v};
const list=(v:any,max=100)=>{if(!Array.isArray(v)||v.length>max)throw Error('Invalid content list');return v};
const auditedLinks=new Set(Object.values(experienceBaselines).flatMap((g:any)=>g.migration.segments.flatMap((s:any)=>(s.links||[]).map((l:any)=>l.href))));
const link=(v:any)=>{if(typeof v!=='string'||!(/^(https:\/\/|tel:\+|\/(?!\/))/.test(v)||auditedLinks.has(v)))throw Error('Use a secure or existing local link');return v};
function blocks(v:any){return list(v).map((b:any)=>(b.html!==undefined?{html:cleanRich(b.html,true),text:richPlain(cleanRich(b.html,true)),links:[]}:{text:str(b.text),links:list(b.links||[]).map((l:any)=>({text:str(l.text,500),href:link(l.href)}))}))}
const media=(v:any)=>{if(!v)return '';if(!/^\/(wp-content\/uploads\/|media\/)[^<>]+$/.test(v))throw Error('Choose existing or uploaded media');return v};
function validateEvents(events:any){return list(events,100).map((s:any)=>{for(const k of ['lat','lng'])if(s[k]!=null&&(!Number.isFinite(s[k])||Math.abs(s[k])>(k==='lat'?85:180)))throw Error('Invalid event coordinates');return {...s,id:str(s.id,100),type:'time',label:str(s.label||'',100),title:str(s.title,300),location:str(s.location||'',300),description:blocks(s.description||[]),duration:str(s.duration||'',100),image:media(s.image),note:str(s.note||''),lat:s.lat??null,lng:s.lng??null,mapOrder:Number(s.mapOrder)||0}})}
function validate(g:any){if(typeof g.path!=='string')throw Error('Choose an existing experience.');g.routePoints=validateEvents(g.routePoints||[]);g.timeFormat=g.timeFormat==='12'?'12':'24';g.hiddenSections=list(g.hiddenSections||[]).filter((k:any)=>goldenSections.includes(k));for(const k of ['overview','highlights','included','excluded','optional'])g[k]=blocks(g[k]);g.facts=list(g.facts,12).map((f:any)=>({icon:str(f.icon,30),label:str(f.label,100),value:str(f.value,300)}));if(!['time','day','stop'].includes(g.itineraryMode))throw Error('Choose time, day or sequential itinerary');g.itinerary=list(g.itinerary,60).map((s:any)=>{for(const k of ['lat','lng'])if(s[k]!==null&&(!Number.isFinite(s[k])||Math.abs(s[k])>(k==='lat'?85:180)))throw Error('Invalid map coordinates');if(!['time','day','stop'].includes(s.type))throw Error('Invalid stop type');return {...s,id:str(s.id,100),title:str(s.title,300),label:str(s.label,100),location:str(s.location,300),description:blocks(s.description),note:str(s.note||''),duration:str(s.duration||'',100),image:media(s.image),events:validateEvents(s.events||[]),route:str(s.route||'',500),accommodation:str(s.accommodation||'',2000),meals:str(s.meals||'',1000),distance:str(s.distance||'',100),drivingTime:str(s.drivingTime||'',100),activities:str(s.activities||'',2000),mapOrder:Number(s.mapOrder)||0,admission:!!s.admission,meal:!!s.meal,transport:!!s.transport}});if(new Set(g.itinerary.flatMap((s:any)=>[s,...s.events]).map((s:any)=>s.id)).size!==g.itinerary.flatMap((s:any)=>[s,...s.events]).length)throw Error('Duplicate stop ID');g.before=list(g.before).map((b:any)=>({...b,id:str(b.id,100),title:str(b.title,200),icon:str(b.icon,30),body:blocks(b.body)}));g.faqs=list(g.faqs).map((f:any)=>({id:str(f.id,100),question:str(f.question,1000),answer:blocks(f.answer)}));g.cancellation={mode:g.cancellation.mode==='global'?'global':'custom',body:blocks(g.cancellation.body)};if(g.sectionOrder.length!==goldenSections.length||new Set(g.sectionOrder).size!==goldenSections.length||goldenSections.some(s=>!g.sectionOrder.includes(s)))throw Error('Retain every template section in the order list');g.map={enabled:!!g.map.enabled,pointsReviewed:!!g.map.pointsReviewed};g.reusableIds=list(g.reusableIds).map((s:any)=>str(s,100));g.links=list(g.links).map((l:any)=>({text:str(l.text,500),href:link(l.href)}));return g}
export async function saveGolden(b:any,owner:string,prepareOnly=false){const target=b.tour?.path||goldenPath;const before=await goldenAdmin(target).catch(e=>{if(prepareOnly)return {tour:emptyTourContent(target),shared:structuredClone(sharedDefaults)};throw e});const source=(experienceBaselines as any)[target]||emptyTourContent(target);if(b.action==='shared'){const s=b.shared;const maps=s.maps;if(!['openstreetmap','none'].includes(maps.provider)||!Number.isInteger(maps.zoom)||maps.zoom<7||maps.zoom>15||maps.style!=='standard')throw Error('Invalid map provider settings');const pages=(await db().prepare("SELECT value FROM settings WHERE key LIKE 'page:%'").all<any>()).results.map(r=>JSON.parse(r.value));const used=[...Object.values(await goldenContents()).flatMap((g:any)=>g.reusableIds||[]),...pages.flatMap(p=>[...(p.knowledge?.factIds||[]),...(p.landing?.factIds||[])])];if(used.some((id:string)=>!s.blocks.some((b:any)=>b.id===id)))throw Error('Remove tour references before deleting reusable information');const shared={cancellation:blocks(s.cancellation),blocks:list(s.blocks).map((x:any)=>({id:str(x.id,100),kind:x.kind==='faq'?'faq':'information',factKey:str(x.factKey||'',100),lastReviewed:/^\d{4}-\d{2}-\d{2}$/.test(x.lastReviewed||'')?x.lastReviewed:'',sourceURL:/^https:\/\//.test(x.sourceURL||'')?str(x.sourceURL,1000):'',scope:str(x.scope||'global',100),title:str(x.title,500),icon:str(x.icon||'info',30),body:blocks(x.body)})),maps:{provider:maps.provider,zoom:maps.zoom,style:'standard',animate:!!maps.animate}};if(new Set(shared.blocks.map(x=>x.id)).size!==shared.blocks.length)throw Error('Duplicate reusable information ID');await db().prepare('INSERT INTO settings(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('golden-shared',JSON.stringify(shared)).run();await record('admin-log',owner,{action:'Golden reusable information and maps saved',previous:before.shared});return shared}
const g=validate(structuredClone(b.tour));const translations:any={};for(const lang of ['fr','es']){const t=g.translations?.[lang];if(t){const c=validate({...g,...t.content,path:g.path,translations:{}});translations[lang]={reviewed:!!t.reviewed,content:Object.fromEntries(translatedFields.map(k=>[k,c[k]]))}}}g.translations=translations;if(JSON.stringify(g).length>180000)throw Error('Golden Tour content is too large');g.reviews=source.reviews;g.migration={...source.migration,decisions:g.migration?.decisions||{},approvedAt:null};g.status='REVIEW REQUIRED';if(b.action==='approve'){const resolved=effectiveGolden(g,before.shared);if(!resolved.cancellation.body.some((x:any)=>x.text.trim()))throw Error('Provide a reviewed cancellation policy before approval');if(!g.map.pointsReviewed&&g.map.enabled)throw Error('Review the proposed map coordinates before approval');for(const [key,status] of Object.entries(source.migration.checks))if(status==='REVIEW REQUIRED'&&!String(g.migration.decisions[key]||'').trim())throw Error('Record a review decision for '+key);for(const s of coverage(g,source.migration.segments).filter(x=>x.needsReview))if(!String(g.migration.decisions[s.id]||'').trim())throw Error('Review possible information loss: '+s.id);g.status='APPROVED';g.migration.approvedAt=now()}
g.updated=now();if(prepareOnly)return g;await db().prepare('INSERT INTO settings(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('golden:'+g.path,JSON.stringify(g)).run();await record('admin-log',owner,{action:b.action==='approve'?'Golden Tour approved for review':'Golden Tour saved',target:g.path,previous:before.tour});return g}
