import {db,now,escape,editablePages} from './server';
import {partnerPermission} from './partner-service';
import {listBookings,bookingView,accessibleBooking} from './booking-service';
import {companyDetails} from './company';
// Credit is derived from the canonical bookings and receipt ledger, never a second balance.
export const creditOutstandingSQL=`SELECT COALESCE(SUM(MAX(0,b.total-COALESCE((SELECT SUM(json_extract(p.data,'$.amount')) FROM records p WHERE p.kind='booking-payment' AND p.owner=b.id AND json_extract(p.data,'$.kind')='payment'),0))),0) FROM bookings b WHERE json_extract(b.data,'$.partnerId')=? AND json_extract(b.data,'$.invoice.number') IS NOT NULL AND b.status<>'cancelled'`;
export async function creditSummary(id:string,u:any){const p=await partnerPermission(id,u,['admin','finance']);const row=await db().prepare(creditOutstandingSQL).bind(id).first<any>();const outstanding=Number(Object.values(row||{})[0]||0),limit=p.data.creditEnabled?Number(p.data.creditLimit||0):null;return {outstanding,limit,available:limit==null?null:Math.max(0,limit-outstanding),currency:'EUR'}}
export async function invoiceTerms(partnerId:string,u:any){const p=await partnerPermission(partnerId,u,['admin','booker']);if(!p.data.invoiceEnabled||!p.data.paymentModes?.includes('invoice'))throw Error('Invoice terms are not enabled for this partner');const days=Number(p.data.paymentTermDays);if(!Number.isInteger(days)||days<0||days>120)throw Error('Invoice terms need administrator review');return {days,creditEnabled:!!p.data.creditEnabled,creditLimit:Number(p.data.creditLimit||0),billing:{name:p.data.name,address:p.data.address||'',country:p.data.country||'',taxId:p.data.taxId||'',information:p.data.billingInformation||''}}}
export function invoiceSnapshot(id:string,terms:any){const issuedAt=now();return {number:'TEST-INV-'+id,issuedAt,dueAt:new Date(Date.parse(issuedAt)+terms.days*86400000).toISOString(),termsDays:terms.days,billing:terms.billing,testOnly:true}}
export async function invoiceList(id:string,u:any){await partnerPermission(id,u,['admin','finance']);return (await listBookings(u)).filter(b=>b.data.partnerId===id&&b.data.invoice).map(invoiceProjection)}
export function invoiceProjection(b:any){const i=b.data.invoice;const status=b.status==='cancelled'?'cancelled':b.balanceDue===0?'paid':i.dueAt<now()?'overdue':b.paid>0?'partially-paid':'issued';return {booking:b.id,number:i.number,issuedAt:i.issuedAt,dueAt:i.dueAt,status,total:b.total,paid:b.total-b.balanceDue,outstanding:b.balanceDue,currency:'EUR',testOnly:true,billing:i.billing}}
export async function invoiceDocument(id:string,u:any){const raw=await accessibleBooking(id,u);if(!raw.data.invoice||!raw.data.partnerId)throw Error('Invoice unavailable');await partnerPermission(raw.data.partnerId,u,['admin','finance']);const b=await bookingView(raw),i=invoiceProjection(b),company=await companyDetails(),tour=(await editablePages()).find(p=>p.path===b.tour);const money=(v:number)=>'€'+(v/100).toFixed(2);return `<!doctype html><html><head><meta charset="utf-8"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(i.number)}</title><style>body{font:16px Rubik,Arial,sans-serif;color:#182a42;margin:32px auto;padding:24px;max-width:800px}img{width:220px}h1{font-size:28px}dl{display:grid;grid-template-columns:1fr 1fr;gap:16px}dd{margin:0;text-align:right}.note{background:#fff2cc;padding:16px}@media print{body{margin:0}}</style></head><body><img src="${escape(company.logos?.primary||'/assets/brand/primary.png')}" alt="Tangier Excursions"><h1>Development invoice</h1><p class="note">TEST DOCUMENT · No tax invoice issued and no payment collected. Legal tax configuration requires review before live use.</p><p>${escape(company.legalName||company.tradingName)}</p><h2>Bill to ${escape(i.billing.name)}</h2><p>${escape(i.billing.address)} · ${escape(i.billing.country)}</p><dl><dt>Number</dt><dd>${escape(i.number)}</dd><dt>Issued</dt><dd>${escape(i.issuedAt.slice(0,10))}</dd><dt>Due</dt><dd>${escape(i.dueAt.slice(0,10))}</dd><dt>Booking</dt><dd>${escape(b.id)}</dd><dt>Experience</dt><dd>${escape(tour?.name||b.tour)}</dd><dt>Total</dt><dd>${money(i.total)}</dd><dt>Receipts</dt><dd>${money(i.paid)}</dd><dt>Outstanding</dt><dd>${money(i.outstanding)}</dd><dt>Status</dt><dd>${i.status}</dd></dl></body></html>`}
