import {privateRoute,indexState} from './organic-core';
export const clientEvents=['web_vital','view_home','view_destination','view_landing_page','view_trip','view_article','view_page','view_gallery','view_itinerary','check_availability','select_date','select_travelers','view_price','add_extra','add_to_wishlist','share_whatsapp','share_email','copy_link','start_booking','custom_trip_started','payment_started'] as const;
export const businessEvents=['submit_enquiry','custom_trip_submitted','deposit_paid','booking_confirmed','booking_cancelled','refund_completed','review_submitted'] as const;
export const marketingDefaults={analyticsEnabled:true,retentionDays:90,utmTracking:true,firstTouch:true,lastTouch:true,debugTracking:false,seoSuffix:'Tangier Excursions',defaultSocialImage:'',landingNoindex:true};
export const publicPath=(v:any)=>typeof v==='string'&&!privateRoute(v)&&/^\/(?:[a-z0-9_-]+\/)*$/i.test(v)&&!/^\/(?:admin|api|account|checkout|cart|login|signup|verify|passengers|booking-workspace|booking-link)(?:\/|$)/.test(v)?v:null;
const token=(v:any)=>typeof v==='string'&&/^[a-zA-Z0-9 _.-]{1,100}$/.test(v)&&!/@|\b\d{7,}\b/.test(v)?v.trim():null;
export function acquisition(url:string,referrer:string,utm=true){let u:URL;try{u=new URL(url)}catch{return null}const path=publicPath(u.pathname);if(!path)return null;let host:string|null=null;try{const r=new URL(referrer);if(r.host!==u.host)host=r.hostname}catch{}const source=utm?token(u.searchParams.get('utm_source')):null;return {landing_page:path,referrer:host,source:source||host||'direct',medium:(utm?token(u.searchParams.get('utm_medium')):null)||(host?'referral':'none'),campaign:utm?token(u.searchParams.get('utm_campaign')):null,content:utm?token(u.searchParams.get('utm_content')):null,term:utm?token(u.searchParams.get('utm_term')):null,acquired:!!source||!!host};}
export function touches(previous:any,current:any,options:any=marketingDefaults){return {first:options.firstTouch?(previous?.first||current):null,last:options.lastTouch?(!previous?.last||current?.acquired?current:previous.last):null};}
export function eventContext(input:any){const out:any={};if(['LCP','INP','CLS'].includes(input?.metric)&&Number.isFinite(input?.value)&&input.value>=0&&input.value<=(input.metric==='CLS'?100:300000)&&['home','tour','destination','landing','knowledge','article','page'].includes(input?.template)){out.metric=input.metric;out.value=input.value;out.template=input.template;}for(const k of ['trip_id','destination_id','landing_page_id'])if(publicPath(input?.[k]))out[k]=input[k];for(const k of ['departure_city','trip_type'])if(token(input?.[k]))out[k]=token(input[k]);if(Number.isInteger(input?.party_size)&&input.party_size>0&&input.party_size<=999)out.party_size=input.party_size;return out;}
export function isSessionActive(s:any,stamp:number){return !!s&&Date.parse(s.last_seen)>stamp-30*60*1000;}
export function effectiveSEO(base:any,saved:any={}){return {...base,...saved,title:saved.title?.trim()||base.title,description:saved.description?.trim()||base.description,canonical:saved.canonical||base.canonical,openGraph:{...base.openGraph,...saved.openGraph,title:saved.openGraph?.title||saved.title||base.openGraph?.title,description:saved.openGraph?.description||saved.description||base.openGraph?.description,image:saved.openGraph?.image||base.openGraph?.image}};}
export const canIndex=(p:any,s:any)=>indexState(p,s).sitemap;
