export const ORIGIN='https://www.tangierexcursions.com';
export const privateRoute=(p:string)=>/^\/(?:admin|api|auth|account|login|signup|verify|checkout|cart|wishlist|passengers?|passenger-information|booking-link|booking-workspace|booking-confirmation|confirmation|review|review-qr|preview|test)(?:\/|$)/i.test(p)||/^\/partners\/portal(?:\/|$)/i.test(p);
export function canonicalURL(input:string){const u=new URL(input,ORIGIN);if(!['tangierexcursions.com','www.tangierexcursions.com'].includes(u.hostname)||u.protocol!=='https:'||u.username||u.password)throw Error('Canonical must use the Tangier Excursions HTTPS origin');u.hostname='www.tangierexcursions.com';u.hash='';u.search='';u.pathname=u.pathname.replace(/\/{2,}/g,'/');if(!/\.[a-z0-9]+$/i.test(u.pathname)&&!u.pathname.endsWith('/'))u.pathname+='/';return u.href}
export function indexState(p:any,s:any,query=''){let canonical:string;try{canonical=canonicalURL(s.canonical||p.path)}catch{return {status:'ERROR',index:false,follow:false,sitemap:false,canonical:''}}const hidden=privateRoute(p.path),search=p.path==='/search/'||/(?:^|[?&])(destination|duration|price|sort|filter|q)=/.test(query),draft=!!p.draft||s.status!=='published',alias=canonical!==ORIGIN+p.path,index=!hidden&&!search&&!draft&&s.index!==false&&!alias;return {status:draft?'DRAFT':hidden||search||s.index===false?'NOINDEX':alias?'CANONICALIZED':'INDEXABLE',index,follow:!hidden&&s.follow!==false,sitemap:index&&s.sitemap!==false,canonical}}
export const plain=(v:any)=>String(v||'').replace(/<[^>]*>/g,' ').replace(/&[a-z#0-9]+;/gi,' ').replace(/\s+/g,' ').trim();
export function pageText(p:any){return plain([p.editorialIntro||p.intro,p.content,p.editorial?.html,p.knowledge?.shortAnswer,p.knowledge?.detailedAnswer,...Object.values(p.product?.sections||{})].filter(Boolean).join(' '))}
export function fingerprint(text:string){const w=plain(text).toLowerCase().match(/[\p{L}\p{N}]+/gu)||[];return new Set(w.slice(0,15000).map((_,i)=>w.slice(i,i+5).join(' ')).filter(x=>x.split(' ').length===5))}
export function similarity(a:Set<string>,b:Set<string>){if(a.size<20||b.size<20)return 0;let same=0;for(const x of a)if(b.has(x))same++;return same/(a.size+b.size-same)}
export function landingQuality(p:any,s:any,others:any[]=[]){const l=p.landing||{},body=pageText(p),checks=[['Unique introduction',plain(p.editorialIntro||p.intro).length>=120&&!others.some(x=>x.path!==p.path&&plain(x.editorialIntro||x.intro)===plain(p.editorialIntro||p.intro))],['Useful traveler information',body.split(/\s+/).length>=120],['Relevant tours',p.editorial?.relatedTours?.length>0],['Destination context',l.destinations?.length>0],['Useful FAQs',l.faqs?.some((f:any)=>plain(f.question)&&plain(f.answer).length>=30)],['Internal links',l.links?.length>0||l.destinations?.length>0],['Meaningful image',!!(p.featuredImage||p.image)&&!!p.imageAlt],['SEO metadata',!!s.title&&!!s.description],['Self canonical',indexState({...p,draft:false},{...s,status:'published',index:true}).status==='INDEXABLE'],['No near-duplicate content',!others.some(x=>x.path!==p.path&&similarity(fingerprint(body),fingerprint(pageText(x)))>=0.8)]];return {ready:checks.every(x=>x[1]),checks:checks.map(([name,passed])=>({name,passed:!!passed})),schemaEligible:!!p.name&&!!body}}
export function validateRedirects(rules:any[],paths:Set<string>){const seen=new Set();for(const r of rules){if(![301,302,410].includes(Number(r.type)))throw Error('Use 301, 302 or 410');if(!/^\/(?!\/)[a-z0-9_./%-]*$/i.test(r.source)||privateRoute(r.source)||r.source.length>500||new URL(r.source,ORIGIN).pathname!==r.source||/%2f|%5c|%2e/i.test(r.source))throw Error('Use a public local source path without a query');if(!r.source.endsWith('/')&&!/\.[a-z0-9]+$/i.test(r.source))throw Error('Use the preferred trailing-slash source URL; extensionless aliases normalize there automatically');if(seen.has(r.source))throw Error('Duplicate or conflicting source: '+r.source);seen.add(r.source);if(r.type===410)continue;if(!/^\/(?!\/)[a-z0-9_./%-]*$/i.test(r.destination)||privateRoute(r.destination))throw Error('Use a public local destination');if(r.source===r.destination)throw Error('Self redirect');let target=r.destination;const visited=new Set([r.source]);for(let i=0;i<=rules.length;i++){if(visited.has(target))throw Error('Redirect loop');visited.add(target);const next=rules.find(x=>x.source===target);if(!next)break;if(next.type===410)throw Error('Redirect destination is retired');target=next.destination}if(rules.some(x=>x.source===r.destination))throw Error('Redirect chain: use the final destination directly');if(!paths.has(r.destination))throw Error('Redirect destination is not a published page');}return rules}
export function relationSuggestions(p:any,pages:any[]){const terms=new Set((p.taxonomy||[]).map((t:any)=>t.id)),related=new Set((p.related||[]).flatMap((r:any)=>[r.from,r.to]));return pages.filter(x=>x.path!==p.path&&!x.draft).map(x=>{const common=(x.taxonomy||[]).filter((t:any)=>terms.has(t.id)),explicit=related.has(x.path);return {path:x.path,name:x.name,type:x.type,weight:common.length+(explicit?5:0),reason:explicit?'Reviewed topic relationship':common.map((t:any)=>t.kind+': '+t.name).join(', ')}}).filter(x=>x.weight>0).sort((a,b)=>b.weight-a.weight).slice(0,8)}
export function incomingGraph(pages:any[]){const incoming=new Map<string,string[]>();for(const p of pages)for(const link of new Set<string>(p.outgoing||[])){if(!incoming.has(link))incoming.set(link,[]);incoming.get(link)!.push(p.path)}return pages.map(p=>({...p,incoming:incoming.get(p.path)||[],orphan:p.path!=='/'&&!(incoming.get(p.path)||[]).length}))}
export const reviewDays:Record<string,number>={Ferries:30,'Passports & Visas':30,Payments:60,Transportation:60,'Travel Planning':90,Families:180,Accessibility:90,'Culture & Etiquette':365,knowledge:90,tour:90,destination:180,landing:90,article:180,page:180};
export function reviewDue(p:any,overrides:any={}){const days=p.review?.intervalDays||overrides[p.knowledge?.category||p.type]||reviewDays[p.knowledge?.category||p.type]||180,last=p.review?.lastReviewed||p.knowledge?.lastReviewed,due=p.review?.nextReview||(last?new Date(Date.parse(last)+days*86400000).toISOString().slice(0,10):null);return {days,last:last||null,due,needsReview:!due||Date.parse(due)<Date.now()}}
export function parseMigration(csv:string){const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<csv.length;i++){const c=csv[i];if(c==='"'){if(quoted&&csv[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if(c==='\n'&&!quoted){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=c}if(quoted)throw Error('Unclosed CSV quote');if(cell||row.length){row.push(cell);rows.push(row)}const head=(rows.shift()||[]).map(x=>x.trim().toLowerCase());if(!['old url','new url','action','notes'].every(x=>head.includes(x)))throw Error('CSV headers: Old URL, New URL, Action, Notes');if(rows.length>2000)throw Error('Import up to 2,000 rows at a time');return rows.filter(r=>r.some(Boolean)).map(r=>{const get=(s:string)=>r[head.indexOf(s)]?.trim()||'',action=get('action').toLowerCase();if(!['keep unchanged','301 redirect','410 retire','review'].includes(action))throw Error('Invalid migration action');const local=(v:string)=>{if(!v)return '';const u=new URL(v,ORIGIN);if(!['tangierexcursions.com','www.tangierexcursions.com'].includes(u.hostname)||u.search||u.hash||privateRoute(u.pathname))throw Error('Use public Tangier URLs without query parameters');return u.pathname};return {source:local(get('old url')),destination:local(get('new url')),action,notes:get('notes').slice(0,500)}})}
