import {db,editablePages,now,escape,record} from './server';
import {cleanRich} from './rich-content';
import {ORIGIN,privateRoute,reviewDue,reviewDays} from './organic-core';
export async function organicSetting(key:string,fallback:any=null){const r=await db().prepare('SELECT value FROM settings WHERE key=?').bind(key).first<any>();return r?JSON.parse(r.value):fallback}
export async function organicSave(key:string,value:any){await db().prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(key,JSON.stringify(value)).run();return value}
const text=(v:any,n=500)=>String(v||'').trim().slice(0,n);
const date=(v:any)=>{if(!v)return '';if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v)))throw Error('Use a valid YYYY-MM-DD date');return v};
import {knowledgeCategories} from './organic-labels';
export {knowledgeCategories};
export async function knowledgeList(){return (await db().prepare("SELECT key,value FROM settings WHERE key LIKE 'page:/knowledge/%'").all<any>()).results.map(r=>({path:r.key.slice(5),...JSON.parse(r.value)})).filter(p=>p.knowledge)}
export async function saveKnowledge(b:any,owner:string){if(!/^\/knowledge\/[a-z0-9]+(?:-[a-z0-9]+)*\/$/.test(b.path))throw Error('Use /knowledge/your-question/');const previous=await organicSetting('page:'+b.path),pages=await editablePages();if(previous&&!previous.knowledge||!previous&&pages.some(p=>p.path===b.path))throw Error('URL already exists');const k=b.knowledge||{},name=text(b.name,250),shortAnswer=text(k.shortAnswer,2000),detailedAnswer=cleanRich(text(k.detailedAnswer,60000));if(!name||!shortAnswer)throw Error('Question and direct answer are required');if(!knowledgeCategories.includes(k.category))throw Error('Choose a knowledge category');const paths=(a:any)=>Array.isArray(a)?[...new Set<string>(a)].filter(p=>pages.some(x=>x.path===p&&!x.draft)&&p!==b.path).slice(0,20):[];const sources=(k.sources||[]).slice(0,20).map((s:any)=>{const url=new URL(s.url);if(url.protocol!=='https:'||url.username||url.password)throw Error('Use HTTPS source URLs');return {title:text(s.title,200),url:url.href,reviewed:date(s.reviewed),notes:text(s.notes,1000)}});const knowledge={shortAnswer,detailedAnswer,category:k.category,destinations:paths(k.destinations),departures:paths(k.departures),relatedTours:paths(k.relatedTours),relatedQuestions:paths(k.relatedQuestions),usefulLinks:paths(k.usefulLinks),author:text(k.author,120),reviewer:text(k.reviewer,120),publicAttribution:k.publicAttribution===true,lastReviewed:date(k.lastReviewed),sources,factIds:(k.factIds||[]).filter((id:any)=>typeof id==='string').slice(0,20),schemaEligible:k.schemaEligible!==false};const shared=await organicSetting('golden-shared',{blocks:[]});if(knowledge.factIds.some((id:string)=>!shared.blocks.some((b:any)=>b.id===id)))throw Error('Choose existing reusable information IDs');if(knowledge.lastReviewed&&Date.parse(knowledge.lastReviewed)>Date.now())throw Error('A completed review cannot be in the future');if(b.reviewed&&(!plainEnough(detailedAnswer)||!knowledge.lastReviewed||!knowledge.reviewer))throw Error('Publishing requires a detailed answer, reviewer and review date');const value={...previous,name,kind:'article',created:true,reviewed:b.reviewed===true,intro:shortAnswer,image:text(b.image,1000),imageAlt:text(b.imageAlt,300),knowledge,createdAt:previous?.createdAt||now(),updatedAt:now(),editorial:{html:detailedAnswer,quickAnswer:shortAnswer,category:k.category,relatedTours:knowledge.relatedTours,author:knowledge.publicAttribution?knowledge.author:'',published:previous?.editorial?.published||(b.reviewed?now():''),showPlanning:true}};if(value.image&&!/^\/(media|assets|wp-content)\//.test(value.image))throw Error('Use site media');await organicSave('page:'+b.path,value);await record('admin-log',owner,{action:'SEO knowledge article saved',target:b.path});return {path:b.path,...value}}
function plainEnough(s:string){return s.replace(/<[^>]*>/g,' ').trim().length>=150}
export async function organicEnrichPages(pages:any[]){const metadata=(await db().prepare("SELECT key,value FROM settings WHERE key LIKE 'seo-review:%' OR key='marketing:relationships' OR key='golden-shared'").all<any>()).results,map=Object.fromEntries(metadata.map(r=>[r.key,JSON.parse(r.value)])),relationships=map['marketing:relationships']||[],blocks=map['golden-shared']?.blocks||[];for(const p of pages){p.review=map['seo-review:'+p.path]||{};p.approvedLinks=relationships.filter((r:any)=>r.from===p.path&&r.publish===true).map((r:any)=>({...r,label:pages.find(x=>x.path===r.to&&!x.draft)?.name})).filter((r:any)=>r.label).slice(0,6);if(p.landing?.factIds?.length){const shared=blocks.filter((b:any)=>p.landing.factIds.includes(b.id));p.editorial={...p.editorial,html:(p.editorial?.html||'')+shared.map((b:any)=>'<h3>'+escape(b.title)+'</h3>'+b.body.map((v:any)=>'<p>'+escape(v.text||'')+'</p>').join('')).join('')};}if(p.knowledge){const k=p.knowledge;const factHTML=blocks.filter((b:any)=>k.factIds?.includes(b.id)).map((b:any)=>'<h3>'+escape(b.title)+'</h3>'+b.body.map((v:any)=>'<p>'+escape(v.text||'')+'</p>').join('')).join('');const links=[...k.relatedQuestions,...k.usefulLinks,...k.destinations,...k.departures].map((path:string)=>pages.find(p=>p.path===path&&!p.draft)).filter(Boolean);p.editorial={...p.editorial,html:k.detailedAnswer+factHTML+(links.length?'<h2>Related travel information</h2><ul>'+links.map((x:any)=>'<li><a href="'+escape(x.path)+'">'+escape(x.name)+'</a></li>').join('')+'</ul>':'')+(k.sources.length?'<h2>Sources and references</h2><ul>'+k.sources.map((s:any)=>'<li><a href="'+escape(s.url)+'" rel="noopener noreferrer">'+escape(s.title)+'</a>'+ (s.reviewed?' — checked '+escape(s.reviewed):'')+'</li>').join('')+'</ul>':'')+(k.lastReviewed?'<p>Last reviewed: <time datetime="'+escape(k.lastReviewed)+'">'+escape(k.lastReviewed)+'</time>'+(k.publicAttribution&&k.reviewer?' · Reviewed by '+escape(k.reviewer):'')+'</p>':'')};}}
const published=pages.filter(p=>p.knowledge&&!p.draft);if(published.length&&!pages.some(p=>p.path==='/knowledge/'))pages.push({path:'/knowledge/',name:'Travel Knowledge Hub',title:'Travel Knowledge Hub | Tangier Excursions',kind:'page',meta:{description:'Practical answers for planning your journey between Spain and Morocco.'},url:ORIGIN+'/knowledge/',canonical:[ORIGIN+'/knowledge/'],structured_data:[],images:[],gallery:[],internal_links:published.map(p=>p.path),pricing:[],content:'',editorial:{html:knowledgeCategories.map(c=>{const items=published.filter(p=>p.knowledge.category===c);return items.length?'<h2>'+escape(c)+'</h2><ul>'+items.map(p=>'<li><a href="'+escape(p.path)+'">'+escape(p.name)+'</a></li>').join('')+'</ul>':''}).join(''),relatedTours:[],showPlanning:false},draft:false});return pages}
export async function saveReview(b:any){const p=(await editablePages()).find(p=>p.path===b.path);if(!p)throw Error('Choose an existing page');const lastReviewed=date(b.lastReviewed),nextReview=date(b.nextReview),intervalDays=Number(b.intervalDays)||reviewDays[p.knowledge?.category||p.kind]||180;if(intervalDays<7||intervalDays>730)throw Error('Review interval must be 7–730 days');if(lastReviewed&&Date.parse(lastReviewed)>Date.now())throw Error('A completed review cannot be in the future');const hub=['','Topic Hub','Destination Hub','Departure City Hub','Experience Hub'].includes(b.hub)?b.hub:'';return organicSave('seo-review:'+b.path,{lastReviewed,nextReview,intervalDays,hub,reviewer:text(b.reviewer,120),updated:now()})}
export async function saveOrganicRelationship(b:any){const pages=await editablePages();if(!pages.some(p=>p.path===b.from)||!pages.some(p=>p.path===b.to)||b.from===b.to||privateRoute(b.from)||privateRoute(b.to))throw Error('Choose two public pages');const items=await organicSetting('marketing:relationships',[]),next=items.filter((r:any)=>r.from!==b.from||r.to!==b.to);if(!b.remove)next.push({from:b.from,to:b.to,type:['related','topic','parent','destination','departure','nearby'].includes(b.type)?b.type:'related',module:['Related Experiences','Explore This Destination','Traveling From…','Continue Your Morocco Journey','Useful Travel Information','Related Questions','Nearby Experiences'].includes(b.module)?b.module:'Useful Travel Information',publish:b.publish===true,updated:now()});await organicSave('marketing:relationships',next);return {ok:true}}
