import {canonicalURL,indexState,landingQuality,validateRedirects,privateRoute} from './organic-core';
import {marketingSettings} from './marketing';
import {effectiveSEO} from './marketing-core';
import {helpFAQs} from './travel-hub';
import {db,editablePages,now,record,rows} from './server';

const clean=(v:any,n=5000)=>String(v??'').trim().slice(0,n);
const list=(v:any,max=100)=>Array.isArray(v)?v.slice(0,max):[];
const validPath=(v:string)=>v==='/'||/^\/(?:[a-z0-9]+(?:-[a-z0-9]+)*\/)+$/.test(v);
const intents=['informational','commercial','transactional','navigational','local','mixed'];
const safeRobots=['index','noindex','follow','nofollow'];
const defaultRules:any={tour:{index:true,follow:true,sitemap:true},article:{index:true,follow:true,sitemap:true},page:{index:true,follow:true,sitemap:true},destination:{index:true,follow:true,sitemap:true},search:{index:false,follow:true,sitemap:false},system:{index:false,follow:false,sitemap:false}};

export interface AIService{
 suggestKeywords(context:any):Promise<any[]>;
 clusterKeywords(keywords:string[]):Promise<any[]>;
 classifyIntent(keyword:string):Promise<string>;
 suggestFAQ(context:any):Promise<any[]>;
 generateMeta(context:any):Promise<any[]>;
 generateTitle(context:any):Promise<any[]>;
 analyzeContent(context:any):Promise<any>;
 suggestInternalLinks(context:any):Promise<any[]>;
 createContentBrief(context:any):Promise<any>;
 generateAltText(context:any):Promise<string>;
}

const words=(s:string)=>clean(s,100000).toLowerCase().normalize('NFKD').replace(/[^a-z0-9\s-]/g,' ').split(/\s+/).filter(w=>w.length>2);
const titleCase=(s:string)=>s.replace(/\b\w/g,c=>c.toUpperCase());
function classify(keyword:string){const k=keyword.toLowerCase();if(/near me|in tangier|from (tarifa|seville|malaga|marbella|spain)/.test(k))return 'local';if(/book|price|cost|reserve|ticket/.test(k))return 'transactional';if(/best|tour|trip|experience|private/.test(k))return 'commercial';if(/how|what|when|where|why|can|do i|guide/.test(k))return 'informational';return 'mixed'}
function groundedSuggestions(seed:string,pages:any[]){const base=clean(seed,160).toLowerCase();const tokens=new Set(words(base));const related=pages.filter(p=>words(p.name+' '+(p.meta?.description||'')).some(w=>tokens.has(w))).slice(0,8);const suffix=['private tour','day trip','ferry tour','guided experience','travel guide','from Spain'];const ideas=[base,...suffix.map(x=>base+' '+x),...related.map(p=>p.name.toLowerCase())];return [...new Set(ideas.map(x=>x.replace(/\s+/g,' ').trim()))].filter(Boolean).slice(0,24).map((keyword,i)=>({keyword,intent:classify(keyword),source:i===0?'Seed keyword':'AI Suggested',metrics:null,pageType:/how|guide/.test(keyword)?'Blog Guide':/tour|trip|experience/.test(keyword)?'Tour':'Landing Page'}))}
export const GroundedAIService:AIService={
 async suggestKeywords(c){return groundedSuggestions(c.seed,c.pages)},
 async clusterKeywords(keys){const groups=new Map<string,string[]>();for(const k of keys){const key=/tarifa|seville|malaga|marbella|spain/.exec(k.toLowerCase())?.[0]||/chefchaouen|tangier|fes|rabat|casablanca/.exec(k.toLowerCase())?.[0]||classify(k);groups.set(key,[...(groups.get(key)||[]),k])}return [...groups].map(([topic,keywords])=>({topic:titleCase(topic),keywords,recommendation:'Use one strong page when search intent overlaps.'}))},
 async classifyIntent(k){return classify(k)},
 async suggestFAQ(c){return [`How does ${c.topic} work?`,`What is included with ${c.topic}?`,`How long does ${c.topic} take?`,`What should travelers bring for ${c.topic}?`].map(question=>({question,answer:'',status:'suggested'}))},
 async generateMeta(c){const name=clean(c.page.name,110);const description=clean(c.page.meta?.description||c.profile?.description||'',135);return [description,`Plan ${name} with Tangier Excursions. Review the itinerary, practical details and private booking options.`,`Explore ${name}. See what is included, journey information and how to arrange your private experience.`].filter(Boolean).map(text=>({text:clean(text,160),status:'draft',grounding:'Existing page data'}))},
 async generateTitle(c){const name=clean(c.page.name,58);return [name,`${name} | Tangier Excursions`,`${name} – Private Morocco Experience`].map(text=>({text:clean(text,65),status:'draft',grounding:'Existing page title'}))},
 async analyzeContent(c){return analyzePage(c.page,c.profile,c.links)},
 async suggestInternalLinks(c){return c.pages.filter((p:any)=>p.path!==c.page.path&&words(p.name).some(w=>words(c.page.name+' '+c.content).includes(w))).slice(0,8).map((p:any)=>({target:p.path,anchor:p.name,sourceSentence:'Choose a relevant sentence during editorial review.',reason:'Shared destination or journey topic',status:'suggested'}))},
 async createContentBrief(c){return {topic:c.topic,market:c.market,intent:classify(c.topic),h1:titleCase(c.topic),headings:['Overview','Who this experience suits','Journey and logistics','What is included','Practical questions'],questions:(await GroundedAIService.suggestFAQ(c)).map(x=>x.question),entities:[...new Set(words(c.topic).filter(w=>w.length>4))],status:'draft'}},
 async generateAltText(c){return clean(`${c.page.name} — ${c.image.caption||c.image.alt||'travel experience photograph'}`,180)}
};

function sourceProfile(page:any,defaults:any={}):any{const canonical=page.canonical?.[0]||page.url||('https://www.tangierexcursions.com'+page.path);const robots=String(page.meta?.robots||'');return {path:page.path,primaryKeyword:'',secondaryKeywords:[],intent:'mixed',title:page.landing||page.knowledge?`${page.name} | ${defaults.seoSuffix||'Tangier Excursions'}`:page.title||`${page.name} | ${defaults.seoSuffix||'Tangier Excursions'}`,description:page.meta?.description||'',slug:page.path,canonical,index:!page.landing&&!page.draft&&!robots.includes('noindex'),follow:!robots.includes('nofollow'),sitemap:true,maxSnippet:-1,maxImagePreview:'large',maxVideoPreview:-1,schemaMode:'preserve',schema:page.structured_data||[],openGraph:{title:page.meta?.['og:title']||page.title||page.name,description:page.meta?.['og:description']||page.meta?.description||'',image:page.featuredImage||page.gallery?.[0]||page.meta?.['og:image']||defaults.defaultSocialImage||''},twitter:{title:page.meta?.['twitter:title']||'',description:page.meta?.['twitter:description']||'',image:page.meta?.['twitter:image']||''},aeoQuestions:[],entities:[],protected:true,status:'published',source:'migration',updated:''}}
export async function seoProfile(path:string,page?:any,preloaded?:any,defaults?:any){page ||= (await editablePages()).find(p=>p.path===path);if(!page)throw Error('Choose an existing page.');defaults ||= await marketingSettings().catch(()=>({}));if(preloaded!==undefined)return effectiveSEO(sourceProfile(page,defaults),preloaded||{});const found=await db().prepare('SELECT key,value FROM settings WHERE key IN (?,?)').bind('seo:'+path,'presence:'+path).all<any>();const row=found.results.find((r:any)=>r.key==='seo:'+path),legacy=found.results.find((r:any)=>r.key==='presence:'+path);if(row)return {...effectiveSEO(sourceProfile(page,defaults),JSON.parse(row.value)),path};const base=sourceProfile(page,defaults);if(path==='/faqs/')base.aeoQuestions=(await helpFAQs(await editablePages())).map((f:any)=>({id:f.id,question:f.question,answer:f.shortAnswer,status:'published',shared:true}));if(legacy){const p=JSON.parse(legacy.value);base.aeoQuestions=(p.questions||[]).map((q:any)=>({...q,status:p.reviewed?'published':'reviewed'}));base.entities=[]}return base}
function contentHTML(page:any){return [page.name,page.meta?.description,page.editorialIntro,page.editorial?.html,page.content,Object.values(page.product?.sections||{}).join(' ')].filter(Boolean).join(' ')}
function textContent(page:any){return contentHTML(page).replace(/<[^>]*>/g,' ')}
function pageKind(page:any){if(['/search/','/checkout/','/cart/','/account/','/admin/','/wishlist/','/verify/'].includes(page.path))return 'system';return page.kind||'page'}
function linkInventory(page:any,pages:any[]){const html=contentHTML(page);const detected=[...html.matchAll(/href=["']([^"']+)/g)].map(m=>m[1]);const internal=[...new Set([...(page.internal_links||[]),...detected.filter(x=>x.startsWith('/'))])];const external=[...new Set(detected.filter(x=>/^https?:\/\//.test(x)&&!x.includes('tangierexcursions.com')))];return {internal,external,inbound:pages.filter(p=>(p.internal_links||[]).includes(page.path)).map(p=>p.path),broken:internal.filter(x=>!pages.some(p=>p.path===x)),orphan:page.path!=='/'&&!pages.some(p=>(p.internal_links||[]).includes(page.path))}}
function analyzePage(page:any,p:any,links:any){const text=textContent(page),h1=(contentHTML(page).match(/<h1\b/gi)||[]).length||1,h2=(contentHTML(page).match(/<h2\b/gi)||[]).length;const imgs=(page.images||page.gallery||[]);const checks=[
 ['critical','Indexing',p.index?'Indexable':'Noindex is active','Confirm noindex is intentional before publication.'],['critical','Canonical',!!p.canonical?'Canonical is present':'Canonical is missing','Provide one absolute canonical URL.'],['critical','Title',p.title?.length>=20&&p.title.length<=65?'Title length is usable':'Review title length','Write a concise title aligned with search intent.'],['recommended','Description',p.description?.length>=80&&p.description.length<=170?'Description length is usable':'Review meta description','Summarize the visible page without inventing offers.'],['recommended','Heading structure',h1===1?'One H1 detected':`${h1} H1 headings detected`,'Keep one descriptive H1 and logical H2/H3 sections.'],['recommended','Internal links',links.internal.length?`${links.internal.length} internal links`:'No internal links detected','Link to genuinely related tours, destinations or guides.'],['recommended','Images',imgs.length?`${imgs.length} images available`:'No image inventory','Use relevant optimized imagery and descriptive alt text.'],['optional','FAQ coverage',p.aeoQuestions?.length?`${p.aeoQuestions.length} reviewed answer candidates`:'No AEO questions saved','Add only genuine traveler questions with reviewed answers.'],['optional','Schema',p.schema?.length?'Structured data preserved':'No structured data detected','Add only schema that matches visible content.']];
 return {checks,wordCount:words(text).length};}

async function setting(key:string,fallback:any){const r=await db().prepare('SELECT value FROM settings WHERE key=?').bind(key).first<any>();return r?JSON.parse(r.value):fallback}
async function setSetting(key:string,value:any){await db().prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(key,JSON.stringify(value)).run()}

export async function seoAdmin(){const pages=await editablePages(),profiles:any={},analysis:any={},links:any={};for(const page of pages){profiles[page.path]=await seoProfile(page.path,page);links[page.path]=linkInventory(page,pages);analysis[page.path]=analyzePage(page,profiles[page.path],links[page.path])}const redirects=await setting('seo:redirects',[]),keywordMap=await setting('seo:keyword-map',[]),config=await setting('seo:config',{defaults:defaultRules,providers:{searchConsole:{connected:false},ga4:{connected:false},bing:{connected:false},rank:{connected:false}},verification:{},indexNow:{enabled:false},llms:{enabled:true,inclusions:[]},crawlers:{search:[],training:[]},reports:{enabled:false,frequency:'monthly'},automation:{sitemap:true,indexNow:false,reports:false,issueDetection:true},business:{}});const missed=await rows('seo-404');const history=(await rows('admin-log')).filter((r:any)=>String(r.data.action||'').startsWith('SEO')).slice(0,100);const measured=await setting('seo:measured-data',{searchConsole:[],analytics:[],rankings:[],updated:''});return {pages:pages.map(p=>({path:p.path,draft:!!p.draft,name:p.name,kind:pageKind(p),title:p.title,description:p.meta?.description||'',canonical:p.canonical?.[0]||p.url,migrated:!!p.product?.migrated||!!p.import_status,image:p.featuredImage||p.gallery?.[0]||'',schema:p.structured_data||[]})),profiles,analysis,links,redirects,keywordMap,config,missed,history,measured,capabilities:{keywordMetrics:config.providers?.rank?.connected||false,searchConsole:config.providers?.searchConsole?.connected||false,analytics:config.providers?.ga4?.connected||false,rankTracking:config.providers?.rank?.connected||false}}}

function validateProfile(b:any,current:any){
 const image=(v:any)=>{const value=clean(v,1000);if(!value)return '';try{const u=new URL(value,'https://www.tangierexcursions.com');if(u.protocol!=='https:'||u.username||u.password)throw Error();return value}catch{throw Error('Social images must use an HTTPS or local image URL.')}};
 const absolute=(v:string)=>{try{const u=new URL(v);return u.protocol==='https:'&&(u.hostname==='tangierexcursions.com'||u.hostname.endsWith('.tangierexcursions.com'))&&!u.username&&!u.password}catch{return false}};
 if(!absolute(b.canonical))throw Error('Canonical must be a Tangier Excursions HTTPS URL.');
 if(!intents.includes(b.intent))throw Error('Choose a supported search intent.');
 if(!safeRobots.includes(b.index?'index':'noindex')||!safeRobots.includes(b.follow?'follow':'nofollow'))throw Error('Invalid robots choice.');
 if(!validPath(current.path))throw Error('Existing URL is invalid.');
 const schemaMode=['preserve','template','custom'].includes(b.schemaMode)?b.schemaMode:'preserve';
 let schema:any[]=schemaMode==='preserve'?list(current.schema,30):[];
 if(schemaMode!=='preserve')for(const raw of list(b.schema,30)){const parsed=typeof raw==='string'?JSON.parse(raw):raw;if(!parsed||typeof parsed!=='object'||!parsed['@type']&&!parsed['@graph'])throw Error('Schema must be valid JSON-LD with @type or @graph.');schema.push(typeof raw==='string'?raw:JSON.stringify(parsed))}
 return {...current,primaryKeyword:clean(b.primaryKeyword,200),secondaryKeywords:[...new Set(list(b.secondaryKeywords,100).map((x:any)=>clean(x,200)).filter(Boolean))],intent:b.intent,title:clean(b.title,300),description:clean(b.description,500),canonical:canonicalURL(b.canonical),index:!!b.index,follow:!!b.follow,sitemap:!!b.sitemap,maxSnippet:Number.isInteger(+b.maxSnippet)?+b.maxSnippet:-1,maxImagePreview:['none','standard','large'].includes(b.maxImagePreview)?b.maxImagePreview:'large',maxVideoPreview:Number.isInteger(+b.maxVideoPreview)?+b.maxVideoPreview:-1,schemaMode,schema,openGraph:{title:clean(b.openGraph?.title,300),description:clean(b.openGraph?.description,500),image:image(b.openGraph?.image)},twitter:{title:clean(b.twitter?.title,300),description:clean(b.twitter?.description,500),image:image(b.twitter?.image)},aeoQuestions:list(b.aeoQuestions,30).map((q:any)=>({question:clean(q.question,300),answer:clean(q.answer,3000),status:['suggested','reviewed','published'].includes(q.status)?q.status:'suggested'})).filter((q:any)=>q.question),entities:[...new Set(list(b.entities,100).map((x:any)=>clean(x,100)).filter(Boolean))],protected:b.protected!==false,status:['draft','review','published'].includes(b.status)?b.status:'review',source:current.source,updated:now()}
}
export async function saveSeo(b:any,owner:string){const page=(await editablePages()).find(p=>p.path===b.path);if(!page)throw Error('Choose an existing page.');const current=await seoProfile(b.path,page),next=validateProfile(b,current);if(next.index&&next.status==='published'&&page.landing){const quality=landingQuality(page,next,await editablePages());if(!quality.ready)throw Error('Publication readiness: '+quality.checks.filter(c=>!c.passed).map(c=>c.name).join(', '));}const sensitive=current.protected&&(current.index&&!next.index||current.canonical!==next.canonical||current.title!==next.title&&b.majorChange);if(sensitive&&b.confirmProtected!==true)throw Error('SEO protected: confirm this change after reviewing organic-performance risk.');await setSetting('seo:'+b.path,next);await record('admin-log',owner,{action:'SEO page profile updated',target:b.path,previous:current,next:{...next,schema:next.schema.length+' items'}});return next}
export async function keywordResearch(b:any){const pages=await editablePages(),seed=clean(b.seed,160);if(!seed)throw Error('Enter a seed keyword.');const suggestions=await GroundedAIService.suggestKeywords({seed,pages,market:clean(b.market,60),language:clean(b.language,30)});const clusters=await GroundedAIService.clusterKeywords(suggestions.map(x=>x.keyword));const existing=pages.map(p=>({path:p.path,name:p.name,score:words(seed).filter(w=>words(p.name+' '+(p.meta?.description||'')).includes(w)).length})).filter(x=>x.score).sort((a,b)=>b.score-a.score).slice(0,8);return {seed,market:clean(b.market,60)||'Worldwide',language:clean(b.language,30)||'English',suggestions,clusters,existing,notice:'Suggestions are grounded in the current site inventory. No search volume, CPC, competition or ranking data is claimed without a configured provider.'}}
export async function aiDraft(b:any){const page=(await editablePages()).find(p=>p.path===b.path);if(!page)throw Error('Choose an existing page.');const profile=await seoProfile(b.path,page),pages=await editablePages(),links=linkInventory(page,pages),context={page,profile,pages,links,content:textContent(page),topic:clean(b.topic||profile.primaryKeyword||page.name,200),market:clean(b.market||'Worldwide',60)};if(b.task==='titles')return {drafts:await GroundedAIService.generateTitle(context)};if(b.task==='meta')return {drafts:await GroundedAIService.generateMeta(context)};if(b.task==='faq')return {drafts:await GroundedAIService.suggestFAQ(context)};if(b.task==='links')return {drafts:await GroundedAIService.suggestInternalLinks(context)};if(b.task==='brief')return {draft:await GroundedAIService.createContentBrief(context)};if(b.task==='analysis')return await GroundedAIService.analyzeContent(context);throw Error('Unknown AI task')}
export async function saveSeoCollection(b:any,owner:string){const data=await seoAdmin();if(b.kind==='keyword-map'){const value=list(b.items,1000).map((x:any)=>({keyword:clean(x.keyword,200),variations:list(x.variations,30).map((v:any)=>clean(v,200)),url:clean(x.url,1000),tracked:!!x.tracked,country:clean(x.country,40),device:['desktop','mobile'].includes(x.device)?x.device:'desktop'})).filter((x:any)=>x.keyword&&data.pages.some((p:any)=>p.path===x.url));await setSetting('seo:keyword-map',value);await record('admin-log',owner,{action:'SEO keyword map updated',target:'Keyword map',previous:data.keywordMap});return value}
 if(b.kind==='redirects'){const value=list(b.items,1000).map((x:any)=>({id:clean(x.id||crypto.randomUUID(),100),source:clean(x.source,1000),destination:clean(x.destination,1000),type:[301,302,307,410].includes(+x.type)?+x.type:301,reason:clean(x.reason,300),hits:Number(x.hits)||0,created:x.created||now(),lastAccessed:x.lastAccessed||''}));validateRedirects(value,new Set(data.pages.filter((p:any)=>!p.draft).map((p:any)=>p.path)));await setSetting('seo:redirects',value);await record('admin-log',owner,{action:'SEO redirects updated',target:'Redirect manager',previous:data.redirects});return value}
 if(b.kind==='config'){const c=b.value||{};const value={...data.config,...c,defaults:{...defaultRules,...c.defaults},providers:{...data.config.providers,...c.providers},updated:now()};await setSetting('seo:config',value);await record('admin-log',owner,{action:'SEO platform settings updated',target:'SEO settings',previous:data.config});return value}
 throw Error('Unknown SEO collection')}
export async function bulkSeo(b:any,owner:string){const paths=list(b.paths,500),changes=b.changes||{};const results=[];for(const path of paths){const current=await seoProfile(path);if(current.protected&&(['index','canonical','title'].some(k=>Object.hasOwn(changes,k)))&&b.confirmProtected!==true)throw Error('Protected pages require confirmation.');results.push(await saveSeo({...current,...changes,path,confirmProtected:b.confirmProtected},owner))}return results}
export async function record404(path:string,referrer='',agent=''){if(!/^\/(?!\/)[a-z0-9_./%-]{0,250}$/i.test(path)||privateRoute(path)||/\d{7,}|%40|@|\.(php|env|git)/i.test(path))return;let host='';try{host=new URL(referrer).hostname}catch{}const stamp=now(),id='seo404:'+path;await db().prepare("INSERT INTO records(id,kind,owner,data,created) VALUES(?,'seo-404','anonymous',?,?) ON CONFLICT(id) DO UPDATE SET data=json_set(records.data,'$.hits',COALESCE(json_extract(records.data,'$.hits'),0)+1,'$.lastSeen',?)").bind(id,JSON.stringify({url:path,referrer:host,firstSeen:stamp,lastSeen:stamp,hits:1,status:'open',noise:/bot|spider|crawler/i.test(agent)}),stamp,stamp).run()}
export async function sitemapPages(kind?:string){const {contentRegistry}=await import('./marketing-content');const registry=await contentRegistry(false);return registry.filter((p:any)=>p.sitemap&&(!kind||p.type===kind)).map((p:any)=>({url:p.canonical,lastModified:p.modified&&/^\d{4}-/.test(p.modified)?p.modified:undefined,images:p.image?[p.image]:[]}));}
export async function llmsText(){const data=await seoAdmin();if(data.config.llms?.enabled===false)return '';const selected=data.config.llms?.inclusions?.length?data.config.llms.inclusions:data.pages.filter((p:any)=>['tour','article','page'].includes(p.kind)&&data.profiles[p.path].index).slice(0,35).map((p:any)=>p.path);const lines=['# Tangier Excursions','> Private journeys between southern Spain and Morocco. Canonical resources selected for factual discovery.',''];for(const path of selected){const p=data.pages.find((x:any)=>x.path===path);if(p&&data.profiles[path]?.index)lines.push(`- [${p.name}](${data.profiles[path].canonical}): ${clean(data.profiles[path].description,220)}`)}return lines.join('\n')+'\n'}
