import {organicEnrichPages} from './organic-content';
import {landingHTML} from './marketing-content';
import {customerIdentity} from './customer-auth';
import {canAdminOperation,staffRoles} from './admin-permissions';
import {aboutDocument} from './about-cms';
import {hubPages,virtualPage,destinationPages} from './travel-hub';
import {tourModels} from './tour-cms';
import {env} from 'cloudflare:workers';
import {cookies} from 'next/headers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {defaults,baseTiers,pages,Tier,logo} from './model';
export const db=()=>{if(!env.DB)throw new Error('The test database is unavailable.');return env.DB;};
export const now=()=>new Date().toISOString();
export const testMode=()=>!!import.meta.env.DEV;
export async function identity(){const u=await getChatGPTUser();if(u){const ids=((env as any).ADMIN_USER_IDS||'').split(',');const staff=await db().prepare('SELECT value FROM settings WHERE key=?').bind('staff').first<{value:string}>();if(staff)ids.push(...JSON.parse(staff.value));
// Enable only for the verified owner-private test Site. Bind once to its first
// authenticated owner; later visitors never inherit administrator privileges.
if((env as any).PRIVATE_PREVIEW_OWNER_BOOTSTRAP==='true'){
 await db().prepare('INSERT OR IGNORE INTO settings (key,value) VALUES (?,?)').bind('private-preview-owner',JSON.stringify(u.userId)).run();
 const owner=await db().prepare('SELECT value FROM settings WHERE key=?').bind('private-preview-owner').first<{value:string}>();
 if(owner&&JSON.parse(owner.value)===u.userId)ids.push(u.userId);
}
const roles=await db().prepare("SELECT value FROM settings WHERE key='staff-roles'").first<any>();const assigned=roles?JSON.parse(roles.value)[u.userId]:null;return {id:u.userId,name:u.displayName,email:u.email,role:ids.includes(u.userId)?'admin':staffRoles.includes(assigned)?assigned:'customer'};}const customer=await customerIdentity();if(customer)return customer;if(testMode()){const token=(await cookies()).get('te_test_session')?.value;if(token){const s=await db().prepare('SELECT * FROM sessions WHERE token=? AND expires>?').bind(token,Date.now()).first<any>();if(s)return {id:s.owner,name:s.role==='admin'?'Preview administrator':'Preview traveler',email:'traveler@example.test',role:s.role};}}return null;}
export async function requireUser(admin=false){const u=await identity();if(!u)throw new Error('Please sign in to continue.');if(admin&&u.role!=='admin')throw new Error('Administrator access required.');return u;}
export async function config(){const r=await db().prepare('SELECT value FROM settings WHERE key=?').bind('config').first<{value:string}>();return {...defaults,...(r?JSON.parse(r.value):{})};}
export async function tourConfig(path:string){const r=await db().prepare('SELECT value FROM settings WHERE key=?').bind('tour:'+path).first<{value:string}>();const p=(await editablePages()).find(p=>p.path===path);if(!p)throw new Error('Tour not found');return {tiers:baseTiers(p),blackouts:[],capacity:99,...(r?JSON.parse(r.value):{}),bookingMode:p.product?.bookingMode||'instant',status:p.product?.status||'published'};}
export async function record(kind:string,owner:string,data:any,id=crypto.randomUUID()){await db().prepare('INSERT INTO records (id,kind,owner,data,created) VALUES (?,?,?,?,?)').bind(id,kind,owner,JSON.stringify(data),now()).run();return id;}
export async function rows(kind:string,owner?:string){const q=owner?db().prepare('SELECT * FROM records WHERE kind=? AND owner=? ORDER BY created DESC').bind(kind,owner):db().prepare('SELECT * FROM records WHERE kind=? ORDER BY created DESC').bind(kind);return (await q.all<any>()).results.map(r=>({...r,data:JSON.parse(r.data)}));}
export function escape(s:any){return String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]!));}
export async function emailHTML(name:string,data:any){return (await import('./branded-email')).brandedEmail(name,data)}
export async function queueEmail(name:string,owner:string,data:any,id?:string){const email=await emailHTML(name,data);return record('email',owner,{...email,to:data.email||'',status:'test-outbox',template:name},id);}
export async function editablePages(){const data=(await db().prepare("SELECT key,value FROM settings WHERE key LIKE 'page:%'").all<any>()).results;const list:any[]=pages.map(p=>({...p}));for(const r of data){const path=r.key.slice(5),v=JSON.parse(r.value),i=list.findIndex(p=>p.path===path);if(i>=0){if(v.reviewed)list[i]={...list[i],name:v.name||list[i].name,editorialIntro:v.intro,editorial:v.landing?landingHTML(v):v.editorial,landing:v.landing,knowledge:v.knowledge,createdAt:v.createdAt,updatedAt:v.updatedAt,featuredImage:v.image||undefined,imageAlt:v.imageAlt||'',gallery:v.image?[v.image,...list[i].gallery.filter((u:string)=>u!==v.image)]:list[i].gallery,duration:v.duration,category:v.category};}else if(v.created){list.push({path,name:v.name,kind:v.kind,gallery:v.image?[v.image]:[],content:'',editorialIntro:v.intro,editorial:v.landing?landingHTML(v):v.editorial,landing:v.landing,knowledge:v.knowledge,createdAt:v.createdAt,updatedAt:v.updatedAt,featuredImage:v.image||undefined,imageAlt:v.imageAlt||'',meta:{description:v.intro?.slice(0,160)||''},title:v.name,url:'https://www.tangierexcursions.com'+path,canonical:[],structured_data:[],images:[],internal_links:[],pricing:[],import_status:'New preview content',draft:!v.reviewed,duration:v.duration,category:v.category});}}for(const p of [...hubPages.map(virtualPage),...await destinationPages()])if(!list.some(x=>x.path===p.path))list.push(p);const models=await tourModels();for(const [path,product] of Object.entries(models)){let i=list.findIndex(p=>p.path===path);if(i<0){list.push({path,kind:'tour',name:product.name,title:product.seo.title,meta:{description:product.seo.description},url:'https://www.tangierexcursions.com'+path,canonical:[],structured_data:[],images:[],internal_links:[],pricing:[],content:'',gallery:[],draft:true});i=list.length-1;}list[i]={...list[i],name:product.updated==='Migration baseline'?list[i].name:product.name,duration:product.duration,featuredImage:product.featuredImage,imageAlt:product.media.find((m:any)=>m.url===product.featuredImage)?.alt||product.name,gallery:product.media.map((m:any)=>m.url),product,draft:!product.migrated&&product.status!=='published'};}const about=list.find(p=>p.path==='/about-us/');if(about){const story=await aboutDocument();about.content=story.sections.filter((s:any)=>s.enabled).map((s:any)=>'<'+(s.type==='hero'?'h1':'h2')+'>'+escape(s.heading)+'</'+(s.type==='hero'?'h1':'h2')+'>'+s.body).join('');about.internal_links=[...new Set([...about.internal_links,...story.sections.flatMap((s:any)=>[s.ctaUrl,s.secondaryCtaUrl]).filter((v:string)=>v.startsWith('/'))])];}return organicEnrichPages(list);}
export async function applyCoupon(price:any,code:any,date:string){if(!code)return price;const value=await db().prepare('SELECT value FROM settings WHERE key=?').bind('coupons').first<any>();const coupon=(value?JSON.parse(value.value):[]).find((c:any)=>c.code===String(code).trim().toUpperCase()&&c.active!==false);if(!coupon||coupon.expires&&date>coupon.expires)throw new Error('This promotional code is not available for your travel date.');const discount=Math.min(price.total,Math.round(coupon.type==='percent'?price.total*coupon.value/100:coupon.value*100));return {...price,total:price.total-discount,unit:Math.round((price.total-discount)/price.guests),coupon:coupon.code,breakdown:[...price.breakdown,{label:'Promotion '+coupon.code,amount:-discount}]};}

export async function requireStaffFor(op:string){const u=await requireUser();if(!canAdminOperation(u.role,op))throw Error('Staff access required for this action.');return {...u,staffRole:u.role,role:'admin'};}
