import {validateOperations} from './booking-operations';
import {emptyTourContent} from './golden-model';
import {goldenContents,goldenPath} from './golden-server';
import organizedDiscovery from '@/data/discovery-content.json';
import catalog from '@/data/catalog.json';
import baseline from '@/data/structured-tours.json';
import {db,now} from './server';
export async function tourModels(){const all:Record<string,any>=Object.fromEntries(Object.entries(baseline).map(([path,t])=>[path,{...t,sections:(organizedDiscovery as any)[path]||t.sections}]));const saved=await db().prepare("SELECT key,value FROM settings WHERE key LIKE 'product:%'").all<any>();for(const r of saved.results)all[r.key.slice(8)]={...all[r.key.slice(8)],...JSON.parse(r.value)};const metadata=await db().prepare("SELECT key,value FROM settings WHERE key LIKE 'media-meta:%'").all<any>();const mm=Object.fromEntries(metadata.results.map(r=>[r.key.slice(11),JSON.parse(r.value)]));for(const path of Object.keys(all))all[path]={...all[path],media:all[path].media.map((m:any)=>({...m,...mm[m.url]}))};const content=await goldenContents();for(const path of Object.keys(all)){all[path].golden=content[path]||emptyTourContent(path);if(!all[path].operations)all[path].operations={ferryIncluded:all[path].golden.included.some((b:any)=>/round[ -]trip ferry tickets/i.test(b.text)),suppliers:[]};if(!all[path].related?.length)all[path].related=content[path]?.migration?.relatedPaths||[];}return all;}
const text=(s:any,n=20000)=>String(s??'').trim().slice(0,n);
export async function saveTour(b:any,trustedCopy?:any,prepareOnly=false){const all=await tourModels();const original=all[b.originalPath||b.path];const migrated=(baseline as any)[b.path]||(baseline as any)[b.originalPath];if(!all[b.path]&&(catalog.some(p=>p.path===b.path)||['/admin/','/account/','/verify/','/wishlist/','/search/'].includes(b.path)||b.path.startsWith('/admin/')))throw new Error('This URL is reserved');if(migrated&&b.path!==(b.originalPath||b.path))throw new Error('Existing SEO Asset: migrated URLs are locked in this development phase. No redirect was created.');if(!/^\/(?:[a-z0-9]+(?:-[a-z0-9]+)*\/)+$/.test(b.path))throw new Error('Use a valid local tour URL ending in /.');if(!text(b.name,300))throw new Error('A tour name is required');if(!original&&all[b.path])throw new Error('This URL already exists');if(!['published','draft','archived'].includes(b.status))throw new Error('Invalid tour status');if(!['instant','request','enquiry','custom'].includes(b.bookingMode))throw new Error('Invalid booking mode');if(migrated&&b.status!=='published')throw new Error('Migrated indexed pages must remain published. Disable booking instead.');if(!Array.isArray(b.media)||b.media.length>100)throw new Error('Invalid gallery');const known=new Set(Object.values(baseline).flatMap((t:any)=>t.media.map((m:any)=>m.url)));for(const m of b.media){if(!known.has(m.url)&&!/^\/media\/[\w-]+$/.test(m.url))throw new Error('Choose audited or uploaded media');}if(b.featuredImage&&!b.media.some((m:any)=>m.url===b.featuredImage))throw new Error('Featured image must belong to the gallery');if(!Array.isArray(b.journey)||b.journey.length>30)throw new Error('Invalid journey');if(JSON.stringify(b).length>250000)throw new Error('Tour data exceeds the size limit');const sections:Record<string,string>={};for(const [k,v] of Object.entries(b.sections||{})){// Existing audited HTML is retained; new editorial fields are plain text.
const prior=(original||trustedCopy)?.sections?.[k];sections[k]=v===prior?String(v):text(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!)).replace(/\n/g,'<br/>');}
const value={operations:validateOperations(b.operations||original?.operations),path:b.path,name:text(b.name,300),internalRef:text(b.internalRef,60),status:b.status,bookingMode:b.bookingMode,tourType:text(b.tourType,100),productType:b.productType==='transfer'?'transfer':'tour',experienceType:b.experienceType==='shared'?'shared':'private',badges:Array.isArray(b.badges)?[...new Set(b.badges.map((s:any)=>text(s,80)).filter(Boolean))].slice(0,3):[],aeo:text(b.aeo,5000),origin:text(b.origin,100),destination:text(b.destination,200),duration:text(b.duration,80),featuredImage:text(b.featuredImage,1000),media:b.media.map((m:any)=>({...m,alt:text(m.alt,300),caption:text(m.caption,500),migrated:known.has(m.url)})),sections,journey:b.journey.map((j:any)=>({title:text(j.title,200),text:text(j.text,1000)})),pickup:text(b.pickup,3000),shortDescription:text(b.shortDescription,3000),related:(b.related||[]).filter((x:any)=>typeof x==='string'&&all[x]),migrated:!!migrated,seo:migrated?(baseline as any)[b.path].seo:{title:text(b.seo?.title||b.name,300),description:text(b.seo?.description,500),canonical:'',robots:'noindex',schema:[],socialImage:b.featuredImage},updated:now(),reviewRequired:!migrated&&b.reviewRequired!==false};if(value.status==='published'&&value.reviewRequired)throw new Error('Review URL, title, pickup, transfer duration, price, SEO and content before publishing a new tour.');if(prepareOnly)return value;await db().prepare('INSERT INTO settings (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('product:'+b.path,JSON.stringify(value)).run();if(!original){const g=trustedCopy?.golden?{...structuredClone(trustedCopy.golden),path:b.path,status:'REVIEW REQUIRED',reviews:[],translations:{},migration:{...emptyTourContent(b.path).migration},map:{...trustedCopy.golden.map,pointsReviewed:false}}:emptyTourContent(b.path);await db().prepare('INSERT INTO settings(key,value) VALUES (?,?) ON CONFLICT(key) DO NOTHING').bind('golden:'+b.path,JSON.stringify(g)).run();return {...value,golden:g};}return value;}
