import {attachConversion,marketingEnvironment} from './marketing';
import {revision} from './admin-content';
import {db,record,now,rows} from './server';
const origin='https://www.tangierexcursions.com';
export const hubPages=[{path:'/destinations/',name:'Explore Morocco & Spain with Tangier Excursions',description:'Discover destinations, private tours, day trips and journeys across Morocco and southern Spain.'},{path:'/faqs/',name:'Frequently Asked Questions',description:'Find answers about bookings, ferry travel, Morocco tours, payments, cancellations and planning your trip.'}];
export function virtualPage(p:any){return {path:p.path,name:p.name,kind:'page',title:p.name+' | Tangier Excursions',meta:{description:p.description||''},url:origin+p.path,canonical:[origin+p.path],structured_data:[JSON.stringify({'@context':'https://schema.org','@type':'CollectionPage','@id':origin+p.path+'#page',url:origin+p.path,name:p.name}),JSON.stringify({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:origin+'/'},{'@type':'ListItem',position:2,name:p.name,item:origin+p.path}]})],images:[],internal_links:[],pricing:[],content:p.content||'',gallery:p.image?[p.image]:[],hub:true,draft:false}}
export async function hubSettings(){const r=await db().prepare("SELECT key,value FROM settings WHERE key LIKE 'hub:%'").all<any>();return Object.fromEntries(r.results.map(x=>[x.key.slice(4),JSON.parse(x.value)]))}
export async function destinationPages(){const s=await hubSettings();const terms=(await db().prepare("SELECT id,data FROM discovery_terms WHERE kind IN ('destination','origin')").all<any>()).results;const counts=(await db().prepare('SELECT term,COUNT(*) AS n FROM discovery_links GROUP BY term').all<any>()).results;const out:any[]=[];for(const t of terms){const term=JSON.parse(t.data),p=s['destination:'+t.id];if(!term.visible||term.seoUrl||!p?.published||!p.slug||!p.longDescription)continue;const count=counts.find((x:any)=>x.term===t.id);if(!count?.n)continue;out.push({...virtualPage({path:'/destinations/'+p.slug+'/',name:term.name,description:term.description,content:p.longDescription,image:term.image}),destinationId:t.id})}return out}
const starter=[
 ['Booking & Reservations','How do I book a tour?','Open the experience, choose Check availability, then select your date and travelers. Review the price and booking terms before continuing. If a tour is enquiry-only, ask our team for a quote.','booking reserve'],
 ['Booking & Reservations','When is my booking confirmed?','A submitted enquiry is not a confirmed booking. Follow the status and confirmation sent for your reservation. This development preview only creates test records and does not take payment.','confirmation'],
 ['Payments','Can I pay by credit or debit card?','Payment options depend on the payment service available for your booking. Ask our team to confirm the available method before sending money. The development preview does not process payments.','card paypal payment'],
 ['Deposits & Balance','How much deposit is required?','The deposit is shown in your tour’s booking summary. It can differ between experiences; review the amount and the remaining balance before confirming.','deposit balance'],
 ['Cancellations & Refunds','What is your cancellation policy?','Read the cancellation policy on your chosen experience and in your booking confirmation. Refund and rescheduling conditions are specific to the reservation; contact us with your booking reference for help.','cancel refund weather ferry'],
 ['Spain to Morocco','Which Spanish cities do you serve?','Browse the starting locations in our Destinations directory to see the routes currently linked to tours. Ask us about your hotel or address before booking a pickup outside the listed route.','spain seville malaga marbella tarifa pickup'],
 ['Ferries','Are ferry tickets included?','Check the inclusions for your selected tour. Ferry arrangements vary between experiences, so do not assume tickets are included unless stated in your itinerary or confirmation.','ferry tarifa tickets'],
 ['Ferries','What happens if my ferry is delayed or cancelled?','Contact the team using the details in your booking confirmation. We will discuss the arrangements for your reservation; do not assume a later departure or refund is automatic.','delay weather tarifa sailing'],
 ['Passports & Entry','Where can I check passport and entry requirements?','Check the official entry requirements for your nationality and travel dates with the relevant authorities before booking. Do not send passport numbers through a general enquiry form.','passport children visa validity'],
 ['Pickup & Transfers','Can you pick us up from our hotel?','Check the pickup information for your experience. Share your hotel or pickup area with the team so the meeting point and any transfer supplement can be confirmed.','hotel transfer airport'],
 ['Private Tours','Can I customize the itinerary?','Use Plan a custom tour or Ask about this trip to describe what you would like to change. The team will confirm the route, inclusions, timing and any price difference.','custom private stops'],
 ['Morocco Multi-Day Tours','Are hotels, guides and meals included?','Review each day’s itinerary and the inclusions for your chosen tour. Accommodation, meals and local guiding differ by product and selected arrangements.','hotel accommodation guide meals luggage'],
 ['Desert Tours','Can I request a 4×4 instead of a camel ride?','Tell us your preference before booking. The team must confirm the transport options and any extra cost for the specific desert experience.','desert merzouga camel 4x4'],
 ['Families & Children','Can we request a child seat?','Include your children’s ages and seating requirements in your enquiry. Please wait for confirmation of the suitable seats and vehicle before booking.','baby family children seat'],
 ['Accessibility','Can the itinerary accommodate limited mobility?','Describe the access requirements and equipment you use before booking. Historic streets, steps and walking routes vary; the team will confirm what can be adapted for your specific journey.','wheelchair mobility steps chefchaouen'],
 ['Food & Dietary Requirements','Can I request vegetarian meals or share allergy requirements?','Tell us about dietary requirements before booking and reconfirm them with the team. Suitability and food preparation arrangements must be confirmed for the selected providers.','vegetarian gluten allergy halal food'],
 ['What to Wear','What should I pack for my tour?','Check the Before You Go section of your experience for route-specific guidance. Consider the season, walking surfaces and weather, and ask the team about any special equipment.','clothing shoes weather packing'],
 ['Currencies & Cash','Which currency will I pay in?','The currency selector provides planning estimates. Check the settlement currency in your booking summary and confirmation before paying.','euro dirham currency cash'],
 ['Guides & Drivers','Can I request a specific language or guide?','Share your language or guide preference when enquiring. Requests depend on availability and are only agreed once the team confirms them.','guide driver language licensed'],
 ['Custom Tours','Can you create a custom Morocco itinerary?','Yes—use Plan a custom tour to share your dates, starting city, destinations and interests. The team can discuss a proposal with you before you commit.','custom itinerary airport hotel'],
 ['Reviews','How can I share a review and photos?','Customers with an eligible completed booking can use their review invitation or account to submit feedback and guest photos. Reviews are moderated before display.','review photos feedback'],
 ['Contact & Support','How do I ask about an existing booking?','Choose Existing Booking on the contact form and include your reference. Avoid including passport or payment-card details in the message.','contact help support booking']
];
export async function helpFAQs(pages:any[],admin=false){const s=await hubSettings();const all:any[]=starter.map(([category,question,answer,keywords],i)=>({id:'planning-'+i,category,question,shortAnswer:answer,answer:'',keywords,order:i,published:true,source:'Planning guidance',relatedTours:[],relatedPages:[]}));const seen=new Set(all.map(x=>x.question.toLowerCase()));for(const p of pages.filter(p=>p.kind==='tour'&&!p.draft)){for(const f of p.product?.golden?.faqs||[]){const answer=(f.answer||[]).map((b:any)=>b.text||'').join('\n\n');if(!answer||seen.has(f.question.toLowerCase()))continue;seen.add(f.question.toLowerCase());all.push({id:'tour-'+f.id+'-'+p.path.replace(/\W/g,'').slice(-50),category:'Tour questions',question:f.question,shortAnswer:answer,answer:'',keywords:p.name,order:all.length,published:true,source:p.name,relatedTours:[p.path],relatedPages:[]})}}
 for(const [key,value] of Object.entries(s).filter(([k])=>k.startsWith('faq:'))){const i=all.findIndex(f=>f.id===key.slice(4));if(i>=0)all[i]={...all[i],...(value as any)};else all.push(value)}return all.filter(f=>admin||f.published).sort((a,b)=>a.order-b.order)}
export async function saveHub(b:any,owner:string){const s=await hubSettings(),clean=(v:any,n=6000)=>String(v||'').trim().slice(0,n);let key='',value:any;
 if(b.kind==='faq'){if(!clean(b.question)||!clean(b.shortAnswer))throw Error('Question and short answer are required');const id=clean(b.id,150)||crypto.randomUUID();key='faq:'+id;value={id,question:clean(b.question,400),shortAnswer:clean(b.shortAnswer),answer:clean(b.answer,12000),category:clean(b.category,100)||'Travel planning',keywords:clean(b.keywords,500),relatedTours:(b.relatedTours||[]).filter((p:any)=>typeof p==='string'&&/^\/(?!\/)/.test(p)),relatedPages:(b.relatedPages||[]).filter((p:any)=>typeof p==='string'&&/^\/(?!\/)/.test(p)),published:!!b.published,order:Math.max(0,Number(b.order)||0),reviewed:clean(b.reviewed,10),source:clean(b.source,300)||'Editorial',updated:now()};}
 else if(b.kind==='destination'){const term=await db().prepare('SELECT data FROM discovery_terms WHERE id=?').bind(b.id).first<any>();if(!term)throw Error('Select an existing destination or starting location');const t=JSON.parse(term.data);key='destination:'+b.id;const slug=clean(b.slug,100);if(slug&&!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))throw Error('Use a lowercase slug');if(Object.entries(s).some(([k,v]:any)=>k!==key&&k.startsWith('destination:')&&v.slug&&v.slug===slug))throw Error('This destination URL already exists');if(s[key]?.published&&s[key].slug!==slug)throw Error('Published destination URLs are protected');if(b.published&&(t.seoUrl||clean(b.longDescription).length<250))throw Error(t.seoUrl?'Use the existing SEO landing page; do not create a duplicate':'Add a useful destination introduction before publishing');value={id:b.id,slug,region:clean(b.region,100),country:clean(b.country||t.country,100),longDescription:clean(b.longDescription,18000),gallery:(b.gallery||[]).filter((x:any)=>typeof x==='string'&&/^\/(?:media|assets|wp-content)\//.test(x)),lat:b.lat===''||b.lat==null?null:Number(b.lat),lng:b.lng===''||b.lng==null?null:Number(b.lng),tips:clean(b.tips),highlights:clean(b.highlights),relatedBlog:(b.relatedBlog||[]).filter((p:any)=>typeof p==='string'&&/^\/(?!\/)/.test(p)),nearby:(b.nearby||[]).slice(0,20),badge:['','Featured','New','Popular','Top Destination'].includes(b.badge)?b.badge:'',published:!!b.published,updated:now()};if(value.lat!==null&&(!Number.isFinite(value.lat)||Math.abs(value.lat)>90)||value.lng!==null&&(!Number.isFinite(value.lng)||Math.abs(value.lng)>180))throw Error('Invalid map coordinates');}
 else if(b.kind==='about'){key='about';value={images:(b.images||[]).slice(0,6).map((x:any)=>{if(!/^\/(?:media|assets|wp-content)\//.test(x.url))throw Error('Choose permanent site media');return {url:clean(x.url,1000),alt:clean(x.alt,250),demo:x.demo!==false}})}}
 else throw Error('Unknown editor');if(b.kind==='faq'&&s[key])await revision(key,{...s[key],kind:'faq'},owner,'Before FAQ update');await record('admin-log',owner,{action:'Travel hub '+b.kind+' updated',target:key,previous:s[key]||null});await db().prepare('INSERT INTO settings(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('hub:'+key,JSON.stringify(value)).run();return value}
export async function supportEnquiry(b:any){const categories=['General Enquiry','Existing Booking','Custom Tour','Spain to Morocco Trip','Morocco Tour','Transfer','Hotel / Agency Partner','Other'];if(b.websiteTrap)throw Error('Unable to submit');if(!categories.includes(b.category)||!b.name?.trim()||!/^\S+@\S+\.\S+$/.test(b.email||'')||!b.message?.trim()||b.consent!==true)throw Error('Enter your name, email, message and consent');if(b.category==='Existing Booking'&&!b.reference?.trim())throw Error('Enter your booking reference');const recent=await db().prepare("SELECT COUNT(*) AS n FROM records WHERE kind='lead' AND json_extract(data,'$.email')=? AND created>?").bind(String(b.email).trim(),new Date(Date.now()-600000).toISOString()).first<any>();if(recent?.n>=5)throw Error('Please wait before sending another enquiry');const data:any={environment:marketingEnvironment(),type:'contact',status:'new',source:'/transport_booking/',category:b.category};for(const k of ['name','email','phone','country','subject','message','reference','date','guests','pickup','destinations','hotel','language','interests','company'])data[k]=String(b[k]||'').trim().slice(0,k==='message'?6000:300);data.notes=data.message;const id='ENQ-'+crypto.randomUUID().slice(0,8).toUpperCase();await record('lead','guest',data,id);await attachConversion('lead',id,data.source,'submit_enquiry');return {id}}
export async function updateEnquiry(b:any,owner:string){const r=await db().prepare("SELECT data FROM records WHERE id=? AND kind='lead'").bind(b.id).first<any>();if(!r||!['new','in-progress','replied','closed'].includes(b.status))throw Error('Invalid enquiry');const old=JSON.parse(r.data);await db().prepare('UPDATE records SET data=? WHERE id=?').bind(JSON.stringify({...old,status:b.status,assigned:String(b.assigned||'').slice(0,150),internalNotes:String(b.internalNotes||'').slice(0,6000)}),b.id).run();await record('admin-log',owner,{action:'Enquiry updated',target:b.id,previous:old});return {ok:true}}
export async function publicHubSettings(){const s=await hubSettings();return Object.fromEntries(Object.entries(s).filter(([k])=>!k.startsWith('faq:')).map(([k,v]:any)=>[k,k.startsWith('destination:')&&!v.published?{country:v.country,region:v.region,badge:v.badge,published:false}:v]))}
