import {sqliteTable,text,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const records=sqliteTable('records',{id:text('id').primaryKey(),kind:text('kind').notNull(),owner:text('owner').notNull(),data:text('data').notNull(),created:text('created').notNull() },t=>[index('records_kind_owner').on(t.kind,t.owner),index('records_kind_created').on(t.kind,t.created)]);
export const bookings=sqliteTable('bookings',{id:text('id').primaryKey(),owner:text('owner').notNull(),tour:text('tour').notNull(),date:text('date').notNull(),guests:integer('guests').notNull(),total:integer('total').notNull(),status:text('status').notNull(),token:text('token').notNull(),data:text('data').notNull(),created:text('created').notNull(),requestKey:text('request_key').notNull()},t=>[index('bookings_owner').on(t.owner),index('bookings_created_status').on(t.created,t.status),index('bookings_tour_date_status').on(t.tour,t.date,t.status),uniqueIndex('bookings_token').on(t.token),uniqueIndex('bookings_request').on(t.owner,t.requestKey)]);
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const sessions=sqliteTable('sessions',{token:text('token').primaryKey(),owner:text('owner').notNull(),role:text('role').notNull(),expires:integer('expires').notNull()});
export const discoveryTerms=sqliteTable('discovery_terms',{id:text('id').primaryKey(),kind:text('kind').notNull(),data:text('data').notNull(),updated:text('updated').notNull()},t=>[index('discovery_terms_kind').on(t.kind)]);
export const discoveryLinks=sqliteTable('discovery_links',{id:text('id').primaryKey(),tour:text('tour').notNull(),term:text('term').notNull()},t=>[uniqueIndex('discovery_links_tour_term').on(t.tour,t.term),index('discovery_links_term_tour').on(t.term,t.tour)]);
export const customerAuthSessions=sqliteTable('customer_auth_sessions',{tokenHash:text('token_hash').primaryKey(),owner:text('owner').notNull(),email:text('email').notNull(),name:text('name').notNull(),expires:integer('expires').notNull()},t=>[index('customer_auth_sessions_owner').on(t.owner),index('customer_auth_sessions_expiry').on(t.expires)]);
export const customerAuthLimits=sqliteTable('customer_auth_limits',{id:text('id').primaryKey(),attempts:integer('attempts').notNull(),expires:integer('expires').notNull()},t=>[index('customer_auth_limits_expiry').on(t.expires)]);

export const marketingVisitors=sqliteTable('marketing_visitors',{id:text('id').primaryKey(),environment:text('environment').notNull(),first:text('first_touch'),last:text('last_touch'),created:text('created').notNull(),lastSeen:text('last_seen').notNull()},t=>[index('marketing_visitors_expiry').on(t.lastSeen)]);
export const marketingSessions=sqliteTable('marketing_sessions',{id:text('id').primaryKey(),visitor:text('visitor').notNull(),environment:text('environment').notNull(),created:text('created').notNull(),lastSeen:text('last_seen').notNull()},t=>[index('marketing_sessions_expiry').on(t.lastSeen),index('marketing_sessions_visitor').on(t.visitor)]);
export const marketingEvents=sqliteTable('marketing_events',{id:text('id').primaryKey(),name:text('name').notNull(),created:text('created').notNull(),environment:text('environment').notNull(),visitor:text('visitor'),session:text('session'),path:text('path'),booking:text('booking'),context:text('context').notNull()},t=>[index('marketing_events_env_date').on(t.environment,t.created),index('marketing_events_session_date').on(t.session,t.created)]);
export const marketingConversions=sqliteTable('marketing_conversions',{id:text('id').primaryKey(),kind:text('kind').notNull(),target:text('target').notNull(),environment:text('environment').notNull(),visitor:text('visitor'),session:text('session'),first:text('first_touch'),last:text('last_touch'),path:text('path'),created:text('created').notNull()},t=>[index('marketing_conversion_env_date').on(t.environment,t.created),uniqueIndex('marketing_conversion_target').on(t.kind,t.target),index('marketing_conversion_expiry').on(t.created)]);
